/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminFamilySummary
 */
export interface AdminFamilySummary {
    /**
     * 
     * @type {string}
     * @memberof AdminFamilySummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminFamilySummary
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AdminFamilySummary
     */
    timezone: string;
    /**
     * 
     * @type {AdminFamilySummaryStatusEnum}
     * @memberof AdminFamilySummary
     */
    status: AdminFamilySummaryStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof AdminFamilySummary
     */
    childCount: number;
    /**
     * 
     * @type {number}
     * @memberof AdminFamilySummary
     */
    memberCount: number;
    /**
     * 
     * @type {Date}
     * @memberof AdminFamilySummary
     */
    createdAt: Date;
}


/**
 * @export
 */
export const AdminFamilySummaryStatusEnum = {
    active: 'active',
    locked: 'locked',
    deleting: 'deleting',
    deleted: 'deleted'
} as const;
export type AdminFamilySummaryStatusEnum = typeof AdminFamilySummaryStatusEnum[keyof typeof AdminFamilySummaryStatusEnum];


/**
 * Check if a given object implements the AdminFamilySummary interface.
 */
export function instanceOfAdminFamilySummary(value: object): value is AdminFamilySummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('childCount' in value) || value['childCount'] === undefined) return false;
    if (!('memberCount' in value) || value['memberCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AdminFamilySummaryFromJSON(json: any): AdminFamilySummary {
    return AdminFamilySummaryFromJSONTyped(json, false);
}

export function AdminFamilySummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminFamilySummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'timezone': json['timezone'],
        'status': json['status'],
        'childCount': json['childCount'],
        'memberCount': json['memberCount'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function AdminFamilySummaryToJSON(json: any): AdminFamilySummary {
    return AdminFamilySummaryToJSONTyped(json, false);
}

export function AdminFamilySummaryToJSONTyped(value?: AdminFamilySummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'timezone': value['timezone'],
        'status': value['status'],
        'childCount': value['childCount'],
        'memberCount': value['memberCount'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

