/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminMediaAccessGrant
 */
export interface AdminMediaAccessGrant {
    /**
     * 
     * @type {string}
     * @memberof AdminMediaAccessGrant
     */
    mediaAssetId: string;
    /**
     * 
     * @type {string}
     * @memberof AdminMediaAccessGrant
     */
    familyId: string;
    /**
     * 
     * @type {string}
     * @memberof AdminMediaAccessGrant
     */
    accessUrl: string;
    /**
     * 
     * @type {Date}
     * @memberof AdminMediaAccessGrant
     */
    expiresAt: Date;
    /**
     * 
     * @type {string}
     * @memberof AdminMediaAccessGrant
     */
    auditLogId: string;
}

/**
 * Check if a given object implements the AdminMediaAccessGrant interface.
 */
export function instanceOfAdminMediaAccessGrant(value: object): value is AdminMediaAccessGrant {
    if (!('mediaAssetId' in value) || value['mediaAssetId'] === undefined) return false;
    if (!('familyId' in value) || value['familyId'] === undefined) return false;
    if (!('accessUrl' in value) || value['accessUrl'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('auditLogId' in value) || value['auditLogId'] === undefined) return false;
    return true;
}

export function AdminMediaAccessGrantFromJSON(json: any): AdminMediaAccessGrant {
    return AdminMediaAccessGrantFromJSONTyped(json, false);
}

export function AdminMediaAccessGrantFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminMediaAccessGrant {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaAssetId': json['mediaAssetId'],
        'familyId': json['familyId'],
        'accessUrl': json['accessUrl'],
        'expiresAt': (new Date(json['expiresAt'])),
        'auditLogId': json['auditLogId'],
    };
}

export function AdminMediaAccessGrantToJSON(json: any): AdminMediaAccessGrant {
    return AdminMediaAccessGrantToJSONTyped(json, false);
}

export function AdminMediaAccessGrantToJSONTyped(value?: AdminMediaAccessGrant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mediaAssetId': value['mediaAssetId'],
        'familyId': value['familyId'],
        'accessUrl': value['accessUrl'],
        'expiresAt': value['expiresAt'].toISOString(),
        'auditLogId': value['auditLogId'],
    };
}

