/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAuditLog
 */
export interface AdminAuditLog {
    /**
     * 
     * @type {string}
     * @memberof AdminAuditLog
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditLog
     */
    familyId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditLog
     */
    actorUserId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditLog
     */
    actorRole: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditLog
     */
    action: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditLog
     */
    resourceType: string;
    /**
     * 
     * @type {string}
     * @memberof AdminAuditLog
     */
    resourceId?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AdminAuditLog
     */
    metadata: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof AdminAuditLog
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the AdminAuditLog interface.
 */
export function instanceOfAdminAuditLog(value: object): value is AdminAuditLog {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('actorRole' in value) || value['actorRole'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AdminAuditLogFromJSON(json: any): AdminAuditLog {
    return AdminAuditLogFromJSONTyped(json, false);
}

export function AdminAuditLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAuditLog {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'familyId': json['familyId'] === undefined ? undefined : json['familyId'] === null ? null : json['familyId'],
        'actorUserId': json['actorUserId'] === undefined ? undefined : json['actorUserId'] === null ? null : json['actorUserId'],
        'actorRole': json['actorRole'],
        'action': json['action'],
        'resourceType': json['resourceType'],
        'resourceId': json['resourceId'] === undefined ? undefined : json['resourceId'] === null ? null : json['resourceId'],
        'metadata': json['metadata'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function AdminAuditLogToJSON(json: any): AdminAuditLog {
    return AdminAuditLogToJSONTyped(json, false);
}

export function AdminAuditLogToJSONTyped(value?: AdminAuditLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'familyId': value['familyId'],
        'actorUserId': value['actorUserId'],
        'actorRole': value['actorRole'],
        'action': value['action'],
        'resourceType': value['resourceType'],
        'resourceId': value['resourceId'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

