/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminMediaAccessGrant } from './AdminMediaAccessGrant';
import {
    AdminMediaAccessGrantFromJSON,
    AdminMediaAccessGrantFromJSONTyped,
    AdminMediaAccessGrantToJSON,
    AdminMediaAccessGrantToJSONTyped,
} from './AdminMediaAccessGrant';

/**
 * 
 * @export
 * @interface AdminMediaAccessGrantPage
 */
export interface AdminMediaAccessGrantPage {
    /**
     * 
     * @type {Array<AdminMediaAccessGrant>}
     * @memberof AdminMediaAccessGrantPage
     */
    items: Array<AdminMediaAccessGrant>;
    /**
     * 
     * @type {number}
     * @memberof AdminMediaAccessGrantPage
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof AdminMediaAccessGrantPage
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof AdminMediaAccessGrantPage
     */
    limit: number;
    /**
     * 
     * @type {boolean}
     * @memberof AdminMediaAccessGrantPage
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the AdminMediaAccessGrantPage interface.
 */
export function instanceOfAdminMediaAccessGrantPage(value: object): value is AdminMediaAccessGrantPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
    return true;
}

export function AdminMediaAccessGrantPageFromJSON(json: any): AdminMediaAccessGrantPage {
    return AdminMediaAccessGrantPageFromJSONTyped(json, false);
}

export function AdminMediaAccessGrantPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminMediaAccessGrantPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(AdminMediaAccessGrantFromJSON)),
        'total': json['total'],
        'offset': json['offset'],
        'limit': json['limit'],
        'hasMore': json['hasMore'],
    };
}

export function AdminMediaAccessGrantPageToJSON(json: any): AdminMediaAccessGrantPage {
    return AdminMediaAccessGrantPageToJSONTyped(json, false);
}

export function AdminMediaAccessGrantPageToJSONTyped(value?: AdminMediaAccessGrantPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(AdminMediaAccessGrantToJSON)),
        'total': value['total'],
        'offset': value['offset'],
        'limit': value['limit'],
        'hasMore': value['hasMore'],
    };
}

