/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiPrecheck
 */
export interface AiPrecheck {
    /**
     * 
     * @type {string}
     * @memberof AiPrecheck
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AiPrecheck
     */
    submissionId: string;
    /**
     * 
     * @type {string}
     * @memberof AiPrecheck
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof AiPrecheck
     */
    summary: string;
    /**
     * 
     * @type {number}
     * @memberof AiPrecheck
     */
    confidence?: number | null;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof AiPrecheck
     */
    flags: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AiPrecheck
     */
    model: { [key: string]: any; };
}

/**
 * Check if a given object implements the AiPrecheck interface.
 */
export function instanceOfAiPrecheck(value: object): value is AiPrecheck {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('submissionId' in value) || value['submissionId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('flags' in value) || value['flags'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    return true;
}

export function AiPrecheckFromJSON(json: any): AiPrecheck {
    return AiPrecheckFromJSONTyped(json, false);
}

export function AiPrecheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiPrecheck {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'submissionId': json['submissionId'],
        'type': json['type'],
        'summary': json['summary'],
        'confidence': json['confidence'] === undefined ? undefined : json['confidence'] === null ? null : json['confidence'],
        'flags': json['flags'],
        'model': json['model'],
    };
}

export function AiPrecheckToJSON(json: any): AiPrecheck {
    return AiPrecheckToJSONTyped(json, false);
}

export function AiPrecheckToJSONTyped(value?: AiPrecheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'submissionId': value['submissionId'],
        'type': value['type'],
        'summary': value['summary'],
        'confidence': value['confidence'],
        'flags': value['flags'],
        'model': value['model'],
    };
}

