/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiTextModelProviderWriteRequest
 */
export interface AiTextModelProviderWriteRequest {
    /**
     * 
     * @type {string}
     * @memberof AiTextModelProviderWriteRequest
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof AiTextModelProviderWriteRequest
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof AiTextModelProviderWriteRequest
     */
    providerType: string;
    /**
     * 
     * @type {string}
     * @memberof AiTextModelProviderWriteRequest
     */
    baseUrl: string;
    /**
     * 
     * @type {string}
     * @memberof AiTextModelProviderWriteRequest
     */
    apiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof AiTextModelProviderWriteRequest
     */
    modelName: string;
    /**
     * 
     * @type {string}
     * @memberof AiTextModelProviderWriteRequest
     */
    capability: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AiTextModelProviderWriteRequest
     */
    extraParams?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof AiTextModelProviderWriteRequest
     */
    isDefault?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AiTextModelProviderWriteRequest
     */
    isEnabled?: boolean;
}

/**
 * Check if a given object implements the AiTextModelProviderWriteRequest interface.
 */
export function instanceOfAiTextModelProviderWriteRequest(value: object): value is AiTextModelProviderWriteRequest {
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('providerType' in value) || value['providerType'] === undefined) return false;
    if (!('baseUrl' in value) || value['baseUrl'] === undefined) return false;
    if (!('modelName' in value) || value['modelName'] === undefined) return false;
    if (!('capability' in value) || value['capability'] === undefined) return false;
    return true;
}

export function AiTextModelProviderWriteRequestFromJSON(json: any): AiTextModelProviderWriteRequest {
    return AiTextModelProviderWriteRequestFromJSONTyped(json, false);
}

export function AiTextModelProviderWriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiTextModelProviderWriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'displayName': json['displayName'],
        'providerType': json['providerType'],
        'baseUrl': json['baseUrl'],
        'apiKey': json['apiKey'] == null ? undefined : json['apiKey'],
        'modelName': json['modelName'],
        'capability': json['capability'],
        'extraParams': json['extraParams'] == null ? undefined : json['extraParams'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
        'isEnabled': json['isEnabled'] == null ? undefined : json['isEnabled'],
    };
}

export function AiTextModelProviderWriteRequestToJSON(json: any): AiTextModelProviderWriteRequest {
    return AiTextModelProviderWriteRequestToJSONTyped(json, false);
}

export function AiTextModelProviderWriteRequestToJSONTyped(value?: AiTextModelProviderWriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'displayName': value['displayName'],
        'providerType': value['providerType'],
        'baseUrl': value['baseUrl'],
        'apiKey': value['apiKey'],
        'modelName': value['modelName'],
        'capability': value['capability'],
        'extraParams': value['extraParams'],
        'isDefault': value['isDefault'],
        'isEnabled': value['isEnabled'],
    };
}

