/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiTextProviderTestResponse
 */
export interface AiTextProviderTestResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AiTextProviderTestResponse
     */
    ok: boolean;
    /**
     * 
     * @type {string}
     * @memberof AiTextProviderTestResponse
     */
    message: string;
}

/**
 * Check if a given object implements the AiTextProviderTestResponse interface.
 */
export function instanceOfAiTextProviderTestResponse(value: object): value is AiTextProviderTestResponse {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AiTextProviderTestResponseFromJSON(json: any): AiTextProviderTestResponse {
    return AiTextProviderTestResponseFromJSONTyped(json, false);
}

export function AiTextProviderTestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiTextProviderTestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'message': json['message'],
    };
}

export function AiTextProviderTestResponseToJSON(json: any): AiTextProviderTestResponse {
    return AiTextProviderTestResponseToJSONTyped(json, false);
}

export function AiTextProviderTestResponseToJSONTyped(value?: AiTextProviderTestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'message': value['message'],
    };
}

