/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArrangeRoomItemRequestPosition } from './ArrangeRoomItemRequestPosition';
import {
    ArrangeRoomItemRequestPositionFromJSON,
    ArrangeRoomItemRequestPositionFromJSONTyped,
    ArrangeRoomItemRequestPositionToJSON,
    ArrangeRoomItemRequestPositionToJSONTyped,
} from './ArrangeRoomItemRequestPosition';

/**
 * 
 * @export
 * @interface ArrangeRoomItemRequest
 */
export interface ArrangeRoomItemRequest {
    /**
     * 
     * @type {ArrangeRoomItemRequestPosition}
     * @memberof ArrangeRoomItemRequest
     */
    position: ArrangeRoomItemRequestPosition;
}

/**
 * Check if a given object implements the ArrangeRoomItemRequest interface.
 */
export function instanceOfArrangeRoomItemRequest(value: object): value is ArrangeRoomItemRequest {
    if (!('position' in value) || value['position'] === undefined) return false;
    return true;
}

export function ArrangeRoomItemRequestFromJSON(json: any): ArrangeRoomItemRequest {
    return ArrangeRoomItemRequestFromJSONTyped(json, false);
}

export function ArrangeRoomItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArrangeRoomItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'position': ArrangeRoomItemRequestPositionFromJSON(json['position']),
    };
}

export function ArrangeRoomItemRequestToJSON(json: any): ArrangeRoomItemRequest {
    return ArrangeRoomItemRequestToJSONTyped(json, false);
}

export function ArrangeRoomItemRequestToJSONTyped(value?: ArrangeRoomItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'position': ArrangeRoomItemRequestPositionToJSON(value['position']),
    };
}

