/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttachWishImageRequest
 */
export interface AttachWishImageRequest {
    /**
     * 
     * @type {string}
     * @memberof AttachWishImageRequest
     */
    mediaId: string;
    /**
     * 
     * @type {AttachWishImageRequestSourceTypeEnum}
     * @memberof AttachWishImageRequest
     */
    sourceType?: AttachWishImageRequestSourceTypeEnum;
}


/**
 * @export
 */
export const AttachWishImageRequestSourceTypeEnum = {
    uploaded: 'uploaded',
    generated: 'generated',
    reused: 'reused',
    imported: 'imported'
} as const;
export type AttachWishImageRequestSourceTypeEnum = typeof AttachWishImageRequestSourceTypeEnum[keyof typeof AttachWishImageRequestSourceTypeEnum];


/**
 * Check if a given object implements the AttachWishImageRequest interface.
 */
export function instanceOfAttachWishImageRequest(value: object): value is AttachWishImageRequest {
    if (!('mediaId' in value) || value['mediaId'] === undefined) return false;
    return true;
}

export function AttachWishImageRequestFromJSON(json: any): AttachWishImageRequest {
    return AttachWishImageRequestFromJSONTyped(json, false);
}

export function AttachWishImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachWishImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaId': json['mediaId'],
        'sourceType': json['sourceType'] == null ? undefined : json['sourceType'],
    };
}

export function AttachWishImageRequestToJSON(json: any): AttachWishImageRequest {
    return AttachWishImageRequestToJSONTyped(json, false);
}

export function AttachWishImageRequestToJSONTyped(value?: AttachWishImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mediaId': value['mediaId'],
        'sourceType': value['sourceType'],
    };
}

