/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageModelProvider } from './ImageModelProvider';
import {
    ImageModelProviderFromJSON,
    ImageModelProviderFromJSONTyped,
    ImageModelProviderToJSON,
    ImageModelProviderToJSONTyped,
} from './ImageModelProvider';

/**
 * 
 * @export
 * @interface BusinessImageModelProviderList
 */
export interface BusinessImageModelProviderList {
    /**
     * 
     * @type {string}
     * @memberof BusinessImageModelProviderList
     */
    usageCode: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessImageModelProviderList
     */
    selectedProviderCode?: string | null;
    /**
     * 
     * @type {Array<ImageModelProvider>}
     * @memberof BusinessImageModelProviderList
     */
    providers: Array<ImageModelProvider>;
}

/**
 * Check if a given object implements the BusinessImageModelProviderList interface.
 */
export function instanceOfBusinessImageModelProviderList(value: object): value is BusinessImageModelProviderList {
    if (!('usageCode' in value) || value['usageCode'] === undefined) return false;
    if (!('providers' in value) || value['providers'] === undefined) return false;
    return true;
}

export function BusinessImageModelProviderListFromJSON(json: any): BusinessImageModelProviderList {
    return BusinessImageModelProviderListFromJSONTyped(json, false);
}

export function BusinessImageModelProviderListFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessImageModelProviderList {
    if (json == null) {
        return json;
    }
    return {
        
        'usageCode': json['usageCode'],
        'selectedProviderCode': json['selectedProviderCode'] === undefined ? undefined : json['selectedProviderCode'] === null ? null : json['selectedProviderCode'],
        'providers': ((json['providers'] as Array<any>).map(ImageModelProviderFromJSON)),
    };
}

export function BusinessImageModelProviderListToJSON(json: any): BusinessImageModelProviderList {
    return BusinessImageModelProviderListToJSONTyped(json, false);
}

export function BusinessImageModelProviderListToJSONTyped(value?: BusinessImageModelProviderList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usageCode': value['usageCode'],
        'selectedProviderCode': value['selectedProviderCode'],
        'providers': ((value['providers'] as Array<any>).map(ImageModelProviderToJSON)),
    };
}

