/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaAsset } from './MediaAsset';
import {
    MediaAssetFromJSON,
    MediaAssetFromJSONTyped,
    MediaAssetToJSON,
    MediaAssetToJSONTyped,
} from './MediaAsset';

/**
 * 
 * @export
 * @interface ChildFeedbackCard
 */
export interface ChildFeedbackCard {
    /**
     * 
     * @type {string}
     * @memberof ChildFeedbackCard
     */
    reviewId: string;
    /**
     * 
     * @type {string}
     * @memberof ChildFeedbackCard
     */
    taskTitle: string;
    /**
     * 
     * @type {ChildFeedbackCardDecisionEnum}
     * @memberof ChildFeedbackCard
     */
    decision: ChildFeedbackCardDecisionEnum;
    /**
     * 
     * @type {string}
     * @memberof ChildFeedbackCard
     */
    emoji?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChildFeedbackCard
     */
    text?: string | null;
    /**
     * 
     * @type {MediaAsset}
     * @memberof ChildFeedbackCard
     */
    audioMedia?: MediaAsset | null;
    /**
     * 
     * @type {Date}
     * @memberof ChildFeedbackCard
     */
    createdAt: Date;
}


/**
 * @export
 */
export const ChildFeedbackCardDecisionEnum = {
    approved: 'approved',
    needs_revision: 'needs_revision'
} as const;
export type ChildFeedbackCardDecisionEnum = typeof ChildFeedbackCardDecisionEnum[keyof typeof ChildFeedbackCardDecisionEnum];


/**
 * Check if a given object implements the ChildFeedbackCard interface.
 */
export function instanceOfChildFeedbackCard(value: object): value is ChildFeedbackCard {
    if (!('reviewId' in value) || value['reviewId'] === undefined) return false;
    if (!('taskTitle' in value) || value['taskTitle'] === undefined) return false;
    if (!('decision' in value) || value['decision'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ChildFeedbackCardFromJSON(json: any): ChildFeedbackCard {
    return ChildFeedbackCardFromJSONTyped(json, false);
}

export function ChildFeedbackCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChildFeedbackCard {
    if (json == null) {
        return json;
    }
    return {
        
        'reviewId': json['reviewId'],
        'taskTitle': json['taskTitle'],
        'decision': json['decision'],
        'emoji': json['emoji'] === undefined ? undefined : json['emoji'] === null ? null : json['emoji'],
        'text': json['text'] === undefined ? undefined : json['text'] === null ? null : json['text'],
        'audioMedia': json['audioMedia'] === undefined ? undefined : json['audioMedia'] === null ? null : MediaAssetFromJSON(json['audioMedia']),
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ChildFeedbackCardToJSON(json: any): ChildFeedbackCard {
    return ChildFeedbackCardToJSONTyped(json, false);
}

export function ChildFeedbackCardToJSONTyped(value?: ChildFeedbackCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reviewId': value['reviewId'],
        'taskTitle': value['taskTitle'],
        'decision': value['decision'],
        'emoji': value['emoji'],
        'text': value['text'],
        'audioMedia': MediaAssetToJSON(value['audioMedia']),
        'createdAt': value['createdAt'].toISOString(),
    };
}

