/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WeeklyMemory } from './WeeklyMemory';
import {
    WeeklyMemoryFromJSON,
    WeeklyMemoryFromJSONTyped,
    WeeklyMemoryToJSON,
    WeeklyMemoryToJSONTyped,
} from './WeeklyMemory';
import type { TodaySnapshot } from './TodaySnapshot';
import {
    TodaySnapshotFromJSON,
    TodaySnapshotFromJSONTyped,
    TodaySnapshotToJSON,
    TodaySnapshotToJSONTyped,
} from './TodaySnapshot';
import type { ChildFeedbackCard } from './ChildFeedbackCard';
import {
    ChildFeedbackCardFromJSON,
    ChildFeedbackCardFromJSONTyped,
    ChildFeedbackCardToJSON,
    ChildFeedbackCardToJSONTyped,
} from './ChildFeedbackCard';
import type { ChildProfile } from './ChildProfile';
import {
    ChildProfileFromJSON,
    ChildProfileFromJSONTyped,
    ChildProfileToJSON,
    ChildProfileToJSONTyped,
} from './ChildProfile';
import type { Wish } from './Wish';
import {
    WishFromJSON,
    WishFromJSONTyped,
    WishToJSON,
    WishToJSONTyped,
} from './Wish';
import type { RoomState } from './RoomState';
import {
    RoomStateFromJSON,
    RoomStateFromJSONTyped,
    RoomStateToJSON,
    RoomStateToJSONTyped,
} from './RoomState';

/**
 * 
 * @export
 * @interface ChildHomeContext
 */
export interface ChildHomeContext {
    /**
     * 
     * @type {ChildProfile}
     * @memberof ChildHomeContext
     */
    child: ChildProfile;
    /**
     * 
     * @type {TodaySnapshot}
     * @memberof ChildHomeContext
     */
    today: TodaySnapshot;
    /**
     * 
     * @type {Wish}
     * @memberof ChildHomeContext
     */
    currentWish?: Wish | null;
    /**
     * 
     * @type {RoomState}
     * @memberof ChildHomeContext
     */
    room: RoomState;
    /**
     * 
     * @type {WeeklyMemory}
     * @memberof ChildHomeContext
     */
    latestMemory?: WeeklyMemory | null;
    /**
     * 
     * @type {ChildFeedbackCard}
     * @memberof ChildHomeContext
     */
    latestFeedback?: ChildFeedbackCard | null;
    /**
     * 
     * @type {number}
     * @memberof ChildHomeContext
     */
    unreadNotifications: number;
}

/**
 * Check if a given object implements the ChildHomeContext interface.
 */
export function instanceOfChildHomeContext(value: object): value is ChildHomeContext {
    if (!('child' in value) || value['child'] === undefined) return false;
    if (!('today' in value) || value['today'] === undefined) return false;
    if (!('room' in value) || value['room'] === undefined) return false;
    if (!('unreadNotifications' in value) || value['unreadNotifications'] === undefined) return false;
    return true;
}

export function ChildHomeContextFromJSON(json: any): ChildHomeContext {
    return ChildHomeContextFromJSONTyped(json, false);
}

export function ChildHomeContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChildHomeContext {
    if (json == null) {
        return json;
    }
    return {
        
        'child': ChildProfileFromJSON(json['child']),
        'today': TodaySnapshotFromJSON(json['today']),
        'currentWish': json['currentWish'] === undefined ? undefined : json['currentWish'] === null ? null : WishFromJSON(json['currentWish']),
        'room': RoomStateFromJSON(json['room']),
        'latestMemory': json['latestMemory'] === undefined ? undefined : json['latestMemory'] === null ? null : WeeklyMemoryFromJSON(json['latestMemory']),
        'latestFeedback': json['latestFeedback'] === undefined ? undefined : json['latestFeedback'] === null ? null : ChildFeedbackCardFromJSON(json['latestFeedback']),
        'unreadNotifications': json['unreadNotifications'],
    };
}

export function ChildHomeContextToJSON(json: any): ChildHomeContext {
    return ChildHomeContextToJSONTyped(json, false);
}

export function ChildHomeContextToJSONTyped(value?: ChildHomeContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'child': ChildProfileToJSON(value['child']),
        'today': TodaySnapshotToJSON(value['today']),
        'currentWish': WishToJSON(value['currentWish']),
        'room': RoomStateToJSON(value['room']),
        'latestMemory': WeeklyMemoryToJSON(value['latestMemory']),
        'latestFeedback': ChildFeedbackCardToJSON(value['latestFeedback']),
        'unreadNotifications': value['unreadNotifications'],
    };
}

