/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChildProfile
 */
export interface ChildProfile {
    /**
     * 
     * @type {string}
     * @memberof ChildProfile
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ChildProfile
     */
    familyId: string;
    /**
     * 
     * @type {string}
     * @memberof ChildProfile
     */
    nickname: string;
    /**
     * 
     * @type {number}
     * @memberof ChildProfile
     */
    birthYear?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ChildProfile
     */
    avatarAsset?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChildProfile
     */
    roomTheme: string;
    /**
     * 
     * @type {ChildProfileStatusEnum}
     * @memberof ChildProfile
     */
    status: ChildProfileStatusEnum;
}


/**
 * @export
 */
export const ChildProfileStatusEnum = {
    active: 'active',
    archived: 'archived'
} as const;
export type ChildProfileStatusEnum = typeof ChildProfileStatusEnum[keyof typeof ChildProfileStatusEnum];


/**
 * Check if a given object implements the ChildProfile interface.
 */
export function instanceOfChildProfile(value: object): value is ChildProfile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('familyId' in value) || value['familyId'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('roomTheme' in value) || value['roomTheme'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ChildProfileFromJSON(json: any): ChildProfile {
    return ChildProfileFromJSONTyped(json, false);
}

export function ChildProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChildProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'familyId': json['familyId'],
        'nickname': json['nickname'],
        'birthYear': json['birthYear'] === undefined ? undefined : json['birthYear'] === null ? null : json['birthYear'],
        'avatarAsset': json['avatarAsset'] === undefined ? undefined : json['avatarAsset'] === null ? null : json['avatarAsset'],
        'roomTheme': json['roomTheme'],
        'status': json['status'],
    };
}

export function ChildProfileToJSON(json: any): ChildProfile {
    return ChildProfileToJSONTyped(json, false);
}

export function ChildProfileToJSONTyped(value?: ChildProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'familyId': value['familyId'],
        'nickname': value['nickname'],
        'birthYear': value['birthYear'],
        'avatarAsset': value['avatarAsset'],
        'roomTheme': value['roomTheme'],
        'status': value['status'],
    };
}

