/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimOutboxEventsRequest
 */
export interface ClaimOutboxEventsRequest {
    /**
     * 
     * @type {number}
     * @memberof ClaimOutboxEventsRequest
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ClaimOutboxEventsRequest
     */
    leaseSeconds?: number;
}

/**
 * Check if a given object implements the ClaimOutboxEventsRequest interface.
 */
export function instanceOfClaimOutboxEventsRequest(value: object): value is ClaimOutboxEventsRequest {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ClaimOutboxEventsRequestFromJSON(json: any): ClaimOutboxEventsRequest {
    return ClaimOutboxEventsRequestFromJSONTyped(json, false);
}

export function ClaimOutboxEventsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimOutboxEventsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'leaseSeconds': json['leaseSeconds'] == null ? undefined : json['leaseSeconds'],
    };
}

export function ClaimOutboxEventsRequestToJSON(json: any): ClaimOutboxEventsRequest {
    return ClaimOutboxEventsRequestToJSONTyped(json, false);
}

export function ClaimOutboxEventsRequestToJSONTyped(value?: ClaimOutboxEventsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'leaseSeconds': value['leaseSeconds'],
    };
}

