/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimNotificationEventsRequest
 */
export interface ClaimNotificationEventsRequest {
    /**
     * 
     * @type {number}
     * @memberof ClaimNotificationEventsRequest
     */
    limit: number;
}

/**
 * Check if a given object implements the ClaimNotificationEventsRequest interface.
 */
export function instanceOfClaimNotificationEventsRequest(value: object): value is ClaimNotificationEventsRequest {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ClaimNotificationEventsRequestFromJSON(json: any): ClaimNotificationEventsRequest {
    return ClaimNotificationEventsRequestFromJSONTyped(json, false);
}

export function ClaimNotificationEventsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimNotificationEventsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
    };
}

export function ClaimNotificationEventsRequestToJSON(json: any): ClaimNotificationEventsRequest {
    return ClaimNotificationEventsRequestToJSONTyped(json, false);
}

export function ClaimNotificationEventsRequestToJSONTyped(value?: ClaimNotificationEventsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
    };
}

