/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChildRequest
 */
export interface CreateChildRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateChildRequest
     */
    nickname: string;
    /**
     * 
     * @type {number}
     * @memberof CreateChildRequest
     */
    birthYear?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateChildRequest
     */
    avatarAsset?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateChildRequest
     */
    roomTheme?: string;
}

/**
 * Check if a given object implements the CreateChildRequest interface.
 */
export function instanceOfCreateChildRequest(value: object): value is CreateChildRequest {
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    return true;
}

export function CreateChildRequestFromJSON(json: any): CreateChildRequest {
    return CreateChildRequestFromJSONTyped(json, false);
}

export function CreateChildRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChildRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'],
        'birthYear': json['birthYear'] == null ? undefined : json['birthYear'],
        'avatarAsset': json['avatarAsset'] == null ? undefined : json['avatarAsset'],
        'roomTheme': json['roomTheme'] == null ? undefined : json['roomTheme'],
    };
}

export function CreateChildRequestToJSON(json: any): CreateChildRequest {
    return CreateChildRequestToJSONTyped(json, false);
}

export function CreateChildRequestToJSONTyped(value?: CreateChildRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nickname': value['nickname'],
        'birthYear': value['birthYear'],
        'avatarAsset': value['avatarAsset'],
        'roomTheme': value['roomTheme'],
    };
}

