/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNotificationEventRequest
 */
export interface CreateNotificationEventRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateNotificationEventRequest
     */
    familyId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNotificationEventRequest
     */
    recipientUserId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNotificationEventRequest
     */
    recipientDeviceId?: string;
    /**
     * 
     * @type {CreateNotificationEventRequestTypeEnum}
     * @memberof CreateNotificationEventRequest
     */
    type: CreateNotificationEventRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateNotificationEventRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNotificationEventRequest
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNotificationEventRequest
     */
    relatedResourceType?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNotificationEventRequest
     */
    relatedResourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNotificationEventRequest
     */
    dedupeKey?: string;
}


/**
 * @export
 */
export const CreateNotificationEventRequestTypeEnum = {
    child_submission_created: 'child_submission_created',
    ai_precheck_completed: 'ai_precheck_completed',
    review_completed: 'review_completed',
    wish_fragment_earned: 'wish_fragment_earned',
    wish_unlocked: 'wish_unlocked',
    wish_redeemed_memory_generated: 'wish_redeemed_memory_generated',
    task_plan_changed: 'task_plan_changed'
} as const;
export type CreateNotificationEventRequestTypeEnum = typeof CreateNotificationEventRequestTypeEnum[keyof typeof CreateNotificationEventRequestTypeEnum];


/**
 * Check if a given object implements the CreateNotificationEventRequest interface.
 */
export function instanceOfCreateNotificationEventRequest(value: object): value is CreateNotificationEventRequest {
    if (!('familyId' in value) || value['familyId'] === undefined) return false;
    if (!('recipientUserId' in value) || value['recipientUserId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function CreateNotificationEventRequestFromJSON(json: any): CreateNotificationEventRequest {
    return CreateNotificationEventRequestFromJSONTyped(json, false);
}

export function CreateNotificationEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNotificationEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'familyId': json['familyId'],
        'recipientUserId': json['recipientUserId'],
        'recipientDeviceId': json['recipientDeviceId'] == null ? undefined : json['recipientDeviceId'],
        'type': json['type'],
        'title': json['title'],
        'body': json['body'],
        'relatedResourceType': json['relatedResourceType'] == null ? undefined : json['relatedResourceType'],
        'relatedResourceId': json['relatedResourceId'] == null ? undefined : json['relatedResourceId'],
        'dedupeKey': json['dedupeKey'] == null ? undefined : json['dedupeKey'],
    };
}

export function CreateNotificationEventRequestToJSON(json: any): CreateNotificationEventRequest {
    return CreateNotificationEventRequestToJSONTyped(json, false);
}

export function CreateNotificationEventRequestToJSONTyped(value?: CreateNotificationEventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'familyId': value['familyId'],
        'recipientUserId': value['recipientUserId'],
        'recipientDeviceId': value['recipientDeviceId'],
        'type': value['type'],
        'title': value['title'],
        'body': value['body'],
        'relatedResourceType': value['relatedResourceType'],
        'relatedResourceId': value['relatedResourceId'],
        'dedupeKey': value['dedupeKey'],
    };
}

