/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSubmissionRequest
 */
export interface CreateSubmissionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSubmissionRequest
     */
    taskInstanceId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSubmissionRequest
     */
    clientMutationId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateSubmissionRequest
     */
    mediaAssetIds: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof CreateSubmissionRequest
     */
    submittedAtClient?: Date;
}

/**
 * Check if a given object implements the CreateSubmissionRequest interface.
 */
export function instanceOfCreateSubmissionRequest(value: object): value is CreateSubmissionRequest {
    if (!('taskInstanceId' in value) || value['taskInstanceId'] === undefined) return false;
    if (!('clientMutationId' in value) || value['clientMutationId'] === undefined) return false;
    if (!('mediaAssetIds' in value) || value['mediaAssetIds'] === undefined) return false;
    return true;
}

export function CreateSubmissionRequestFromJSON(json: any): CreateSubmissionRequest {
    return CreateSubmissionRequestFromJSONTyped(json, false);
}

export function CreateSubmissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubmissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'taskInstanceId': json['taskInstanceId'],
        'clientMutationId': json['clientMutationId'],
        'mediaAssetIds': json['mediaAssetIds'],
        'submittedAtClient': json['submittedAtClient'] == null ? undefined : (new Date(json['submittedAtClient'])),
    };
}

export function CreateSubmissionRequestToJSON(json: any): CreateSubmissionRequest {
    return CreateSubmissionRequestToJSONTyped(json, false);
}

export function CreateSubmissionRequestToJSONTyped(value?: CreateSubmissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskInstanceId': value['taskInstanceId'],
        'clientMutationId': value['clientMutationId'],
        'mediaAssetIds': value['mediaAssetIds'],
        'submittedAtClient': value['submittedAtClient'] == null ? value['submittedAtClient'] : value['submittedAtClient'].toISOString(),
    };
}

