/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskCategory } from './TaskCategory';
import {
    TaskCategoryFromJSON,
    TaskCategoryFromJSONTyped,
    TaskCategoryToJSON,
    TaskCategoryToJSONTyped,
} from './TaskCategory';
import type { SubmissionType } from './SubmissionType';
import {
    SubmissionTypeFromJSON,
    SubmissionTypeFromJSONTyped,
    SubmissionTypeToJSON,
    SubmissionTypeToJSONTyped,
} from './SubmissionType';

/**
 * 
 * @export
 * @interface CreateTaskTemplateRequest
 */
export interface CreateTaskTemplateRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTaskTemplateRequest
     */
    familyId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskTemplateRequest
     */
    title: string;
    /**
     * 
     * @type {TaskCategory}
     * @memberof CreateTaskTemplateRequest
     */
    category: TaskCategory;
    /**
     * 
     * @type {SubmissionType}
     * @memberof CreateTaskTemplateRequest
     */
    submissionType: SubmissionType;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskTemplateRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskTemplateRequest
     */
    targetText?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTaskTemplateRequest
     */
    defaultDurationSec?: number;
}



/**
 * Check if a given object implements the CreateTaskTemplateRequest interface.
 */
export function instanceOfCreateTaskTemplateRequest(value: object): value is CreateTaskTemplateRequest {
    if (!('familyId' in value) || value['familyId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('submissionType' in value) || value['submissionType'] === undefined) return false;
    return true;
}

export function CreateTaskTemplateRequestFromJSON(json: any): CreateTaskTemplateRequest {
    return CreateTaskTemplateRequestFromJSONTyped(json, false);
}

export function CreateTaskTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaskTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'familyId': json['familyId'],
        'title': json['title'],
        'category': TaskCategoryFromJSON(json['category']),
        'submissionType': SubmissionTypeFromJSON(json['submissionType']),
        'description': json['description'] == null ? undefined : json['description'],
        'targetText': json['targetText'] == null ? undefined : json['targetText'],
        'defaultDurationSec': json['defaultDurationSec'] == null ? undefined : json['defaultDurationSec'],
    };
}

export function CreateTaskTemplateRequestToJSON(json: any): CreateTaskTemplateRequest {
    return CreateTaskTemplateRequestToJSONTyped(json, false);
}

export function CreateTaskTemplateRequestToJSONTyped(value?: CreateTaskTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'familyId': value['familyId'],
        'title': value['title'],
        'category': TaskCategoryToJSON(value['category']),
        'submissionType': SubmissionTypeToJSON(value['submissionType']),
        'description': value['description'],
        'targetText': value['targetText'],
        'defaultDurationSec': value['defaultDurationSec'],
    };
}

