/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePairingSessionRequest
 */
export interface CreatePairingSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreatePairingSessionRequest
     */
    childId: string;
}

/**
 * Check if a given object implements the CreatePairingSessionRequest interface.
 */
export function instanceOfCreatePairingSessionRequest(value: object): value is CreatePairingSessionRequest {
    if (!('childId' in value) || value['childId'] === undefined) return false;
    return true;
}

export function CreatePairingSessionRequestFromJSON(json: any): CreatePairingSessionRequest {
    return CreatePairingSessionRequestFromJSONTyped(json, false);
}

export function CreatePairingSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePairingSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'childId': json['childId'],
    };
}

export function CreatePairingSessionRequestToJSON(json: any): CreatePairingSessionRequest {
    return CreatePairingSessionRequestToJSONTyped(json, false);
}

export function CreatePairingSessionRequestToJSONTyped(value?: CreatePairingSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'childId': value['childId'],
    };
}

