/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DebugWishFragmentsRequest
 */
export interface DebugWishFragmentsRequest {
    /**
     * 
     * @type {number}
     * @memberof DebugWishFragmentsRequest
     */
    earnedFragments: number;
}

/**
 * Check if a given object implements the DebugWishFragmentsRequest interface.
 */
export function instanceOfDebugWishFragmentsRequest(value: object): value is DebugWishFragmentsRequest {
    if (!('earnedFragments' in value) || value['earnedFragments'] === undefined) return false;
    return true;
}

export function DebugWishFragmentsRequestFromJSON(json: any): DebugWishFragmentsRequest {
    return DebugWishFragmentsRequestFromJSONTyped(json, false);
}

export function DebugWishFragmentsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebugWishFragmentsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'earnedFragments': json['earnedFragments'],
    };
}

export function DebugWishFragmentsRequestToJSON(json: any): DebugWishFragmentsRequest {
    return DebugWishFragmentsRequestToJSONTyped(json, false);
}

export function DebugWishFragmentsRequestToJSONTyped(value?: DebugWishFragmentsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'earnedFragments': value['earnedFragments'],
    };
}

