/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FamilyInvite
 */
export interface FamilyInvite {
    /**
     * 
     * @type {string}
     * @memberof FamilyInvite
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FamilyInvite
     */
    familyId: string;
    /**
     * 
     * @type {FamilyInviteStatusEnum}
     * @memberof FamilyInvite
     */
    status: FamilyInviteStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof FamilyInvite
     */
    expiresAt: Date;
}


/**
 * @export
 */
export const FamilyInviteStatusEnum = {
    pending: 'pending',
    accepted: 'accepted',
    expired: 'expired',
    revoked: 'revoked'
} as const;
export type FamilyInviteStatusEnum = typeof FamilyInviteStatusEnum[keyof typeof FamilyInviteStatusEnum];


/**
 * Check if a given object implements the FamilyInvite interface.
 */
export function instanceOfFamilyInvite(value: object): value is FamilyInvite {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('familyId' in value) || value['familyId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function FamilyInviteFromJSON(json: any): FamilyInvite {
    return FamilyInviteFromJSONTyped(json, false);
}

export function FamilyInviteFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyInvite {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'familyId': json['familyId'],
        'status': json['status'],
        'expiresAt': (new Date(json['expiresAt'])),
    };
}

export function FamilyInviteToJSON(json: any): FamilyInvite {
    return FamilyInviteToJSONTyped(json, false);
}

export function FamilyInviteToJSONTyped(value?: FamilyInvite | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'familyId': value['familyId'],
        'status': value['status'],
        'expiresAt': value['expiresAt'].toISOString(),
    };
}

