/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackInput
 */
export interface FeedbackInput {
    /**
     * 
     * @type {string}
     * @memberof FeedbackInput
     */
    emoji?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackInput
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackInput
     */
    audioMediaId?: string;
}

/**
 * Check if a given object implements the FeedbackInput interface.
 */
export function instanceOfFeedbackInput(value: object): value is FeedbackInput {
    return true;
}

export function FeedbackInputFromJSON(json: any): FeedbackInput {
    return FeedbackInputFromJSONTyped(json, false);
}

export function FeedbackInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackInput {
    if (json == null) {
        return json;
    }
    return {
        
        'emoji': json['emoji'] == null ? undefined : json['emoji'],
        'text': json['text'] == null ? undefined : json['text'],
        'audioMediaId': json['audioMediaId'] == null ? undefined : json['audioMediaId'],
    };
}

export function FeedbackInputToJSON(json: any): FeedbackInput {
    return FeedbackInputToJSONTyped(json, false);
}

export function FeedbackInputToJSONTyped(value?: FeedbackInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'emoji': value['emoji'],
        'text': value['text'],
        'audioMediaId': value['audioMediaId'],
    };
}

