/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaAsset } from './MediaAsset';
import {
    MediaAssetFromJSON,
    MediaAssetFromJSONTyped,
    MediaAssetToJSON,
    MediaAssetToJSONTyped,
} from './MediaAsset';

/**
 * 
 * @export
 * @interface Feedback
 */
export interface Feedback {
    /**
     * 
     * @type {string}
     * @memberof Feedback
     */
    emoji?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Feedback
     */
    text?: string | null;
    /**
     * 
     * @type {MediaAsset}
     * @memberof Feedback
     */
    audioMedia?: MediaAsset | null;
}

/**
 * Check if a given object implements the Feedback interface.
 */
export function instanceOfFeedback(value: object): value is Feedback {
    return true;
}

export function FeedbackFromJSON(json: any): Feedback {
    return FeedbackFromJSONTyped(json, false);
}

export function FeedbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): Feedback {
    if (json == null) {
        return json;
    }
    return {
        
        'emoji': json['emoji'] === undefined ? undefined : json['emoji'] === null ? null : json['emoji'],
        'text': json['text'] === undefined ? undefined : json['text'] === null ? null : json['text'],
        'audioMedia': json['audioMedia'] === undefined ? undefined : json['audioMedia'] === null ? null : MediaAssetFromJSON(json['audioMedia']),
    };
}

export function FeedbackToJSON(json: any): Feedback {
    return FeedbackToJSONTyped(json, false);
}

export function FeedbackToJSONTyped(value?: Feedback | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'emoji': value['emoji'],
        'text': value['text'],
        'audioMedia': MediaAssetToJSON(value['audioMedia']),
    };
}

