/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateMemoryWorkflowRequest
 */
export interface GenerateMemoryWorkflowRequest {
    /**
     * 
     * @type {string}
     * @memberof GenerateMemoryWorkflowRequest
     */
    triggeredByEventId: string;
}

/**
 * Check if a given object implements the GenerateMemoryWorkflowRequest interface.
 */
export function instanceOfGenerateMemoryWorkflowRequest(value: object): value is GenerateMemoryWorkflowRequest {
    if (!('triggeredByEventId' in value) || value['triggeredByEventId'] === undefined) return false;
    return true;
}

export function GenerateMemoryWorkflowRequestFromJSON(json: any): GenerateMemoryWorkflowRequest {
    return GenerateMemoryWorkflowRequestFromJSONTyped(json, false);
}

export function GenerateMemoryWorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateMemoryWorkflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'triggeredByEventId': json['triggeredByEventId'],
    };
}

export function GenerateMemoryWorkflowRequestToJSON(json: any): GenerateMemoryWorkflowRequest {
    return GenerateMemoryWorkflowRequestToJSONTyped(json, false);
}

export function GenerateMemoryWorkflowRequestToJSONTyped(value?: GenerateMemoryWorkflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'triggeredByEventId': value['triggeredByEventId'],
    };
}

