/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageModelProviderWriteRequest
 */
export interface ImageModelProviderWriteRequest {
    /**
     * Required on create; immutable on update.
     * @type {string}
     * @memberof ImageModelProviderWriteRequest
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageModelProviderWriteRequest
     */
    displayName: string;
    /**
     * 
     * @type {ImageModelProviderWriteRequestProviderTypeEnum}
     * @memberof ImageModelProviderWriteRequest
     */
    providerType: ImageModelProviderWriteRequestProviderTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageModelProviderWriteRequest
     */
    baseUrl: string;
    /**
     * Leave blank on update to keep the existing key.
     * @type {string}
     * @memberof ImageModelProviderWriteRequest
     */
    apiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageModelProviderWriteRequest
     */
    modelName: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ImageModelProviderWriteRequest
     */
    extraParams?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof ImageModelProviderWriteRequest
     */
    isDefault?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ImageModelProviderWriteRequest
     */
    isEnabled?: boolean;
}


/**
 * @export
 */
export const ImageModelProviderWriteRequestProviderTypeEnum = {
    volcengine_ark: 'volcengine_ark',
    aliyun_bailian: 'aliyun_bailian',
    siliconflow: 'siliconflow',
    deterministic: 'deterministic',
    custom_openai_compatible: 'custom_openai_compatible'
} as const;
export type ImageModelProviderWriteRequestProviderTypeEnum = typeof ImageModelProviderWriteRequestProviderTypeEnum[keyof typeof ImageModelProviderWriteRequestProviderTypeEnum];


/**
 * Check if a given object implements the ImageModelProviderWriteRequest interface.
 */
export function instanceOfImageModelProviderWriteRequest(value: object): value is ImageModelProviderWriteRequest {
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('providerType' in value) || value['providerType'] === undefined) return false;
    if (!('baseUrl' in value) || value['baseUrl'] === undefined) return false;
    if (!('modelName' in value) || value['modelName'] === undefined) return false;
    return true;
}

export function ImageModelProviderWriteRequestFromJSON(json: any): ImageModelProviderWriteRequest {
    return ImageModelProviderWriteRequestFromJSONTyped(json, false);
}

export function ImageModelProviderWriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageModelProviderWriteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'displayName': json['displayName'],
        'providerType': json['providerType'],
        'baseUrl': json['baseUrl'],
        'apiKey': json['apiKey'] == null ? undefined : json['apiKey'],
        'modelName': json['modelName'],
        'extraParams': json['extraParams'] == null ? undefined : json['extraParams'],
        'isDefault': json['isDefault'] == null ? undefined : json['isDefault'],
        'isEnabled': json['isEnabled'] == null ? undefined : json['isEnabled'],
    };
}

export function ImageModelProviderWriteRequestToJSON(json: any): ImageModelProviderWriteRequest {
    return ImageModelProviderWriteRequestToJSONTyped(json, false);
}

export function ImageModelProviderWriteRequestToJSONTyped(value?: ImageModelProviderWriteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'displayName': value['displayName'],
        'providerType': value['providerType'],
        'baseUrl': value['baseUrl'],
        'apiKey': value['apiKey'],
        'modelName': value['modelName'],
        'extraParams': value['extraParams'],
        'isDefault': value['isDefault'],
        'isEnabled': value['isEnabled'],
    };
}

