/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageModelProviderToggleRequest
 */
export interface ImageModelProviderToggleRequest {
    /**
     * 
     * @type {boolean}
     * @memberof ImageModelProviderToggleRequest
     */
    isEnabled: boolean;
}

/**
 * Check if a given object implements the ImageModelProviderToggleRequest interface.
 */
export function instanceOfImageModelProviderToggleRequest(value: object): value is ImageModelProviderToggleRequest {
    if (!('isEnabled' in value) || value['isEnabled'] === undefined) return false;
    return true;
}

export function ImageModelProviderToggleRequestFromJSON(json: any): ImageModelProviderToggleRequest {
    return ImageModelProviderToggleRequestFromJSONTyped(json, false);
}

export function ImageModelProviderToggleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageModelProviderToggleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isEnabled': json['isEnabled'],
    };
}

export function ImageModelProviderToggleRequestToJSON(json: any): ImageModelProviderToggleRequest {
    return ImageModelProviderToggleRequestToJSONTyped(json, false);
}

export function ImageModelProviderToggleRequestToJSONTyped(value?: ImageModelProviderToggleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isEnabled': value['isEnabled'],
    };
}

