/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageGenUsage
 */
export interface ImageGenUsage {
    /**
     * 
     * @type {string}
     * @memberof ImageGenUsage
     */
    usageCode: string;
    /**
     * 
     * @type {string}
     * @memberof ImageGenUsage
     */
    providerCode: string;
    /**
     * 
     * @type {string}
     * @memberof ImageGenUsage
     */
    providerDisplayName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ImageGenUsage
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ImageGenUsage
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ImageGenUsage interface.
 */
export function instanceOfImageGenUsage(value: object): value is ImageGenUsage {
    if (!('usageCode' in value) || value['usageCode'] === undefined) return false;
    if (!('providerCode' in value) || value['providerCode'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ImageGenUsageFromJSON(json: any): ImageGenUsage {
    return ImageGenUsageFromJSONTyped(json, false);
}

export function ImageGenUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageGenUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'usageCode': json['usageCode'],
        'providerCode': json['providerCode'],
        'providerDisplayName': json['providerDisplayName'] === undefined ? undefined : json['providerDisplayName'] === null ? null : json['providerDisplayName'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ImageGenUsageToJSON(json: any): ImageGenUsage {
    return ImageGenUsageToJSONTyped(json, false);
}

export function ImageGenUsageToJSONTyped(value?: ImageGenUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usageCode': value['usageCode'],
        'providerCode': value['providerCode'],
        'providerDisplayName': value['providerDisplayName'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

