/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageModelProvider
 */
export interface ImageModelProvider {
    /**
     * 
     * @type {string}
     * @memberof ImageModelProvider
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ImageModelProvider
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ImageModelProvider
     */
    displayName: string;
    /**
     * 
     * @type {ImageModelProviderProviderTypeEnum}
     * @memberof ImageModelProvider
     */
    providerType: ImageModelProviderProviderTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageModelProvider
     */
    baseUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ImageModelProvider
     */
    apiKeyMasked?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageModelProvider
     */
    modelName: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ImageModelProvider
     */
    extraParams: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof ImageModelProvider
     */
    isDefault: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ImageModelProvider
     */
    isEnabled: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ImageModelProvider
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ImageModelProvider
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const ImageModelProviderProviderTypeEnum = {
    volcengine_ark: 'volcengine_ark',
    aliyun_bailian: 'aliyun_bailian',
    siliconflow: 'siliconflow',
    deterministic: 'deterministic',
    custom_openai_compatible: 'custom_openai_compatible'
} as const;
export type ImageModelProviderProviderTypeEnum = typeof ImageModelProviderProviderTypeEnum[keyof typeof ImageModelProviderProviderTypeEnum];


/**
 * Check if a given object implements the ImageModelProvider interface.
 */
export function instanceOfImageModelProvider(value: object): value is ImageModelProvider {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('providerType' in value) || value['providerType'] === undefined) return false;
    if (!('baseUrl' in value) || value['baseUrl'] === undefined) return false;
    if (!('modelName' in value) || value['modelName'] === undefined) return false;
    if (!('extraParams' in value) || value['extraParams'] === undefined) return false;
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    if (!('isEnabled' in value) || value['isEnabled'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ImageModelProviderFromJSON(json: any): ImageModelProvider {
    return ImageModelProviderFromJSONTyped(json, false);
}

export function ImageModelProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageModelProvider {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
        'displayName': json['displayName'],
        'providerType': json['providerType'],
        'baseUrl': json['baseUrl'],
        'apiKeyMasked': json['apiKeyMasked'] === undefined ? undefined : json['apiKeyMasked'] === null ? null : json['apiKeyMasked'],
        'modelName': json['modelName'],
        'extraParams': json['extraParams'],
        'isDefault': json['isDefault'],
        'isEnabled': json['isEnabled'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ImageModelProviderToJSON(json: any): ImageModelProvider {
    return ImageModelProviderToJSONTyped(json, false);
}

export function ImageModelProviderToJSONTyped(value?: ImageModelProvider | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'displayName': value['displayName'],
        'providerType': value['providerType'],
        'baseUrl': value['baseUrl'],
        'apiKeyMasked': value['apiKeyMasked'],
        'modelName': value['modelName'],
        'extraParams': value['extraParams'],
        'isDefault': value['isDefault'],
        'isEnabled': value['isEnabled'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

