/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteParentRequest
 */
export interface InviteParentRequest {
    /**
     * Phone number for the self-hosted version.
     * @type {string}
     * @memberof InviteParentRequest
     */
    contact: string;
}

/**
 * Check if a given object implements the InviteParentRequest interface.
 */
export function instanceOfInviteParentRequest(value: object): value is InviteParentRequest {
    if (!('contact' in value) || value['contact'] === undefined) return false;
    return true;
}

export function InviteParentRequestFromJSON(json: any): InviteParentRequest {
    return InviteParentRequestFromJSONTyped(json, false);
}

export function InviteParentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteParentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contact': json['contact'],
    };
}

export function InviteParentRequestToJSON(json: any): InviteParentRequest {
    return InviteParentRequestToJSONTyped(json, false);
}

export function InviteParentRequestToJSONTyped(value?: InviteParentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contact': value['contact'],
    };
}

