/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarkNotificationReadRequest
 */
export interface MarkNotificationReadRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof MarkNotificationReadRequest
     */
    notificationIds: Array<string>;
}

/**
 * Check if a given object implements the MarkNotificationReadRequest interface.
 */
export function instanceOfMarkNotificationReadRequest(value: object): value is MarkNotificationReadRequest {
    if (!('notificationIds' in value) || value['notificationIds'] === undefined) return false;
    return true;
}

export function MarkNotificationReadRequestFromJSON(json: any): MarkNotificationReadRequest {
    return MarkNotificationReadRequestFromJSONTyped(json, false);
}

export function MarkNotificationReadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkNotificationReadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'notificationIds': json['notificationIds'],
    };
}

export function MarkNotificationReadRequestToJSON(json: any): MarkNotificationReadRequest {
    return MarkNotificationReadRequestToJSONTyped(json, false);
}

export function MarkNotificationReadRequestToJSONTyped(value?: MarkNotificationReadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notificationIds': value['notificationIds'],
    };
}

