/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaterializeWeeklyPlanWorkflowRequest
 */
export interface MaterializeWeeklyPlanWorkflowRequest {
    /**
     * 
     * @type {string}
     * @memberof MaterializeWeeklyPlanWorkflowRequest
     */
    weeklyPlanId: string;
    /**
     * 
     * @type {string}
     * @memberof MaterializeWeeklyPlanWorkflowRequest
     */
    triggeredByEventId?: string;
}

/**
 * Check if a given object implements the MaterializeWeeklyPlanWorkflowRequest interface.
 */
export function instanceOfMaterializeWeeklyPlanWorkflowRequest(value: object): value is MaterializeWeeklyPlanWorkflowRequest {
    if (!('weeklyPlanId' in value) || value['weeklyPlanId'] === undefined) return false;
    return true;
}

export function MaterializeWeeklyPlanWorkflowRequestFromJSON(json: any): MaterializeWeeklyPlanWorkflowRequest {
    return MaterializeWeeklyPlanWorkflowRequestFromJSONTyped(json, false);
}

export function MaterializeWeeklyPlanWorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaterializeWeeklyPlanWorkflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'weeklyPlanId': json['weeklyPlanId'],
        'triggeredByEventId': json['triggeredByEventId'] == null ? undefined : json['triggeredByEventId'],
    };
}

export function MaterializeWeeklyPlanWorkflowRequestToJSON(json: any): MaterializeWeeklyPlanWorkflowRequest {
    return MaterializeWeeklyPlanWorkflowRequestToJSONTyped(json, false);
}

export function MaterializeWeeklyPlanWorkflowRequestToJSONTyped(value?: MaterializeWeeklyPlanWorkflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'weeklyPlanId': value['weeklyPlanId'],
        'triggeredByEventId': value['triggeredByEventId'],
    };
}

