/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemoryItem
 */
export interface MemoryItem {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof MemoryItem
     */
    id: string;
    /**
     * 
     * @type {MemoryItemItemTypeEnum}
     * @memberof MemoryItem
     */
    itemType: MemoryItemItemTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MemoryItem
     */
    sourceType: string;
    /**
     * 
     * @type {string}
     * @memberof MemoryItem
     */
    sourceId: string;
    /**
     * 
     * @type {string}
     * @memberof MemoryItem
     */
    mediaAssetId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MemoryItem
     */
    downloadUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MemoryItem
     */
    contentType?: string;
    /**
     * 
     * @type {string}
     * @memberof MemoryItem
     */
    thumbnailUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MemoryItem
     */
    durationSec?: number | null;
    /**
     * 
     * @type {string}
     * @memberof MemoryItem
     */
    taskTitle?: string;
    /**
     * 
     * @type {Date}
     * @memberof MemoryItem
     */
    submittedAt?: Date;
}


/**
 * @export
 */
export const MemoryItemItemTypeEnum = {
    approved_task: 'approved_task',
    photo: 'photo',
    audio: 'audio',
    video: 'video'
} as const;
export type MemoryItemItemTypeEnum = typeof MemoryItemItemTypeEnum[keyof typeof MemoryItemItemTypeEnum];


/**
 * Check if a given object implements the MemoryItem interface.
 */
export function instanceOfMemoryItem(value: object): value is MemoryItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('itemType' in value) || value['itemType'] === undefined) return false;
    if (!('sourceType' in value) || value['sourceType'] === undefined) return false;
    if (!('sourceId' in value) || value['sourceId'] === undefined) return false;
    return true;
}

export function MemoryItemFromJSON(json: any): MemoryItem {
    return MemoryItemFromJSONTyped(json, false);
}

export function MemoryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryItem {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'itemType': json['itemType'],
        'sourceType': json['sourceType'],
        'sourceId': json['sourceId'],
        'mediaAssetId': json['mediaAssetId'] === undefined ? undefined : json['mediaAssetId'] === null ? null : json['mediaAssetId'],
        'downloadUrl': json['downloadUrl'] === undefined ? undefined : json['downloadUrl'] === null ? null : json['downloadUrl'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
        'thumbnailUrl': json['thumbnailUrl'] === undefined ? undefined : json['thumbnailUrl'] === null ? null : json['thumbnailUrl'],
        'durationSec': json['durationSec'] === undefined ? undefined : json['durationSec'] === null ? null : json['durationSec'],
        'taskTitle': json['taskTitle'] == null ? undefined : json['taskTitle'],
        'submittedAt': json['submittedAt'] == null ? undefined : (new Date(json['submittedAt'])),
    };
}

export function MemoryItemToJSON(json: any): MemoryItem {
    return MemoryItemToJSONTyped(json, false);
}

export function MemoryItemToJSONTyped(value?: MemoryItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'itemType': value['itemType'],
        'sourceType': value['sourceType'],
        'sourceId': value['sourceId'],
        'mediaAssetId': value['mediaAssetId'],
        'downloadUrl': value['downloadUrl'],
        'contentType': value['contentType'],
        'thumbnailUrl': value['thumbnailUrl'],
        'durationSec': value['durationSec'],
        'taskTitle': value['taskTitle'],
        'submittedAt': value['submittedAt'] == null ? value['submittedAt'] : value['submittedAt'].toISOString(),
    };
}

