/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationDevice
 */
export interface NotificationDevice {
    /**
     * 
     * @type {string}
     * @memberof NotificationDevice
     */
    id: string;
    /**
     * 
     * @type {NotificationDevicePlatformEnum}
     * @memberof NotificationDevice
     */
    platform: NotificationDevicePlatformEnum;
    /**
     * 
     * @type {string}
     * @memberof NotificationDevice
     */
    deviceName?: string | null;
    /**
     * 
     * @type {NotificationDevicePushProviderEnum}
     * @memberof NotificationDevice
     */
    pushProvider?: NotificationDevicePushProviderEnum | null;
    /**
     * 
     * @type {string}
     * @memberof NotificationDevice
     */
    pushToken?: string | null;
}


/**
 * @export
 */
export const NotificationDevicePlatformEnum = {
    ios: 'ios',
    android: 'android',
    ipad_os: 'ipad_os',
    web: 'web',
    admin_web: 'admin_web'
} as const;
export type NotificationDevicePlatformEnum = typeof NotificationDevicePlatformEnum[keyof typeof NotificationDevicePlatformEnum];

/**
 * @export
 */
export const NotificationDevicePushProviderEnum = {
    apns: 'apns',
    fcm: 'fcm',
    huawei: 'huawei',
    xiaomi: 'xiaomi',
    oppo: 'oppo',
    vivo: 'vivo'
} as const;
export type NotificationDevicePushProviderEnum = typeof NotificationDevicePushProviderEnum[keyof typeof NotificationDevicePushProviderEnum];


/**
 * Check if a given object implements the NotificationDevice interface.
 */
export function instanceOfNotificationDevice(value: object): value is NotificationDevice {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    return true;
}

export function NotificationDeviceFromJSON(json: any): NotificationDevice {
    return NotificationDeviceFromJSONTyped(json, false);
}

export function NotificationDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDevice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'platform': json['platform'],
        'deviceName': json['deviceName'] === undefined ? undefined : json['deviceName'] === null ? null : json['deviceName'],
        'pushProvider': json['pushProvider'] === undefined ? undefined : json['pushProvider'] === null ? null : json['pushProvider'],
        'pushToken': json['pushToken'] === undefined ? undefined : json['pushToken'] === null ? null : json['pushToken'],
    };
}

export function NotificationDeviceToJSON(json: any): NotificationDevice {
    return NotificationDeviceToJSONTyped(json, false);
}

export function NotificationDeviceToJSONTyped(value?: NotificationDevice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'platform': value['platform'],
        'deviceName': value['deviceName'],
        'pushProvider': value['pushProvider'],
        'pushToken': value['pushToken'],
    };
}

