/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationEvent } from './NotificationEvent';
import {
    NotificationEventFromJSON,
    NotificationEventFromJSONTyped,
    NotificationEventToJSON,
    NotificationEventToJSONTyped,
} from './NotificationEvent';

/**
 * 
 * @export
 * @interface NotificationListResponse
 */
export interface NotificationListResponse {
    /**
     * 
     * @type {Array<NotificationEvent>}
     * @memberof NotificationListResponse
     */
    items: Array<NotificationEvent>;
    /**
     * 
     * @type {Date}
     * @memberof NotificationListResponse
     */
    nextCursor?: Date | null;
}

/**
 * Check if a given object implements the NotificationListResponse interface.
 */
export function instanceOfNotificationListResponse(value: object): value is NotificationListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function NotificationListResponseFromJSON(json: any): NotificationListResponse {
    return NotificationListResponseFromJSONTyped(json, false);
}

export function NotificationListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(NotificationEventFromJSON)),
        'nextCursor': json['nextCursor'] === undefined ? undefined : json['nextCursor'] === null ? null : (new Date(json['nextCursor'])),
    };
}

export function NotificationListResponseToJSON(json: any): NotificationListResponse {
    return NotificationListResponseToJSONTyped(json, false);
}

export function NotificationListResponseToJSONTyped(value?: NotificationListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(NotificationEventToJSON)),
        'nextCursor': value['nextCursor'] == null ? value['nextCursor'] : value['nextCursor'].toISOString(),
    };
}

