/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationDispatchResultRequest
 */
export interface NotificationDispatchResultRequest {
    /**
     * 
     * @type {NotificationDispatchResultRequestStatusEnum}
     * @memberof NotificationDispatchResultRequest
     */
    status: NotificationDispatchResultRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof NotificationDispatchResultRequest
     */
    providerMessageId?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationDispatchResultRequest
     */
    errorMessage?: string;
}


/**
 * @export
 */
export const NotificationDispatchResultRequestStatusEnum = {
    sent: 'sent',
    failed: 'failed',
    suppressed: 'suppressed'
} as const;
export type NotificationDispatchResultRequestStatusEnum = typeof NotificationDispatchResultRequestStatusEnum[keyof typeof NotificationDispatchResultRequestStatusEnum];


/**
 * Check if a given object implements the NotificationDispatchResultRequest interface.
 */
export function instanceOfNotificationDispatchResultRequest(value: object): value is NotificationDispatchResultRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function NotificationDispatchResultRequestFromJSON(json: any): NotificationDispatchResultRequest {
    return NotificationDispatchResultRequestFromJSONTyped(json, false);
}

export function NotificationDispatchResultRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDispatchResultRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'providerMessageId': json['providerMessageId'] == null ? undefined : json['providerMessageId'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
    };
}

export function NotificationDispatchResultRequestToJSON(json: any): NotificationDispatchResultRequest {
    return NotificationDispatchResultRequestToJSONTyped(json, false);
}

export function NotificationDispatchResultRequestToJSONTyped(value?: NotificationDispatchResultRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'providerMessageId': value['providerMessageId'],
        'errorMessage': value['errorMessage'],
    };
}

