/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OutboxEvent } from './OutboxEvent';
import {
    OutboxEventFromJSON,
    OutboxEventFromJSONTyped,
    OutboxEventToJSON,
    OutboxEventToJSONTyped,
} from './OutboxEvent';

/**
 * 
 * @export
 * @interface OutboxClaimResponse
 */
export interface OutboxClaimResponse {
    /**
     * 
     * @type {Array<OutboxEvent>}
     * @memberof OutboxClaimResponse
     */
    events: Array<OutboxEvent>;
}

/**
 * Check if a given object implements the OutboxClaimResponse interface.
 */
export function instanceOfOutboxClaimResponse(value: object): value is OutboxClaimResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function OutboxClaimResponseFromJSON(json: any): OutboxClaimResponse {
    return OutboxClaimResponseFromJSONTyped(json, false);
}

export function OutboxClaimResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutboxClaimResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(OutboxEventFromJSON)),
    };
}

export function OutboxClaimResponseToJSON(json: any): OutboxClaimResponse {
    return OutboxClaimResponseToJSONTyped(json, false);
}

export function OutboxClaimResponseToJSONTyped(value?: OutboxClaimResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': ((value['events'] as Array<any>).map(OutboxEventToJSON)),
    };
}

