/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OutboxEvent
 */
export interface OutboxEvent {
    /**
     * 
     * @type {string}
     * @memberof OutboxEvent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OutboxEvent
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof OutboxEvent
     */
    aggregateType: string;
    /**
     * 
     * @type {string}
     * @memberof OutboxEvent
     */
    aggregateId: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof OutboxEvent
     */
    payload: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof OutboxEvent
     */
    availableAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof OutboxEvent
     */
    leasedUntil?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof OutboxEvent
     */
    retryCount: number;
    /**
     * 
     * @type {Date}
     * @memberof OutboxEvent
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the OutboxEvent interface.
 */
export function instanceOfOutboxEvent(value: object): value is OutboxEvent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('aggregateType' in value) || value['aggregateType'] === undefined) return false;
    if (!('aggregateId' in value) || value['aggregateId'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('availableAt' in value) || value['availableAt'] === undefined) return false;
    if (!('retryCount' in value) || value['retryCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function OutboxEventFromJSON(json: any): OutboxEvent {
    return OutboxEventFromJSONTyped(json, false);
}

export function OutboxEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutboxEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'aggregateType': json['aggregateType'],
        'aggregateId': json['aggregateId'],
        'payload': json['payload'],
        'availableAt': (new Date(json['availableAt'])),
        'leasedUntil': json['leasedUntil'] === undefined ? undefined : json['leasedUntil'] === null ? null : (new Date(json['leasedUntil'])),
        'retryCount': json['retryCount'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function OutboxEventToJSON(json: any): OutboxEvent {
    return OutboxEventToJSONTyped(json, false);
}

export function OutboxEventToJSONTyped(value?: OutboxEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'aggregateType': value['aggregateType'],
        'aggregateId': value['aggregateId'],
        'payload': value['payload'],
        'availableAt': value['availableAt'].toISOString(),
        'leasedUntil': value['leasedUntil'] == null ? value['leasedUntil'] : value['leasedUntil'].toISOString(),
        'retryCount': value['retryCount'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

