/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhoneCodeRequest
 */
export interface PhoneCodeRequest {
    /**
     * 
     * @type {string}
     * @memberof PhoneCodeRequest
     */
    phoneNumber: string;
    /**
     * 
     * @type {PhoneCodeRequestPurposeEnum}
     * @memberof PhoneCodeRequest
     */
    purpose: PhoneCodeRequestPurposeEnum;
}


/**
 * @export
 */
export const PhoneCodeRequestPurposeEnum = {
    login: 'login'
} as const;
export type PhoneCodeRequestPurposeEnum = typeof PhoneCodeRequestPurposeEnum[keyof typeof PhoneCodeRequestPurposeEnum];


/**
 * Check if a given object implements the PhoneCodeRequest interface.
 */
export function instanceOfPhoneCodeRequest(value: object): value is PhoneCodeRequest {
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('purpose' in value) || value['purpose'] === undefined) return false;
    if (value['purpose'] !== 'login') return false;
    
    return true;
}

export function PhoneCodeRequestFromJSON(json: any): PhoneCodeRequest {
    return PhoneCodeRequestFromJSONTyped(json, false);
}

export function PhoneCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhoneCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneNumber': json['phoneNumber'],
        'purpose': json['purpose'],
    };
}

export function PhoneCodeRequestToJSON(json: any): PhoneCodeRequest {
    return PhoneCodeRequestToJSONTyped(json, false);
}

export function PhoneCodeRequestToJSONTyped(value?: PhoneCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phoneNumber': value['phoneNumber'],
        'purpose': value['purpose'],
    };
}

