/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostponeTaskRequest
 */
export interface PostponeTaskRequest {
    /**
     * 
     * @type {Date}
     * @memberof PostponeTaskRequest
     */
    newDate: Date;
    /**
     * 
     * @type {string}
     * @memberof PostponeTaskRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the PostponeTaskRequest interface.
 */
export function instanceOfPostponeTaskRequest(value: object): value is PostponeTaskRequest {
    if (!('newDate' in value) || value['newDate'] === undefined) return false;
    return true;
}

export function PostponeTaskRequestFromJSON(json: any): PostponeTaskRequest {
    return PostponeTaskRequestFromJSONTyped(json, false);
}

export function PostponeTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostponeTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newDate': (new Date(json['newDate'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function PostponeTaskRequestToJSON(json: any): PostponeTaskRequest {
    return PostponeTaskRequestToJSONTyped(json, false);
}

export function PostponeTaskRequestToJSONTyped(value?: PostponeTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newDate': value['newDate'].toISOString().substring(0,10),
        'reason': value['reason'],
    };
}

