/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivacyDeletionWorkflowRequest
 */
export interface PrivacyDeletionWorkflowRequest {
    /**
     * 
     * @type {string}
     * @memberof PrivacyDeletionWorkflowRequest
     */
    triggeredByEventId: string;
}

/**
 * Check if a given object implements the PrivacyDeletionWorkflowRequest interface.
 */
export function instanceOfPrivacyDeletionWorkflowRequest(value: object): value is PrivacyDeletionWorkflowRequest {
    if (!('triggeredByEventId' in value) || value['triggeredByEventId'] === undefined) return false;
    return true;
}

export function PrivacyDeletionWorkflowRequestFromJSON(json: any): PrivacyDeletionWorkflowRequest {
    return PrivacyDeletionWorkflowRequestFromJSONTyped(json, false);
}

export function PrivacyDeletionWorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivacyDeletionWorkflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'triggeredByEventId': json['triggeredByEventId'],
    };
}

export function PrivacyDeletionWorkflowRequestToJSON(json: any): PrivacyDeletionWorkflowRequest {
    return PrivacyDeletionWorkflowRequestToJSONTyped(json, false);
}

export function PrivacyDeletionWorkflowRequestToJSONTyped(value?: PrivacyDeletionWorkflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'triggeredByEventId': value['triggeredByEventId'],
    };
}

