/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetryOutboxEventRequest
 */
export interface RetryOutboxEventRequest {
    /**
     * 
     * @type {number}
     * @memberof RetryOutboxEventRequest
     */
    delaySeconds: number;
    /**
     * 
     * @type {string}
     * @memberof RetryOutboxEventRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the RetryOutboxEventRequest interface.
 */
export function instanceOfRetryOutboxEventRequest(value: object): value is RetryOutboxEventRequest {
    if (!('delaySeconds' in value) || value['delaySeconds'] === undefined) return false;
    return true;
}

export function RetryOutboxEventRequestFromJSON(json: any): RetryOutboxEventRequest {
    return RetryOutboxEventRequestFromJSONTyped(json, false);
}

export function RetryOutboxEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetryOutboxEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'delaySeconds': json['delaySeconds'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function RetryOutboxEventRequestToJSON(json: any): RetryOutboxEventRequest {
    return RetryOutboxEventRequestToJSONTyped(json, false);
}

export function RetryOutboxEventRequestToJSONTyped(value?: RetryOutboxEventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delaySeconds': value['delaySeconds'],
        'reason': value['reason'],
    };
}

