/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeedbackInput } from './FeedbackInput';
import {
    FeedbackInputFromJSON,
    FeedbackInputFromJSONTyped,
    FeedbackInputToJSON,
    FeedbackInputToJSONTyped,
} from './FeedbackInput';

/**
 * 
 * @export
 * @interface ReviewSubmissionRequest
 */
export interface ReviewSubmissionRequest {
    /**
     * 
     * @type {string}
     * @memberof ReviewSubmissionRequest
     */
    submissionId: string;
    /**
     * 
     * @type {ReviewSubmissionRequestDecisionEnum}
     * @memberof ReviewSubmissionRequest
     */
    decision: ReviewSubmissionRequestDecisionEnum;
    /**
     * 
     * @type {FeedbackInput}
     * @memberof ReviewSubmissionRequest
     */
    feedback?: FeedbackInput;
}


/**
 * @export
 */
export const ReviewSubmissionRequestDecisionEnum = {
    approved: 'approved',
    needs_revision: 'needs_revision'
} as const;
export type ReviewSubmissionRequestDecisionEnum = typeof ReviewSubmissionRequestDecisionEnum[keyof typeof ReviewSubmissionRequestDecisionEnum];


/**
 * Check if a given object implements the ReviewSubmissionRequest interface.
 */
export function instanceOfReviewSubmissionRequest(value: object): value is ReviewSubmissionRequest {
    if (!('submissionId' in value) || value['submissionId'] === undefined) return false;
    if (!('decision' in value) || value['decision'] === undefined) return false;
    return true;
}

export function ReviewSubmissionRequestFromJSON(json: any): ReviewSubmissionRequest {
    return ReviewSubmissionRequestFromJSONTyped(json, false);
}

export function ReviewSubmissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewSubmissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'submissionId': json['submissionId'],
        'decision': json['decision'],
        'feedback': json['feedback'] == null ? undefined : FeedbackInputFromJSON(json['feedback']),
    };
}

export function ReviewSubmissionRequestToJSON(json: any): ReviewSubmissionRequest {
    return ReviewSubmissionRequestToJSONTyped(json, false);
}

export function ReviewSubmissionRequestToJSONTyped(value?: ReviewSubmissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'submissionId': value['submissionId'],
        'decision': value['decision'],
        'feedback': FeedbackInputToJSON(value['feedback']),
    };
}

