/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Feedback } from './Feedback';
import {
    FeedbackFromJSON,
    FeedbackFromJSONTyped,
    FeedbackToJSON,
    FeedbackToJSONTyped,
} from './Feedback';

/**
 * 
 * @export
 * @interface Review
 */
export interface Review {
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    submissionId: string;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    taskInstanceId: string;
    /**
     * 
     * @type {ReviewDecisionEnum}
     * @memberof Review
     */
    decision: ReviewDecisionEnum;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    reviewedBy: string;
    /**
     * 
     * @type {Feedback}
     * @memberof Review
     */
    feedback?: Feedback | null;
    /**
     * 
     * @type {Date}
     * @memberof Review
     */
    createdAt: Date;
}


/**
 * @export
 */
export const ReviewDecisionEnum = {
    approved: 'approved',
    needs_revision: 'needs_revision'
} as const;
export type ReviewDecisionEnum = typeof ReviewDecisionEnum[keyof typeof ReviewDecisionEnum];


/**
 * Check if a given object implements the Review interface.
 */
export function instanceOfReview(value: object): value is Review {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('submissionId' in value) || value['submissionId'] === undefined) return false;
    if (!('taskInstanceId' in value) || value['taskInstanceId'] === undefined) return false;
    if (!('decision' in value) || value['decision'] === undefined) return false;
    if (!('reviewedBy' in value) || value['reviewedBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ReviewFromJSON(json: any): Review {
    return ReviewFromJSONTyped(json, false);
}

export function ReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Review {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'submissionId': json['submissionId'],
        'taskInstanceId': json['taskInstanceId'],
        'decision': json['decision'],
        'reviewedBy': json['reviewedBy'],
        'feedback': json['feedback'] === undefined ? undefined : json['feedback'] === null ? null : FeedbackFromJSON(json['feedback']),
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ReviewToJSON(json: any): Review {
    return ReviewToJSONTyped(json, false);
}

export function ReviewToJSONTyped(value?: Review | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'submissionId': value['submissionId'],
        'taskInstanceId': value['taskInstanceId'],
        'decision': value['decision'],
        'reviewedBy': value['reviewedBy'],
        'feedback': FeedbackToJSON(value['feedback']),
        'createdAt': value['createdAt'].toISOString(),
    };
}

