/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevokeDeviceRequest
 */
export interface RevokeDeviceRequest {
    /**
     * 
     * @type {string}
     * @memberof RevokeDeviceRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the RevokeDeviceRequest interface.
 */
export function instanceOfRevokeDeviceRequest(value: object): value is RevokeDeviceRequest {
    return true;
}

export function RevokeDeviceRequestFromJSON(json: any): RevokeDeviceRequest {
    return RevokeDeviceRequestFromJSONTyped(json, false);
}

export function RevokeDeviceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevokeDeviceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function RevokeDeviceRequestToJSON(json: any): RevokeDeviceRequest {
    return RevokeDeviceRequestToJSONTyped(json, false);
}

export function RevokeDeviceRequestToJSONTyped(value?: RevokeDeviceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

