/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevokeAdminMediaAccessGrantRequest
 */
export interface RevokeAdminMediaAccessGrantRequest {
    /**
     * 
     * @type {string}
     * @memberof RevokeAdminMediaAccessGrantRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the RevokeAdminMediaAccessGrantRequest interface.
 */
export function instanceOfRevokeAdminMediaAccessGrantRequest(value: object): value is RevokeAdminMediaAccessGrantRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function RevokeAdminMediaAccessGrantRequestFromJSON(json: any): RevokeAdminMediaAccessGrantRequest {
    return RevokeAdminMediaAccessGrantRequestFromJSONTyped(json, false);
}

export function RevokeAdminMediaAccessGrantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevokeAdminMediaAccessGrantRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
    };
}

export function RevokeAdminMediaAccessGrantRequestToJSON(json: any): RevokeAdminMediaAccessGrantRequest {
    return RevokeAdminMediaAccessGrantRequestToJSONTyped(json, false);
}

export function RevokeAdminMediaAccessGrantRequestToJSONTyped(value?: RevokeAdminMediaAccessGrantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

