/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevokeReviewRequest
 */
export interface RevokeReviewRequest {
    /**
     * 
     * @type {string}
     * @memberof RevokeReviewRequest
     */
    reason: string;
}

/**
 * Check if a given object implements the RevokeReviewRequest interface.
 */
export function instanceOfRevokeReviewRequest(value: object): value is RevokeReviewRequest {
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function RevokeReviewRequestFromJSON(json: any): RevokeReviewRequest {
    return RevokeReviewRequestFromJSONTyped(json, false);
}

export function RevokeReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevokeReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'],
    };
}

export function RevokeReviewRequestToJSON(json: any): RevokeReviewRequest {
    return RevokeReviewRequestToJSONTyped(json, false);
}

export function RevokeReviewRequestToJSONTyped(value?: RevokeReviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

