/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RewardSummary
 */
export interface RewardSummary {
    /**
     * 
     * @type {string}
     * @memberof RewardSummary
     */
    childId: string;
    /**
     * 
     * @type {string}
     * @memberof RewardSummary
     */
    weekId: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RewardSummary
     */
    fromDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RewardSummary
     */
    toDate: Date | null;
    /**
     * 
     * @type {number}
     * @memberof RewardSummary
     */
    starLight: number;
    /**
     * 
     * @type {number}
     * @memberof RewardSummary
     */
    wishFragment: number;
    /**
     * 
     * @type {number}
     * @memberof RewardSummary
     */
    adjustment: number;
    /**
     * 
     * @type {number}
     * @memberof RewardSummary
     */
    total: number;
}

/**
 * Check if a given object implements the RewardSummary interface.
 */
export function instanceOfRewardSummary(value: object): value is RewardSummary {
    if (!('childId' in value) || value['childId'] === undefined) return false;
    if (!('weekId' in value) || value['weekId'] === undefined) return false;
    if (!('fromDate' in value) || value['fromDate'] === undefined) return false;
    if (!('toDate' in value) || value['toDate'] === undefined) return false;
    if (!('starLight' in value) || value['starLight'] === undefined) return false;
    if (!('wishFragment' in value) || value['wishFragment'] === undefined) return false;
    if (!('adjustment' in value) || value['adjustment'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function RewardSummaryFromJSON(json: any): RewardSummary {
    return RewardSummaryFromJSONTyped(json, false);
}

export function RewardSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RewardSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'childId': json['childId'],
        'weekId': json['weekId'],
        'fromDate': (json['fromDate'] == null ? null : new Date(json['fromDate'])),
        'toDate': (json['toDate'] == null ? null : new Date(json['toDate'])),
        'starLight': json['starLight'],
        'wishFragment': json['wishFragment'],
        'adjustment': json['adjustment'],
        'total': json['total'],
    };
}

export function RewardSummaryToJSON(json: any): RewardSummary {
    return RewardSummaryToJSONTyped(json, false);
}

export function RewardSummaryToJSONTyped(value?: RewardSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'childId': value['childId'],
        'weekId': value['weekId'],
        'fromDate': value['fromDate'] == null ? value['fromDate'] : value['fromDate'].toISOString().substring(0,10),
        'toDate': value['toDate'] == null ? value['toDate'] : value['toDate'].toISOString().substring(0,10),
        'starLight': value['starLight'],
        'wishFragment': value['wishFragment'],
        'adjustment': value['adjustment'],
        'total': value['total'],
    };
}

