/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoomItem } from './RoomItem';
import {
    RoomItemFromJSON,
    RoomItemFromJSONTyped,
    RoomItemToJSON,
    RoomItemToJSONTyped,
} from './RoomItem';

/**
 * 
 * @export
 * @interface RoomState
 */
export interface RoomState {
    /**
     * 
     * @type {string}
     * @memberof RoomState
     */
    childId: string;
    /**
     * 
     * @type {string}
     * @memberof RoomState
     */
    theme?: string;
    /**
     * 
     * @type {Array<RoomItem>}
     * @memberof RoomState
     */
    items: Array<RoomItem>;
}

/**
 * Check if a given object implements the RoomState interface.
 */
export function instanceOfRoomState(value: object): value is RoomState {
    if (!('childId' in value) || value['childId'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function RoomStateFromJSON(json: any): RoomState {
    return RoomStateFromJSONTyped(json, false);
}

export function RoomStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomState {
    if (json == null) {
        return json;
    }
    return {
        
        'childId': json['childId'],
        'theme': json['theme'] == null ? undefined : json['theme'],
        'items': ((json['items'] as Array<any>).map(RoomItemFromJSON)),
    };
}

export function RoomStateToJSON(json: any): RoomState {
    return RoomStateToJSONTyped(json, false);
}

export function RoomStateToJSONTyped(value?: RoomState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'childId': value['childId'],
        'theme': value['theme'],
        'items': ((value['items'] as Array<any>).map(RoomItemToJSON)),
    };
}

