/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunAiPrecheckWorkflowRequest
 */
export interface RunAiPrecheckWorkflowRequest {
    /**
     * 
     * @type {string}
     * @memberof RunAiPrecheckWorkflowRequest
     */
    submissionId: string;
    /**
     * 
     * @type {string}
     * @memberof RunAiPrecheckWorkflowRequest
     */
    triggeredByEventId?: string;
}

/**
 * Check if a given object implements the RunAiPrecheckWorkflowRequest interface.
 */
export function instanceOfRunAiPrecheckWorkflowRequest(value: object): value is RunAiPrecheckWorkflowRequest {
    if (!('submissionId' in value) || value['submissionId'] === undefined) return false;
    return true;
}

export function RunAiPrecheckWorkflowRequestFromJSON(json: any): RunAiPrecheckWorkflowRequest {
    return RunAiPrecheckWorkflowRequestFromJSONTyped(json, false);
}

export function RunAiPrecheckWorkflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunAiPrecheckWorkflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'submissionId': json['submissionId'],
        'triggeredByEventId': json['triggeredByEventId'] == null ? undefined : json['triggeredByEventId'],
    };
}

export function RunAiPrecheckWorkflowRequestToJSON(json: any): RunAiPrecheckWorkflowRequest {
    return RunAiPrecheckWorkflowRequestToJSONTyped(json, false);
}

export function RunAiPrecheckWorkflowRequestToJSONTyped(value?: RunAiPrecheckWorkflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'submissionId': value['submissionId'],
        'triggeredByEventId': value['triggeredByEventId'],
    };
}

