/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WeeklyPlanRuleInput } from './WeeklyPlanRuleInput';
import {
    WeeklyPlanRuleInputFromJSON,
    WeeklyPlanRuleInputFromJSONTyped,
    WeeklyPlanRuleInputToJSON,
    WeeklyPlanRuleInputToJSONTyped,
} from './WeeklyPlanRuleInput';

/**
 * 
 * @export
 * @interface SaveWeeklyPlanRequest
 */
export interface SaveWeeklyPlanRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveWeeklyPlanRequest
     */
    familyId: string;
    /**
     * 
     * @type {string}
     * @memberof SaveWeeklyPlanRequest
     */
    childId: string;
    /**
     * 
     * @type {string}
     * @memberof SaveWeeklyPlanRequest
     */
    weekId: string;
    /**
     * 
     * @type {Date}
     * @memberof SaveWeeklyPlanRequest
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof SaveWeeklyPlanRequest
     */
    endDate: Date;
    /**
     * 
     * @type {SaveWeeklyPlanRequestRewardModeEnum}
     * @memberof SaveWeeklyPlanRequest
     */
    rewardMode: SaveWeeklyPlanRequestRewardModeEnum;
    /**
     * 
     * @type {string}
     * @memberof SaveWeeklyPlanRequest
     */
    wishId?: string | null;
    /**
     * 
     * @type {Array<WeeklyPlanRuleInput>}
     * @memberof SaveWeeklyPlanRequest
     */
    rules: Array<WeeklyPlanRuleInput>;
}


/**
 * @export
 */
export const SaveWeeklyPlanRequestRewardModeEnum = {
    flexible: 'flexible',
    strict: 'strict'
} as const;
export type SaveWeeklyPlanRequestRewardModeEnum = typeof SaveWeeklyPlanRequestRewardModeEnum[keyof typeof SaveWeeklyPlanRequestRewardModeEnum];


/**
 * Check if a given object implements the SaveWeeklyPlanRequest interface.
 */
export function instanceOfSaveWeeklyPlanRequest(value: object): value is SaveWeeklyPlanRequest {
    if (!('familyId' in value) || value['familyId'] === undefined) return false;
    if (!('childId' in value) || value['childId'] === undefined) return false;
    if (!('weekId' in value) || value['weekId'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('rewardMode' in value) || value['rewardMode'] === undefined) return false;
    if (!('rules' in value) || value['rules'] === undefined) return false;
    return true;
}

export function SaveWeeklyPlanRequestFromJSON(json: any): SaveWeeklyPlanRequest {
    return SaveWeeklyPlanRequestFromJSONTyped(json, false);
}

export function SaveWeeklyPlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveWeeklyPlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'familyId': json['familyId'],
        'childId': json['childId'],
        'weekId': json['weekId'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'rewardMode': json['rewardMode'],
        'wishId': json['wishId'] === undefined ? undefined : json['wishId'] === null ? null : json['wishId'],
        'rules': ((json['rules'] as Array<any>).map(WeeklyPlanRuleInputFromJSON)),
    };
}

export function SaveWeeklyPlanRequestToJSON(json: any): SaveWeeklyPlanRequest {
    return SaveWeeklyPlanRequestToJSONTyped(json, false);
}

export function SaveWeeklyPlanRequestToJSONTyped(value?: SaveWeeklyPlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'familyId': value['familyId'],
        'childId': value['childId'],
        'weekId': value['weekId'],
        'startDate': value['startDate'].toISOString().substring(0,10),
        'endDate': value['endDate'].toISOString().substring(0,10),
        'rewardMode': value['rewardMode'],
        'wishId': value['wishId'],
        'rules': ((value['rules'] as Array<any>).map(WeeklyPlanRuleInputToJSON)),
    };
}

