/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubmissionType } from './SubmissionType';
import {
    SubmissionTypeFromJSON,
    SubmissionTypeFromJSONTyped,
    SubmissionTypeToJSON,
    SubmissionTypeToJSONTyped,
} from './SubmissionType';

/**
 * 
 * @export
 * @interface Submission
 */
export interface Submission {
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    familyId: string;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    childId: string;
    /**
     * 
     * @type {string}
     * @memberof Submission
     */
    taskInstanceId: string;
    /**
     * 
     * @type {number}
     * @memberof Submission
     */
    attemptNo: number;
    /**
     * 
     * @type {SubmissionType}
     * @memberof Submission
     */
    submissionType: SubmissionType;
    /**
     * 
     * @type {SubmissionStatusEnum}
     * @memberof Submission
     */
    status: SubmissionStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Submission
     */
    submittedAt: Date;
}


/**
 * @export
 */
export const SubmissionStatusEnum = {
    created: 'created',
    media_uploaded: 'media_uploaded',
    ai_pending: 'ai_pending',
    ai_processing: 'ai_processing',
    review_pending: 'review_pending',
    approved: 'approved',
    rejected: 'rejected',
    superseded: 'superseded',
    cancelled: 'cancelled'
} as const;
export type SubmissionStatusEnum = typeof SubmissionStatusEnum[keyof typeof SubmissionStatusEnum];


/**
 * Check if a given object implements the Submission interface.
 */
export function instanceOfSubmission(value: object): value is Submission {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('familyId' in value) || value['familyId'] === undefined) return false;
    if (!('childId' in value) || value['childId'] === undefined) return false;
    if (!('taskInstanceId' in value) || value['taskInstanceId'] === undefined) return false;
    if (!('attemptNo' in value) || value['attemptNo'] === undefined) return false;
    if (!('submissionType' in value) || value['submissionType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('submittedAt' in value) || value['submittedAt'] === undefined) return false;
    return true;
}

export function SubmissionFromJSON(json: any): Submission {
    return SubmissionFromJSONTyped(json, false);
}

export function SubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Submission {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'familyId': json['familyId'],
        'childId': json['childId'],
        'taskInstanceId': json['taskInstanceId'],
        'attemptNo': json['attemptNo'],
        'submissionType': SubmissionTypeFromJSON(json['submissionType']),
        'status': json['status'],
        'submittedAt': (new Date(json['submittedAt'])),
    };
}

export function SubmissionToJSON(json: any): Submission {
    return SubmissionToJSONTyped(json, false);
}

export function SubmissionToJSONTyped(value?: Submission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'familyId': value['familyId'],
        'childId': value['childId'],
        'taskInstanceId': value['taskInstanceId'],
        'attemptNo': value['attemptNo'],
        'submissionType': SubmissionTypeToJSON(value['submissionType']),
        'status': value['status'],
        'submittedAt': value['submittedAt'].toISOString(),
    };
}

