/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FamilyEvent } from './FamilyEvent';
import {
    FamilyEventFromJSON,
    FamilyEventFromJSONTyped,
    FamilyEventToJSON,
    FamilyEventToJSONTyped,
} from './FamilyEvent';

/**
 * 
 * @export
 * @interface SyncPullResponse
 */
export interface SyncPullResponse {
    /**
     * 
     * @type {Array<FamilyEvent>}
     * @memberof SyncPullResponse
     */
    events: Array<FamilyEvent>;
    /**
     * 
     * @type {number}
     * @memberof SyncPullResponse
     */
    latestSeq: number;
}

/**
 * Check if a given object implements the SyncPullResponse interface.
 */
export function instanceOfSyncPullResponse(value: object): value is SyncPullResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('latestSeq' in value) || value['latestSeq'] === undefined) return false;
    return true;
}

export function SyncPullResponseFromJSON(json: any): SyncPullResponse {
    return SyncPullResponseFromJSONTyped(json, false);
}

export function SyncPullResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncPullResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(FamilyEventFromJSON)),
        'latestSeq': json['latestSeq'],
    };
}

export function SyncPullResponseToJSON(json: any): SyncPullResponse {
    return SyncPullResponseToJSONTyped(json, false);
}

export function SyncPullResponseToJSONTyped(value?: SyncPullResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': ((value['events'] as Array<any>).map(FamilyEventToJSON)),
        'latestSeq': value['latestSeq'],
    };
}

