/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateChildRequest
 */
export interface UpdateChildRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateChildRequest
     */
    nickname?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateChildRequest
     */
    birthYear?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateChildRequest
     */
    avatarAsset?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateChildRequest
     */
    roomTheme?: string;
}

/**
 * Check if a given object implements the UpdateChildRequest interface.
 */
export function instanceOfUpdateChildRequest(value: object): value is UpdateChildRequest {
    return true;
}

export function UpdateChildRequestFromJSON(json: any): UpdateChildRequest {
    return UpdateChildRequestFromJSONTyped(json, false);
}

export function UpdateChildRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateChildRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'birthYear': json['birthYear'] == null ? undefined : json['birthYear'],
        'avatarAsset': json['avatarAsset'] == null ? undefined : json['avatarAsset'],
        'roomTheme': json['roomTheme'] == null ? undefined : json['roomTheme'],
    };
}

export function UpdateChildRequestToJSON(json: any): UpdateChildRequest {
    return UpdateChildRequestToJSONTyped(json, false);
}

export function UpdateChildRequestToJSONTyped(value?: UpdateChildRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nickname': value['nickname'],
        'birthYear': value['birthYear'],
        'avatarAsset': value['avatarAsset'],
        'roomTheme': value['roomTheme'],
    };
}

