/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadSession
 */
export interface UploadSession {
    /**
     * 
     * @type {string}
     * @memberof UploadSession
     */
    mediaId: string;
    /**
     * 
     * @type {string}
     * @memberof UploadSession
     */
    uploadUrl: string;
    /**
     * 
     * @type {string}
     * @memberof UploadSession
     */
    storageKey: string;
    /**
     * 
     * @type {Date}
     * @memberof UploadSession
     */
    expiresAt: Date;
    /**
     * 
     * @type {number}
     * @memberof UploadSession
     */
    maxSizeBytes: number;
}

/**
 * Check if a given object implements the UploadSession interface.
 */
export function instanceOfUploadSession(value: object): value is UploadSession {
    if (!('mediaId' in value) || value['mediaId'] === undefined) return false;
    if (!('uploadUrl' in value) || value['uploadUrl'] === undefined) return false;
    if (!('storageKey' in value) || value['storageKey'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('maxSizeBytes' in value) || value['maxSizeBytes'] === undefined) return false;
    return true;
}

export function UploadSessionFromJSON(json: any): UploadSession {
    return UploadSessionFromJSONTyped(json, false);
}

export function UploadSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadSession {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaId': json['mediaId'],
        'uploadUrl': json['uploadUrl'],
        'storageKey': json['storageKey'],
        'expiresAt': (new Date(json['expiresAt'])),
        'maxSizeBytes': json['maxSizeBytes'],
    };
}

export function UploadSessionToJSON(json: any): UploadSession {
    return UploadSessionToJSONTyped(json, false);
}

export function UploadSessionToJSONTyped(value?: UploadSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mediaId': value['mediaId'],
        'uploadUrl': value['uploadUrl'],
        'storageKey': value['storageKey'],
        'expiresAt': value['expiresAt'].toISOString(),
        'maxSizeBytes': value['maxSizeBytes'],
    };
}

