/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemoryItem } from './MemoryItem';
import {
    MemoryItemFromJSON,
    MemoryItemFromJSONTyped,
    MemoryItemToJSON,
    MemoryItemToJSONTyped,
} from './MemoryItem';

/**
 * 
 * @export
 * @interface WeeklyMemory
 */
export interface WeeklyMemory {
    /**
     * 
     * @type {string}
     * @memberof WeeklyMemory
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WeeklyMemory
     */
    childId: string;
    /**
     * 
     * @type {string}
     * @memberof WeeklyMemory
     */
    weekId: string;
    /**
     * 
     * @type {string}
     * @memberof WeeklyMemory
     */
    title: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WeeklyMemory
     */
    summary?: { [key: string]: any; };
    /**
     * 
     * @type {Array<MemoryItem>}
     * @memberof WeeklyMemory
     */
    items?: Array<MemoryItem>;
    /**
     * 
     * @type {WeeklyMemoryStatusEnum}
     * @memberof WeeklyMemory
     */
    status: WeeklyMemoryStatusEnum;
}


/**
 * @export
 */
export const WeeklyMemoryStatusEnum = {
    generating: 'generating',
    generated: 'generated',
    exported: 'exported'
} as const;
export type WeeklyMemoryStatusEnum = typeof WeeklyMemoryStatusEnum[keyof typeof WeeklyMemoryStatusEnum];


/**
 * Check if a given object implements the WeeklyMemory interface.
 */
export function instanceOfWeeklyMemory(value: object): value is WeeklyMemory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('childId' in value) || value['childId'] === undefined) return false;
    if (!('weekId' in value) || value['weekId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function WeeklyMemoryFromJSON(json: any): WeeklyMemory {
    return WeeklyMemoryFromJSONTyped(json, false);
}

export function WeeklyMemoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeeklyMemory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'childId': json['childId'],
        'weekId': json['weekId'],
        'title': json['title'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(MemoryItemFromJSON)),
        'status': json['status'],
    };
}

export function WeeklyMemoryToJSON(json: any): WeeklyMemory {
    return WeeklyMemoryToJSONTyped(json, false);
}

export function WeeklyMemoryToJSONTyped(value?: WeeklyMemory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'childId': value['childId'],
        'weekId': value['weekId'],
        'title': value['title'],
        'summary': value['summary'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(MemoryItemToJSON)),
        'status': value['status'],
    };
}

