/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WeeklyPlanRule } from './WeeklyPlanRule';
import {
    WeeklyPlanRuleFromJSON,
    WeeklyPlanRuleFromJSONTyped,
    WeeklyPlanRuleToJSON,
    WeeklyPlanRuleToJSONTyped,
} from './WeeklyPlanRule';

/**
 * 
 * @export
 * @interface WeeklyPlan
 */
export interface WeeklyPlan {
    /**
     * 
     * @type {string}
     * @memberof WeeklyPlan
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WeeklyPlan
     */
    familyId: string;
    /**
     * 
     * @type {string}
     * @memberof WeeklyPlan
     */
    childId: string;
    /**
     * 
     * @type {string}
     * @memberof WeeklyPlan
     */
    weekId: string;
    /**
     * 
     * @type {Date}
     * @memberof WeeklyPlan
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof WeeklyPlan
     */
    endDate: Date;
    /**
     * 
     * @type {WeeklyPlanRewardModeEnum}
     * @memberof WeeklyPlan
     */
    rewardMode: WeeklyPlanRewardModeEnum;
    /**
     * 
     * @type {WeeklyPlanStatusEnum}
     * @memberof WeeklyPlan
     */
    status: WeeklyPlanStatusEnum;
    /**
     * 
     * @type {Array<WeeklyPlanRule>}
     * @memberof WeeklyPlan
     */
    rules: Array<WeeklyPlanRule>;
}


/**
 * @export
 */
export const WeeklyPlanRewardModeEnum = {
    flexible: 'flexible',
    strict: 'strict'
} as const;
export type WeeklyPlanRewardModeEnum = typeof WeeklyPlanRewardModeEnum[keyof typeof WeeklyPlanRewardModeEnum];

/**
 * @export
 */
export const WeeklyPlanStatusEnum = {
    draft: 'draft',
    active: 'active',
    archived: 'archived'
} as const;
export type WeeklyPlanStatusEnum = typeof WeeklyPlanStatusEnum[keyof typeof WeeklyPlanStatusEnum];


/**
 * Check if a given object implements the WeeklyPlan interface.
 */
export function instanceOfWeeklyPlan(value: object): value is WeeklyPlan {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('familyId' in value) || value['familyId'] === undefined) return false;
    if (!('childId' in value) || value['childId'] === undefined) return false;
    if (!('weekId' in value) || value['weekId'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('rewardMode' in value) || value['rewardMode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('rules' in value) || value['rules'] === undefined) return false;
    return true;
}

export function WeeklyPlanFromJSON(json: any): WeeklyPlan {
    return WeeklyPlanFromJSONTyped(json, false);
}

export function WeeklyPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeeklyPlan {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'familyId': json['familyId'],
        'childId': json['childId'],
        'weekId': json['weekId'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'rewardMode': json['rewardMode'],
        'status': json['status'],
        'rules': ((json['rules'] as Array<any>).map(WeeklyPlanRuleFromJSON)),
    };
}

export function WeeklyPlanToJSON(json: any): WeeklyPlan {
    return WeeklyPlanToJSONTyped(json, false);
}

export function WeeklyPlanToJSONTyped(value?: WeeklyPlan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'familyId': value['familyId'],
        'childId': value['childId'],
        'weekId': value['weekId'],
        'startDate': value['startDate'].toISOString().substring(0,10),
        'endDate': value['endDate'].toISOString().substring(0,10),
        'rewardMode': value['rewardMode'],
        'status': value['status'],
        'rules': ((value['rules'] as Array<any>).map(WeeklyPlanRuleToJSON)),
    };
}

