/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskCategory } from './TaskCategory';
import {
    TaskCategoryFromJSON,
    TaskCategoryFromJSONTyped,
    TaskCategoryToJSON,
    TaskCategoryToJSONTyped,
} from './TaskCategory';
import type { SubmissionType } from './SubmissionType';
import {
    SubmissionTypeFromJSON,
    SubmissionTypeFromJSONTyped,
    SubmissionTypeToJSON,
    SubmissionTypeToJSONTyped,
} from './SubmissionType';

/**
 * 
 * @export
 * @interface WeeklyPlanRuleInput
 */
export interface WeeklyPlanRuleInput {
    /**
     * 
     * @type {string}
     * @memberof WeeklyPlanRuleInput
     */
    taskTemplateId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WeeklyPlanRuleInput
     */
    title: string;
    /**
     * 
     * @type {TaskCategory}
     * @memberof WeeklyPlanRuleInput
     */
    category: TaskCategory;
    /**
     * 
     * @type {SubmissionType}
     * @memberof WeeklyPlanRuleInput
     */
    submissionType: SubmissionType;
    /**
     * 
     * @type {string}
     * @memberof WeeklyPlanRuleInput
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof WeeklyPlanRuleInput
     */
    targetText?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof WeeklyPlanRuleInput
     */
    weekdays: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof WeeklyPlanRuleInput
     */
    isCore: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WeeklyPlanRuleInput
     */
    requireReview: boolean;
    /**
     * 
     * @type {number}
     * @memberof WeeklyPlanRuleInput
     */
    sortOrder?: number;
}



/**
 * Check if a given object implements the WeeklyPlanRuleInput interface.
 */
export function instanceOfWeeklyPlanRuleInput(value: object): value is WeeklyPlanRuleInput {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('submissionType' in value) || value['submissionType'] === undefined) return false;
    if (!('weekdays' in value) || value['weekdays'] === undefined) return false;
    if (!('isCore' in value) || value['isCore'] === undefined) return false;
    if (!('requireReview' in value) || value['requireReview'] === undefined) return false;
    return true;
}

export function WeeklyPlanRuleInputFromJSON(json: any): WeeklyPlanRuleInput {
    return WeeklyPlanRuleInputFromJSONTyped(json, false);
}

export function WeeklyPlanRuleInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeeklyPlanRuleInput {
    if (json == null) {
        return json;
    }
    return {
        
        'taskTemplateId': json['taskTemplateId'] === undefined ? undefined : json['taskTemplateId'] === null ? null : json['taskTemplateId'],
        'title': json['title'],
        'category': TaskCategoryFromJSON(json['category']),
        'submissionType': SubmissionTypeFromJSON(json['submissionType']),
        'description': json['description'] == null ? undefined : json['description'],
        'targetText': json['targetText'] == null ? undefined : json['targetText'],
        'weekdays': json['weekdays'],
        'isCore': json['isCore'],
        'requireReview': json['requireReview'],
        'sortOrder': json['sortOrder'] == null ? undefined : json['sortOrder'],
    };
}

export function WeeklyPlanRuleInputToJSON(json: any): WeeklyPlanRuleInput {
    return WeeklyPlanRuleInputToJSONTyped(json, false);
}

export function WeeklyPlanRuleInputToJSONTyped(value?: WeeklyPlanRuleInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskTemplateId': value['taskTemplateId'],
        'title': value['title'],
        'category': TaskCategoryToJSON(value['category']),
        'submissionType': SubmissionTypeToJSON(value['submissionType']),
        'description': value['description'],
        'targetText': value['targetText'],
        'weekdays': value['weekdays'],
        'isCore': value['isCore'],
        'requireReview': value['requireReview'],
        'sortOrder': value['sortOrder'],
    };
}

