/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WishFragmentPoint } from './WishFragmentPoint';
import {
    WishFragmentPointFromJSON,
    WishFragmentPointFromJSONTyped,
    WishFragmentPointToJSON,
    WishFragmentPointToJSONTyped,
} from './WishFragmentPoint';

/**
 * 
 * @export
 * @interface WishFragmentCell
 */
export interface WishFragmentCell {
    /**
     * 
     * @type {number}
     * @memberof WishFragmentCell
     */
    index: number;
    /**
     * 
     * @type {number}
     * @memberof WishFragmentCell
     */
    row: number;
    /**
     * 
     * @type {number}
     * @memberof WishFragmentCell
     */
    col: number;
    /**
     * 
     * @type {Array<WishFragmentPoint>}
     * @memberof WishFragmentCell
     */
    polygon?: Array<WishFragmentPoint> | null;
}

/**
 * Check if a given object implements the WishFragmentCell interface.
 */
export function instanceOfWishFragmentCell(value: object): value is WishFragmentCell {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('row' in value) || value['row'] === undefined) return false;
    if (!('col' in value) || value['col'] === undefined) return false;
    return true;
}

export function WishFragmentCellFromJSON(json: any): WishFragmentCell {
    return WishFragmentCellFromJSONTyped(json, false);
}

export function WishFragmentCellFromJSONTyped(json: any, ignoreDiscriminator: boolean): WishFragmentCell {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'row': json['row'],
        'col': json['col'],
        'polygon': json['polygon'] === undefined ? undefined : json['polygon'] === null ? null : ((json['polygon'] as Array<any>).map(WishFragmentPointFromJSON)),
    };
}

export function WishFragmentCellToJSON(json: any): WishFragmentCell {
    return WishFragmentCellToJSONTyped(json, false);
}

export function WishFragmentCellToJSONTyped(value?: WishFragmentCell | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'row': value['row'],
        'col': value['col'],
        'polygon': value['polygon'] == null ? undefined : ((value['polygon'] as Array<any>).map(WishFragmentPointToJSON)),
    };
}

