/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WishRedemption } from './WishRedemption';
import {
    WishRedemptionFromJSON,
    WishRedemptionFromJSONTyped,
    WishRedemptionToJSON,
    WishRedemptionToJSONTyped,
} from './WishRedemption';
import type { Wish } from './Wish';
import {
    WishFromJSON,
    WishFromJSONTyped,
    WishToJSON,
    WishToJSONTyped,
} from './Wish';

/**
 * 
 * @export
 * @interface WishHistoryItem
 */
export interface WishHistoryItem {
    /**
     * 
     * @type {Wish}
     * @memberof WishHistoryItem
     */
    wish: Wish;
    /**
     * 
     * @type {WishRedemption}
     * @memberof WishHistoryItem
     */
    redemption?: WishRedemption | null;
    /**
     * 
     * @type {number}
     * @memberof WishHistoryItem
     */
    realizedCount: number;
}

/**
 * Check if a given object implements the WishHistoryItem interface.
 */
export function instanceOfWishHistoryItem(value: object): value is WishHistoryItem {
    if (!('wish' in value) || value['wish'] === undefined) return false;
    if (!('realizedCount' in value) || value['realizedCount'] === undefined) return false;
    return true;
}

export function WishHistoryItemFromJSON(json: any): WishHistoryItem {
    return WishHistoryItemFromJSONTyped(json, false);
}

export function WishHistoryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): WishHistoryItem {
    if (json == null) {
        return json;
    }
    return {
        
        'wish': WishFromJSON(json['wish']),
        'redemption': json['redemption'] === undefined ? undefined : json['redemption'] === null ? null : WishRedemptionFromJSON(json['redemption']),
        'realizedCount': json['realizedCount'],
    };
}

export function WishHistoryItemToJSON(json: any): WishHistoryItem {
    return WishHistoryItemToJSONTyped(json, false);
}

export function WishHistoryItemToJSONTyped(value?: WishHistoryItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wish': WishToJSON(value['wish']),
        'redemption': WishRedemptionToJSON(value['redemption']),
        'realizedCount': value['realizedCount'],
    };
}

