/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MediaAsset } from './MediaAsset';
import {
    MediaAssetFromJSON,
    MediaAssetFromJSONTyped,
    MediaAssetToJSON,
    MediaAssetToJSONTyped,
} from './MediaAsset';

/**
 * 
 * @export
 * @interface WishImageGenerationJob
 */
export interface WishImageGenerationJob {
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    familyId: string;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    childId: string;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    wishId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    usageCode: string;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    providerCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    note?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    category?: string | null;
    /**
     * 
     * @type {WishImageGenerationJobStyleEnum}
     * @memberof WishImageGenerationJob
     */
    style: WishImageGenerationJobStyleEnum;
    /**
     * 
     * @type {WishImageGenerationJobAspectRatioEnum}
     * @memberof WishImageGenerationJob
     */
    aspectRatio: WishImageGenerationJobAspectRatioEnum;
    /**
     * 
     * @type {WishImageGenerationJobStatusEnum}
     * @memberof WishImageGenerationJob
     */
    status: WishImageGenerationJobStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    mediaAssetId?: string | null;
    /**
     * 
     * @type {MediaAsset}
     * @memberof WishImageGenerationJob
     */
    media?: MediaAsset | null;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    modelProvider?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    modelName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof WishImageGenerationJob
     */
    attemptCount: number;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    errorCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WishImageGenerationJob
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof WishImageGenerationJob
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof WishImageGenerationJob
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const WishImageGenerationJobStyleEnum = {
    warm_illustration: 'warm_illustration',
    storybook: 'storybook',
    clean_product: 'clean_product'
} as const;
export type WishImageGenerationJobStyleEnum = typeof WishImageGenerationJobStyleEnum[keyof typeof WishImageGenerationJobStyleEnum];

/**
 * @export
 */
export const WishImageGenerationJobAspectRatioEnum = {
    _1_1: '1:1',
    _4_3: '4:3'
} as const;
export type WishImageGenerationJobAspectRatioEnum = typeof WishImageGenerationJobAspectRatioEnum[keyof typeof WishImageGenerationJobAspectRatioEnum];

/**
 * @export
 */
export const WishImageGenerationJobStatusEnum = {
    queued: 'queued',
    running: 'running',
    succeeded: 'succeeded',
    failed_retryable: 'failed_retryable',
    failed_final: 'failed_final',
    cancelled: 'cancelled'
} as const;
export type WishImageGenerationJobStatusEnum = typeof WishImageGenerationJobStatusEnum[keyof typeof WishImageGenerationJobStatusEnum];


/**
 * Check if a given object implements the WishImageGenerationJob interface.
 */
export function instanceOfWishImageGenerationJob(value: object): value is WishImageGenerationJob {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('familyId' in value) || value['familyId'] === undefined) return false;
    if (!('childId' in value) || value['childId'] === undefined) return false;
    if (!('usageCode' in value) || value['usageCode'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('style' in value) || value['style'] === undefined) return false;
    if (!('aspectRatio' in value) || value['aspectRatio'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('attemptCount' in value) || value['attemptCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function WishImageGenerationJobFromJSON(json: any): WishImageGenerationJob {
    return WishImageGenerationJobFromJSONTyped(json, false);
}

export function WishImageGenerationJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): WishImageGenerationJob {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'familyId': json['familyId'],
        'childId': json['childId'],
        'wishId': json['wishId'] === undefined ? undefined : json['wishId'] === null ? null : json['wishId'],
        'usageCode': json['usageCode'],
        'providerCode': json['providerCode'] === undefined ? undefined : json['providerCode'] === null ? null : json['providerCode'],
        'title': json['title'],
        'note': json['note'] === undefined ? undefined : json['note'] === null ? null : json['note'],
        'category': json['category'] === undefined ? undefined : json['category'] === null ? null : json['category'],
        'style': json['style'],
        'aspectRatio': json['aspectRatio'],
        'status': json['status'],
        'mediaAssetId': json['mediaAssetId'] === undefined ? undefined : json['mediaAssetId'] === null ? null : json['mediaAssetId'],
        'media': json['media'] === undefined ? undefined : json['media'] === null ? null : MediaAssetFromJSON(json['media']),
        'modelProvider': json['modelProvider'] === undefined ? undefined : json['modelProvider'] === null ? null : json['modelProvider'],
        'modelName': json['modelName'] === undefined ? undefined : json['modelName'] === null ? null : json['modelName'],
        'attemptCount': json['attemptCount'],
        'errorCode': json['errorCode'] === undefined ? undefined : json['errorCode'] === null ? null : json['errorCode'],
        'errorMessage': json['errorMessage'] === undefined ? undefined : json['errorMessage'] === null ? null : json['errorMessage'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function WishImageGenerationJobToJSON(json: any): WishImageGenerationJob {
    return WishImageGenerationJobToJSONTyped(json, false);
}

export function WishImageGenerationJobToJSONTyped(value?: WishImageGenerationJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'familyId': value['familyId'],
        'childId': value['childId'],
        'wishId': value['wishId'],
        'usageCode': value['usageCode'],
        'providerCode': value['providerCode'],
        'title': value['title'],
        'note': value['note'],
        'category': value['category'],
        'style': value['style'],
        'aspectRatio': value['aspectRatio'],
        'status': value['status'],
        'mediaAssetId': value['mediaAssetId'],
        'media': MediaAssetToJSON(value['media']),
        'modelProvider': value['modelProvider'],
        'modelName': value['modelName'],
        'attemptCount': value['attemptCount'],
        'errorCode': value['errorCode'],
        'errorMessage': value['errorMessage'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

