/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WishFragmentVisual } from './WishFragmentVisual';
import {
    WishFragmentVisualFromJSON,
    WishFragmentVisualFromJSONTyped,
    WishFragmentVisualToJSON,
    WishFragmentVisualToJSONTyped,
} from './WishFragmentVisual';
import type { MediaAsset } from './MediaAsset';
import {
    MediaAssetFromJSON,
    MediaAssetFromJSONTyped,
    MediaAssetToJSON,
    MediaAssetToJSONTyped,
} from './MediaAsset';

/**
 * 
 * @export
 * @interface Wish
 */
export interface Wish {
    /**
     * 
     * @type {string}
     * @memberof Wish
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Wish
     */
    familyId: string;
    /**
     * 
     * @type {string}
     * @memberof Wish
     */
    childId: string;
    /**
     * 
     * @type {string}
     * @memberof Wish
     */
    weekId: string;
    /**
     * 
     * @type {string}
     * @memberof Wish
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Wish
     */
    note?: string | null;
    /**
     * 
     * @type {MediaAsset}
     * @memberof Wish
     */
    imageMedia?: MediaAsset | null;
    /**
     * 
     * @type {number}
     * @memberof Wish
     */
    requiredFragments: number;
    /**
     * 
     * @type {number}
     * @memberof Wish
     */
    earnedFragments: number;
    /**
     * 
     * @type {WishRewardModeEnum}
     * @memberof Wish
     */
    rewardMode: WishRewardModeEnum;
    /**
     * 
     * @type {WishStatusEnum}
     * @memberof Wish
     */
    status: WishStatusEnum;
    /**
     * 
     * @type {WishFragmentVisual}
     * @memberof Wish
     */
    fragmentVisual: WishFragmentVisual;
}


/**
 * @export
 */
export const WishRewardModeEnum = {
    flexible: 'flexible',
    strict: 'strict'
} as const;
export type WishRewardModeEnum = typeof WishRewardModeEnum[keyof typeof WishRewardModeEnum];

/**
 * @export
 */
export const WishStatusEnum = {
    draft: 'draft',
    active: 'active',
    unlocked: 'unlocked',
    redeemed: 'redeemed',
    archived: 'archived',
    cancelled: 'cancelled',
    cancelled_by_parent: 'cancelled_by_parent'
} as const;
export type WishStatusEnum = typeof WishStatusEnum[keyof typeof WishStatusEnum];


/**
 * Check if a given object implements the Wish interface.
 */
export function instanceOfWish(value: object): value is Wish {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('familyId' in value) || value['familyId'] === undefined) return false;
    if (!('childId' in value) || value['childId'] === undefined) return false;
    if (!('weekId' in value) || value['weekId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('requiredFragments' in value) || value['requiredFragments'] === undefined) return false;
    if (!('earnedFragments' in value) || value['earnedFragments'] === undefined) return false;
    if (!('rewardMode' in value) || value['rewardMode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('fragmentVisual' in value) || value['fragmentVisual'] === undefined) return false;
    return true;
}

export function WishFromJSON(json: any): Wish {
    return WishFromJSONTyped(json, false);
}

export function WishFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wish {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'familyId': json['familyId'],
        'childId': json['childId'],
        'weekId': json['weekId'],
        'title': json['title'],
        'note': json['note'] === undefined ? undefined : json['note'] === null ? null : json['note'],
        'imageMedia': json['imageMedia'] === undefined ? undefined : json['imageMedia'] === null ? null : MediaAssetFromJSON(json['imageMedia']),
        'requiredFragments': json['requiredFragments'],
        'earnedFragments': json['earnedFragments'],
        'rewardMode': json['rewardMode'],
        'status': json['status'],
        'fragmentVisual': WishFragmentVisualFromJSON(json['fragmentVisual']),
    };
}

export function WishToJSON(json: any): Wish {
    return WishToJSONTyped(json, false);
}

export function WishToJSONTyped(value?: Wish | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'familyId': value['familyId'],
        'childId': value['childId'],
        'weekId': value['weekId'],
        'title': value['title'],
        'note': value['note'],
        'imageMedia': MediaAssetToJSON(value['imageMedia']),
        'requiredFragments': value['requiredFragments'],
        'earnedFragments': value['earnedFragments'],
        'rewardMode': value['rewardMode'],
        'status': value['status'],
        'fragmentVisual': WishFragmentVisualToJSON(value['fragmentVisual']),
    };
}

