/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WishImageCandidateQuery } from './WishImageCandidateQuery';
import {
    WishImageCandidateQueryFromJSON,
    WishImageCandidateQueryFromJSONTyped,
    WishImageCandidateQueryToJSON,
    WishImageCandidateQueryToJSONTyped,
} from './WishImageCandidateQuery';
import type { WishImageCandidate } from './WishImageCandidate';
import {
    WishImageCandidateFromJSON,
    WishImageCandidateFromJSONTyped,
    WishImageCandidateToJSON,
    WishImageCandidateToJSONTyped,
} from './WishImageCandidate';

/**
 * 
 * @export
 * @interface WishImageCandidateResponse
 */
export interface WishImageCandidateResponse {
    /**
     * 
     * @type {WishImageCandidateQuery}
     * @memberof WishImageCandidateResponse
     */
    query: WishImageCandidateQuery;
    /**
     * 
     * @type {Array<WishImageCandidate>}
     * @memberof WishImageCandidateResponse
     */
    items: Array<WishImageCandidate>;
    /**
     * 
     * @type {Array<WishImageCandidateResponseFallbackOptionsEnum>}
     * @memberof WishImageCandidateResponse
     */
    fallbackOptions: Array<WishImageCandidateResponseFallbackOptionsEnum>;
}


/**
 * @export
 */
export const WishImageCandidateResponseFallbackOptionsEnum = {
    upload: 'upload',
    skip: 'skip'
} as const;
export type WishImageCandidateResponseFallbackOptionsEnum = typeof WishImageCandidateResponseFallbackOptionsEnum[keyof typeof WishImageCandidateResponseFallbackOptionsEnum];


/**
 * Check if a given object implements the WishImageCandidateResponse interface.
 */
export function instanceOfWishImageCandidateResponse(value: object): value is WishImageCandidateResponse {
    if (!('query' in value) || value['query'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('fallbackOptions' in value) || value['fallbackOptions'] === undefined) return false;
    return true;
}

export function WishImageCandidateResponseFromJSON(json: any): WishImageCandidateResponse {
    return WishImageCandidateResponseFromJSONTyped(json, false);
}

export function WishImageCandidateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WishImageCandidateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'query': WishImageCandidateQueryFromJSON(json['query']),
        'items': ((json['items'] as Array<any>).map(WishImageCandidateFromJSON)),
        'fallbackOptions': json['fallbackOptions'],
    };
}

export function WishImageCandidateResponseToJSON(json: any): WishImageCandidateResponse {
    return WishImageCandidateResponseToJSONTyped(json, false);
}

export function WishImageCandidateResponseToJSONTyped(value?: WishImageCandidateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': WishImageCandidateQueryToJSON(value['query']),
        'items': ((value['items'] as Array<any>).map(WishImageCandidateToJSON)),
        'fallbackOptions': value['fallbackOptions'],
    };
}

