/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowAcceptedResponse
 */
export interface WorkflowAcceptedResponse {
    /**
     * 
     * @type {string}
     * @memberof WorkflowAcceptedResponse
     */
    workflow: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowAcceptedResponse
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowAcceptedResponse
     */
    acceptedAt: Date;
}

/**
 * Check if a given object implements the WorkflowAcceptedResponse interface.
 */
export function instanceOfWorkflowAcceptedResponse(value: object): value is WorkflowAcceptedResponse {
    if (!('workflow' in value) || value['workflow'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('acceptedAt' in value) || value['acceptedAt'] === undefined) return false;
    return true;
}

export function WorkflowAcceptedResponseFromJSON(json: any): WorkflowAcceptedResponse {
    return WorkflowAcceptedResponseFromJSONTyped(json, false);
}

export function WorkflowAcceptedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowAcceptedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workflow': json['workflow'],
        'status': json['status'],
        'acceptedAt': (new Date(json['acceptedAt'])),
    };
}

export function WorkflowAcceptedResponseToJSON(json: any): WorkflowAcceptedResponse {
    return WorkflowAcceptedResponseToJSONTyped(json, false);
}

export function WorkflowAcceptedResponseToJSONTyped(value?: WorkflowAcceptedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workflow': value['workflow'],
        'status': value['status'],
        'acceptedAt': value['acceptedAt'].toISOString(),
    };
}

