"use client";

import { useState } from "react";
import type { ChildProfile, FamilyContext } from "@/lib/profile-data";

export type FamilyMember = { id: string; familyId: string; userId: string; role: string; childId?: string | null; displayName: string; status: string };
export type FamilySettingsData = { family: FamilyContext["family"]; member: FamilyContext["member"]; members: FamilyMember[]; children: ChildProfile[]; membersError?: string };
const roleLabels: Record<string, string> = { parent_owner: "家长所有者", parent: "家长", child_device: "儿童设备" };
const statusLabels: Record<string, string> = { active: "正常", invited: "已邀请", suspended: "已暂停", removed: "已移除", pending: "待处理", accepted: "已接受", expired: "已过期", revoked: "已撤销" };
const themeLabels: Record<string, string> = { forest: "森林", ocean: "海洋", space: "太空", candy: "糖果", meadow: "草地" };

function formatDate(value?: string | null) { if (!value) return ""; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString("zh-CN", { dateStyle: "medium", timeStyle: "short" }); }
function errorText(body: unknown) { return typeof body === "object" && body !== null && "error" in body && typeof body.error === "string" ? body.error : "操作失败，请稍后重试。"; }

export function FamilySettingsClient({ data }: Readonly<{ data: FamilySettingsData }>) {
  const isOwner = data.member.role === "parent_owner";
  const [children, setChildren] = useState(data.children);
  const [editing, setEditing] = useState<string | null>(null);
  const [childForm, setChildForm] = useState<Record<string, { nickname: string; birthYear: string; roomTheme: string }>>({});
  const [pending, setPending] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [invitePhone, setInvitePhone] = useState("");
  const [inviteResult, setInviteResult] = useState<{ status: string; expiresAt?: string } | null>(null);
  const [pairChildId, setPairChildId] = useState(data.children[0]?.id ?? "");
  const [pairResult, setPairResult] = useState<{ pairingCode: string; expiresAt?: string; sessionId?: string } | null>(null);
  function beginEdit(child: ChildProfile) { setEditing(child.id); setChildForm((current) => ({ ...current, [child.id]: { nickname: child.nickname, birthYear: child.birthYear ? String(child.birthYear) : "", roomTheme: child.roomTheme } })); setError(""); }
  async function saveChild(child: ChildProfile) { const form = childForm[child.id]; if (!form) return; setPending(`child-${child.id}`); setError(""); try { const response = await fetch(`/api/family/${data.family.id}/children/${child.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ nickname: form.nickname.trim(), birthYear: form.birthYear ? Number(form.birthYear) : undefined, roomTheme: form.roomTheme }) }); const body = await response.json(); if (!response.ok) throw new Error(errorText(body)); setChildren((current) => current.map((item) => item.id === child.id ? body : item)); setEditing(null); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "儿童资料保存失败，请稍后重试。"); } finally { setPending(null); } }
  async function invite() { setPending("invite"); setError(""); setInviteResult(null); try { const response = await fetch(`/api/family/${data.family.id}/invites`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contact: invitePhone.trim() }) }); const body = await response.json(); if (!response.ok) throw new Error(errorText(body)); setInviteResult(body); setInvitePhone(""); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "邀请发送失败，请稍后重试。"); } finally { setPending(null); } }
  async function pair() { if (!pairChildId) return; setPending("pair"); setError(""); setPairResult(null); try { const response = await fetch(`/api/family/${data.family.id}/pairing-sessions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ childId: pairChildId }) }); const body = await response.json(); if (!response.ok) throw new Error(errorText(body)); setPairResult(body); } catch (submitError) { setError(submitError instanceof Error ? submitError.message : "配对码生成失败，请稍后重试。"); } finally { setPending(null); } }
  return <section className="dashboard-grid" aria-label="家庭设置">
    <article className="panel span-12"><h2>家庭成员</h2><p className="muted">家庭：{data.family.name}</p>{data.membersError ? <p className="form-error">{data.membersError}</p> : data.members.length === 0 ? <p className="muted">暂无家庭成员。</p> : <div className="family-list">{data.members.map((member) => <div className="family-list-row" key={member.id}><strong>{member.displayName}</strong><span>{roleLabels[member.role] ?? member.role}</span><span>{statusLabels[member.status] ?? member.status}</span></div>)}</div>}</article>
    <article className="panel span-12"><h2>儿童资料</h2>{children.length === 0 ? <p className="muted">暂无儿童资料。</p> : <div className="family-card-grid">{children.map((child) => { const form = childForm[child.id]; const isEditing = editing === child.id; return <div className="family-card" key={child.id}>{isEditing ? <><label>昵称<input value={form?.nickname ?? ""} onChange={(event) => setChildForm((current) => ({ ...current, [child.id]: { ...current[child.id], nickname: event.target.value } }))} /></label><label>出生年份<input type="number" min="1900" max="2200" value={form?.birthYear ?? ""} onChange={(event) => setChildForm((current) => ({ ...current, [child.id]: { ...current[child.id], birthYear: event.target.value } }))} /></label><label>房间主题<select value={form?.roomTheme ?? "forest"} onChange={(event) => setChildForm((current) => ({ ...current, [child.id]: { ...current[child.id], roomTheme: event.target.value } }))}><option value="forest">森林</option><option value="ocean">海洋</option><option value="space">太空</option><option value="candy">糖果</option><option value="meadow">草地</option></select></label><div className="family-actions"><button className="primary-button" type="button" disabled={pending !== null} onClick={() => void saveChild(child)}>{pending === `child-${child.id}` ? "保存中…" : "保存资料"}</button><button className="secondary-button" type="button" disabled={pending !== null} onClick={() => setEditing(null)}>取消</button></div></> : <><h3>{child.nickname}</h3><p className="muted">出生年份：{child.birthYear ?? "未填写"}</p><p className="muted">房间主题：{themeLabels[child.roomTheme] ?? child.roomTheme}</p>{isOwner ? <button className="secondary-button" type="button" onClick={() => beginEdit(child)}>编辑资料</button> : null}</>}</div>; })}</div>}{!isOwner ? <p className="muted">你不是家庭所有者，儿童资料仅可查看。</p> : null}</article>
    <article className="panel span-6"><h2>邀请家长</h2>{isOwner ? <><label className="family-field">手机号<input inputMode="tel" value={invitePhone} onChange={(event) => setInvitePhone(event.target.value)} placeholder="请输入手机号" /></label><button className="primary-button" type="button" disabled={pending !== null || invitePhone.trim().length === 0} onClick={() => void invite()}>{pending === "invite" ? "邀请中…" : "发送邀请"}</button>{inviteResult ? <p className="form-success" role="status">邀请{statusLabels[inviteResult.status] ?? inviteResult.status}，有效期至 {formatDate(inviteResult.expiresAt)}。</p> : null}</> : <p className="muted">仅家长所有者可以邀请成员。</p>}</article>
    <article className="panel span-6"><h2>设备配对</h2>{isOwner ? <><label className="family-field">选择儿童<select value={pairChildId} onChange={(event) => setPairChildId(event.target.value)}>{children.map((child) => <option key={child.id} value={child.id}>{child.nickname}</option>)}</select></label><button className="primary-button" type="button" disabled={pending !== null || !pairChildId} onClick={() => void pair()}>{pending === "pair" ? "生成中…" : "生成配对码"}</button>{pairResult ? <div className="pairing-result" role="status"><strong>{pairResult.pairingCode}</strong><p>请在儿童端输入该配对码完成绑定。</p><p className="muted">有效期至 {formatDate(pairResult.expiresAt)}</p></div> : null}</> : <p className="muted">仅家长所有者可以生成配对码。</p>}</article>
    {error ? <p className="form-error span-12" role="alert">{error}</p> : null}
  </section>;
}
