name: wishpool_mobile
description: WishPool family companion app for child and parent experiences.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  file_picker: ^11.0.3
  flutter:
    sdk: flutter
  mime: ^2.0.0
  shared_preferences: ^2.5.5
  wishpool_api:
    path: ../../packages/api-contracts/generated/dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
