/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AdminAuditLog,
    AdminAuditLogFromJSON,
    AdminAuditLogToJSON,
} from '../models/AdminAuditLog';
import {
    type AdminDashboard,
    AdminDashboardFromJSON,
    AdminDashboardToJSON,
} from '../models/AdminDashboard';
import {
    type AdminFamilySummary,
    AdminFamilySummaryFromJSON,
    AdminFamilySummaryToJSON,
} from '../models/AdminFamilySummary';
import {
    type AdminMediaAccessGrant,
    AdminMediaAccessGrantFromJSON,
    AdminMediaAccessGrantToJSON,
} from '../models/AdminMediaAccessGrant';
import {
    type AdminMediaAccessGrantPage,
    AdminMediaAccessGrantPageFromJSON,
    AdminMediaAccessGrantPageToJSON,
} from '../models/AdminMediaAccessGrantPage';
import {
    type AdminMediaAccessGrantRequest,
    AdminMediaAccessGrantRequestFromJSON,
    AdminMediaAccessGrantRequestToJSON,
} from '../models/AdminMediaAccessGrantRequest';
import {
    type AdminPrivacyRequest,
    AdminPrivacyRequestFromJSON,
    AdminPrivacyRequestToJSON,
} from '../models/AdminPrivacyRequest';
import {
    type AiTextModelProvider,
    AiTextModelProviderFromJSON,
    AiTextModelProviderToJSON,
} from '../models/AiTextModelProvider';
import {
    type AiTextModelProviderToggleRequest,
    AiTextModelProviderToggleRequestFromJSON,
    AiTextModelProviderToggleRequestToJSON,
} from '../models/AiTextModelProviderToggleRequest';
import {
    type AiTextModelProviderWriteRequest,
    AiTextModelProviderWriteRequestFromJSON,
    AiTextModelProviderWriteRequestToJSON,
} from '../models/AiTextModelProviderWriteRequest';
import {
    type AiTextProviderTestResponse,
    AiTextProviderTestResponseFromJSON,
    AiTextProviderTestResponseToJSON,
} from '../models/AiTextProviderTestResponse';
import {
    type ImageGenUsage,
    ImageGenUsageFromJSON,
    ImageGenUsageToJSON,
} from '../models/ImageGenUsage';
import {
    type ImageGenUsageWriteRequest,
    ImageGenUsageWriteRequestFromJSON,
    ImageGenUsageWriteRequestToJSON,
} from '../models/ImageGenUsageWriteRequest';
import {
    type ImageModelProvider,
    ImageModelProviderFromJSON,
    ImageModelProviderToJSON,
} from '../models/ImageModelProvider';
import {
    type ImageModelProviderToggleRequest,
    ImageModelProviderToggleRequestFromJSON,
    ImageModelProviderToggleRequestToJSON,
} from '../models/ImageModelProviderToggleRequest';
import {
    type ImageModelProviderWriteRequest,
    ImageModelProviderWriteRequestFromJSON,
    ImageModelProviderWriteRequestToJSON,
} from '../models/ImageModelProviderWriteRequest';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type RevokeAdminMediaAccessGrantRequest,
    RevokeAdminMediaAccessGrantRequestFromJSON,
    RevokeAdminMediaAccessGrantRequestToJSON,
} from '../models/RevokeAdminMediaAccessGrantRequest';

export interface CreateAdminAiTextModelProviderRequest {
    aiTextModelProviderWriteRequest: AiTextModelProviderWriteRequest;
}

export interface CreateAdminImageModelProviderRequest {
    imageModelProviderWriteRequest: ImageModelProviderWriteRequest;
}

export interface DeleteAdminAiTextModelProviderRequest {
    id: string;
}

export interface DeleteAdminImageModelProviderRequest {
    id: string;
}

export interface GrantAdminMediaAccessRequest {
    adminMediaAccessGrantRequest: AdminMediaAccessGrantRequest;
}

export interface ListAdminAuditLogsRequest {
    familyId?: string;
    action?: string;
    limit?: number;
}

export interface ListAdminFamiliesRequest {
    limit?: number;
    status?: ListAdminFamiliesStatusEnum;
}

export interface ListAdminMediaAccessGrantsRequest {
    familyId?: string;
    mediaAssetId?: string;
    active?: boolean;
    from?: Date;
    to?: Date;
    limit?: number;
    offset?: number;
}

export interface ListAdminPrivacyRequestsRequest {
    limit?: number;
    status?: string;
}

export interface RevokeAdminMediaAccessGrantOperationRequest {
    grantId: string;
    revokeAdminMediaAccessGrantRequest: RevokeAdminMediaAccessGrantRequest;
}

export interface SetDefaultAdminAiTextModelProviderRequest {
    id: string;
}

export interface SetDefaultAdminImageModelProviderRequest {
    id: string;
}

export interface TestAdminAiTextModelProviderRequest {
    id: string;
}

export interface ToggleAdminAiTextModelProviderRequest {
    id: string;
    aiTextModelProviderToggleRequest: AiTextModelProviderToggleRequest;
}

export interface ToggleAdminImageModelProviderRequest {
    id: string;
    imageModelProviderToggleRequest: ImageModelProviderToggleRequest;
}

export interface UpdateAdminAiTextModelProviderRequest {
    id: string;
    aiTextModelProviderWriteRequest: AiTextModelProviderWriteRequest;
}

export interface UpdateAdminImageModelProviderRequest {
    id: string;
    imageModelProviderWriteRequest: ImageModelProviderWriteRequest;
}

export interface UpsertAdminImageGenUsageRequest {
    usageCode: string;
    imageGenUsageWriteRequest: ImageGenUsageWriteRequest;
}

/**
 * AdminApi - interface
 * 
 * @export
 * @interface AdminApiInterface
 */
export interface AdminApiInterface {
    /**
     * Creates request options for createAdminAiTextModelProvider without sending the request
     * @param {AiTextModelProviderWriteRequest} aiTextModelProviderWriteRequest 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    createAdminAiTextModelProviderRequestOpts(requestParameters: CreateAdminAiTextModelProviderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {AiTextModelProviderWriteRequest} aiTextModelProviderWriteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    createAdminAiTextModelProviderRaw(requestParameters: CreateAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiTextModelProvider>>;

    /**
     */
    createAdminAiTextModelProvider(requestParameters: CreateAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiTextModelProvider>;

    /**
     * Creates request options for createAdminImageModelProvider without sending the request
     * @param {ImageModelProviderWriteRequest} imageModelProviderWriteRequest 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    createAdminImageModelProviderRequestOpts(requestParameters: CreateAdminImageModelProviderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create an image generation model provider.
     * @param {ImageModelProviderWriteRequest} imageModelProviderWriteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    createAdminImageModelProviderRaw(requestParameters: CreateAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageModelProvider>>;

    /**
     * Create an image generation model provider.
     */
    createAdminImageModelProvider(requestParameters: CreateAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageModelProvider>;

    /**
     * Creates request options for deleteAdminAiTextModelProvider without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    deleteAdminAiTextModelProviderRequestOpts(requestParameters: DeleteAdminAiTextModelProviderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    deleteAdminAiTextModelProviderRaw(requestParameters: DeleteAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    deleteAdminAiTextModelProvider(requestParameters: DeleteAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for deleteAdminImageModelProvider without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    deleteAdminImageModelProviderRequestOpts(requestParameters: DeleteAdminImageModelProviderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Delete an image generation model provider.
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    deleteAdminImageModelProviderRaw(requestParameters: DeleteAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete an image generation model provider.
     */
    deleteAdminImageModelProvider(requestParameters: DeleteAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getAdminDashboard without sending the request
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    getAdminDashboardRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get local administration dashboard counters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    getAdminDashboardRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminDashboard>>;

    /**
     * Get local administration dashboard counters.
     */
    getAdminDashboard(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminDashboard>;

    /**
     * Creates request options for grantAdminMediaAccess without sending the request
     * @param {AdminMediaAccessGrantRequest} adminMediaAccessGrantRequest 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    grantAdminMediaAccessRequestOpts(requestParameters: GrantAdminMediaAccessRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create an audited short-lived media access grant.
     * @param {AdminMediaAccessGrantRequest} adminMediaAccessGrantRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    grantAdminMediaAccessRaw(requestParameters: GrantAdminMediaAccessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMediaAccessGrant>>;

    /**
     * Create an audited short-lived media access grant.
     */
    grantAdminMediaAccess(requestParameters: GrantAdminMediaAccessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMediaAccessGrant>;

    /**
     * Creates request options for listAdminAiTextModelProviders without sending the request
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminAiTextModelProvidersRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminAiTextModelProvidersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AiTextModelProvider>>>;

    /**
     */
    listAdminAiTextModelProviders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AiTextModelProvider>>;

    /**
     * Creates request options for listAdminAuditLogs without sending the request
     * @param {string} [familyId] 
     * @param {string} [action] 
     * @param {number} [limit] 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminAuditLogsRequestOpts(requestParameters: ListAdminAuditLogsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List audit logs for administration.
     * @param {string} [familyId] 
     * @param {string} [action] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminAuditLogsRaw(requestParameters: ListAdminAuditLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdminAuditLog>>>;

    /**
     * List audit logs for administration.
     */
    listAdminAuditLogs(requestParameters: ListAdminAuditLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdminAuditLog>>;

    /**
     * Creates request options for listAdminFamilies without sending the request
     * @param {number} [limit] 
     * @param {'active' | 'locked' | 'deleting' | 'deleted'} [status] 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminFamiliesRequestOpts(requestParameters: ListAdminFamiliesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List family metadata for administration.
     * @param {number} [limit] 
     * @param {'active' | 'locked' | 'deleting' | 'deleted'} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminFamiliesRaw(requestParameters: ListAdminFamiliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdminFamilySummary>>>;

    /**
     * List family metadata for administration.
     */
    listAdminFamilies(requestParameters: ListAdminFamiliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdminFamilySummary>>;

    /**
     * Creates request options for listAdminImageGenUsages without sending the request
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminImageGenUsagesRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List business usage to image provider mappings.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminImageGenUsagesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ImageGenUsage>>>;

    /**
     * List business usage to image provider mappings.
     */
    listAdminImageGenUsages(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ImageGenUsage>>;

    /**
     * Creates request options for listAdminImageModelProviders without sending the request
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminImageModelProvidersRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List image generation model provider configurations with masked API keys.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminImageModelProvidersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ImageModelProvider>>>;

    /**
     * List image generation model provider configurations with masked API keys.
     */
    listAdminImageModelProviders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ImageModelProvider>>;

    /**
     * Creates request options for listAdminMediaAccessGrants without sending the request
     * @param {string} [familyId] 
     * @param {string} [mediaAssetId] 
     * @param {boolean} [active] 
     * @param {Date} [from] 
     * @param {Date} [to] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminMediaAccessGrantsRequestOpts(requestParameters: ListAdminMediaAccessGrantsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [familyId] 
     * @param {string} [mediaAssetId] 
     * @param {boolean} [active] 
     * @param {Date} [from] 
     * @param {Date} [to] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminMediaAccessGrantsRaw(requestParameters: ListAdminMediaAccessGrantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMediaAccessGrantPage>>;

    /**
     */
    listAdminMediaAccessGrants(requestParameters: ListAdminMediaAccessGrantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMediaAccessGrantPage>;

    /**
     * Creates request options for listAdminPrivacyRequests without sending the request
     * @param {number} [limit] 
     * @param {string} [status] 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminPrivacyRequestsRequestOpts(requestParameters: ListAdminPrivacyRequestsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List privacy requests for administration.
     * @param {number} [limit] 
     * @param {string} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    listAdminPrivacyRequestsRaw(requestParameters: ListAdminPrivacyRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdminPrivacyRequest>>>;

    /**
     * List privacy requests for administration.
     */
    listAdminPrivacyRequests(requestParameters: ListAdminPrivacyRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdminPrivacyRequest>>;

    /**
     * Creates request options for revokeAdminMediaAccessGrant without sending the request
     * @param {string} grantId 
     * @param {RevokeAdminMediaAccessGrantRequest} revokeAdminMediaAccessGrantRequest 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    revokeAdminMediaAccessGrantRequestOpts(requestParameters: RevokeAdminMediaAccessGrantOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} grantId 
     * @param {RevokeAdminMediaAccessGrantRequest} revokeAdminMediaAccessGrantRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    revokeAdminMediaAccessGrantRaw(requestParameters: RevokeAdminMediaAccessGrantOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMediaAccessGrant>>;

    /**
     */
    revokeAdminMediaAccessGrant(requestParameters: RevokeAdminMediaAccessGrantOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMediaAccessGrant>;

    /**
     * Creates request options for setDefaultAdminAiTextModelProvider without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    setDefaultAdminAiTextModelProviderRequestOpts(requestParameters: SetDefaultAdminAiTextModelProviderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    setDefaultAdminAiTextModelProviderRaw(requestParameters: SetDefaultAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiTextModelProvider>>;

    /**
     */
    setDefaultAdminAiTextModelProvider(requestParameters: SetDefaultAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiTextModelProvider>;

    /**
     * Creates request options for setDefaultAdminImageModelProvider without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    setDefaultAdminImageModelProviderRequestOpts(requestParameters: SetDefaultAdminImageModelProviderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Set the global default image generation model provider.
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    setDefaultAdminImageModelProviderRaw(requestParameters: SetDefaultAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageModelProvider>>;

    /**
     * Set the global default image generation model provider.
     */
    setDefaultAdminImageModelProvider(requestParameters: SetDefaultAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageModelProvider>;

    /**
     * Creates request options for testAdminAiTextModelProvider without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    testAdminAiTextModelProviderRequestOpts(requestParameters: TestAdminAiTextModelProviderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    testAdminAiTextModelProviderRaw(requestParameters: TestAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiTextProviderTestResponse>>;

    /**
     */
    testAdminAiTextModelProvider(requestParameters: TestAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiTextProviderTestResponse>;

    /**
     * Creates request options for toggleAdminAiTextModelProvider without sending the request
     * @param {string} id 
     * @param {AiTextModelProviderToggleRequest} aiTextModelProviderToggleRequest 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    toggleAdminAiTextModelProviderRequestOpts(requestParameters: ToggleAdminAiTextModelProviderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {AiTextModelProviderToggleRequest} aiTextModelProviderToggleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    toggleAdminAiTextModelProviderRaw(requestParameters: ToggleAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiTextModelProvider>>;

    /**
     */
    toggleAdminAiTextModelProvider(requestParameters: ToggleAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiTextModelProvider>;

    /**
     * Creates request options for toggleAdminImageModelProvider without sending the request
     * @param {string} id 
     * @param {ImageModelProviderToggleRequest} imageModelProviderToggleRequest 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    toggleAdminImageModelProviderRequestOpts(requestParameters: ToggleAdminImageModelProviderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Enable or disable an image generation model provider.
     * @param {string} id 
     * @param {ImageModelProviderToggleRequest} imageModelProviderToggleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    toggleAdminImageModelProviderRaw(requestParameters: ToggleAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageModelProvider>>;

    /**
     * Enable or disable an image generation model provider.
     */
    toggleAdminImageModelProvider(requestParameters: ToggleAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageModelProvider>;

    /**
     * Creates request options for updateAdminAiTextModelProvider without sending the request
     * @param {string} id 
     * @param {AiTextModelProviderWriteRequest} aiTextModelProviderWriteRequest 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    updateAdminAiTextModelProviderRequestOpts(requestParameters: UpdateAdminAiTextModelProviderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} id 
     * @param {AiTextModelProviderWriteRequest} aiTextModelProviderWriteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    updateAdminAiTextModelProviderRaw(requestParameters: UpdateAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiTextModelProvider>>;

    /**
     */
    updateAdminAiTextModelProvider(requestParameters: UpdateAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiTextModelProvider>;

    /**
     * Creates request options for updateAdminImageModelProvider without sending the request
     * @param {string} id 
     * @param {ImageModelProviderWriteRequest} imageModelProviderWriteRequest 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    updateAdminImageModelProviderRequestOpts(requestParameters: UpdateAdminImageModelProviderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Update an image generation model provider.
     * @param {string} id 
     * @param {ImageModelProviderWriteRequest} imageModelProviderWriteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    updateAdminImageModelProviderRaw(requestParameters: UpdateAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageModelProvider>>;

    /**
     * Update an image generation model provider.
     */
    updateAdminImageModelProvider(requestParameters: UpdateAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageModelProvider>;

    /**
     * Creates request options for upsertAdminImageGenUsage without sending the request
     * @param {string} usageCode 
     * @param {ImageGenUsageWriteRequest} imageGenUsageWriteRequest 
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    upsertAdminImageGenUsageRequestOpts(requestParameters: UpsertAdminImageGenUsageRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create or update a business usage to image provider mapping.
     * @param {string} usageCode 
     * @param {ImageGenUsageWriteRequest} imageGenUsageWriteRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    upsertAdminImageGenUsageRaw(requestParameters: UpsertAdminImageGenUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageGenUsage>>;

    /**
     * Create or update a business usage to image provider mapping.
     */
    upsertAdminImageGenUsage(requestParameters: UpsertAdminImageGenUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageGenUsage>;

}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI implements AdminApiInterface {

    /**
     * Creates request options for createAdminAiTextModelProvider without sending the request
     */
    async createAdminAiTextModelProviderRequestOpts(requestParameters: CreateAdminAiTextModelProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aiTextModelProviderWriteRequest'] == null) {
            throw new runtime.RequiredError(
                'aiTextModelProviderWriteRequest',
                'Required parameter "aiTextModelProviderWriteRequest" was null or undefined when calling createAdminAiTextModelProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/internal/admin/ai-text-model-providers`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AiTextModelProviderWriteRequestToJSON(requestParameters['aiTextModelProviderWriteRequest']),
        };
    }

    /**
     */
    async createAdminAiTextModelProviderRaw(requestParameters: CreateAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiTextModelProvider>> {
        const requestOptions = await this.createAdminAiTextModelProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiTextModelProviderFromJSON(jsonValue));
    }

    /**
     */
    async createAdminAiTextModelProvider(requestParameters: CreateAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiTextModelProvider> {
        const response = await this.createAdminAiTextModelProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createAdminImageModelProvider without sending the request
     */
    async createAdminImageModelProviderRequestOpts(requestParameters: CreateAdminImageModelProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['imageModelProviderWriteRequest'] == null) {
            throw new runtime.RequiredError(
                'imageModelProviderWriteRequest',
                'Required parameter "imageModelProviderWriteRequest" was null or undefined when calling createAdminImageModelProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/image-model-providers`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImageModelProviderWriteRequestToJSON(requestParameters['imageModelProviderWriteRequest']),
        };
    }

    /**
     * Create an image generation model provider.
     */
    async createAdminImageModelProviderRaw(requestParameters: CreateAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageModelProvider>> {
        const requestOptions = await this.createAdminImageModelProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageModelProviderFromJSON(jsonValue));
    }

    /**
     * Create an image generation model provider.
     */
    async createAdminImageModelProvider(requestParameters: CreateAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageModelProvider> {
        const response = await this.createAdminImageModelProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteAdminAiTextModelProvider without sending the request
     */
    async deleteAdminAiTextModelProviderRequestOpts(requestParameters: DeleteAdminAiTextModelProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAdminAiTextModelProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/internal/admin/ai-text-model-providers/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async deleteAdminAiTextModelProviderRaw(requestParameters: DeleteAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteAdminAiTextModelProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteAdminAiTextModelProvider(requestParameters: DeleteAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAdminAiTextModelProviderRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deleteAdminImageModelProvider without sending the request
     */
    async deleteAdminImageModelProviderRequestOpts(requestParameters: DeleteAdminImageModelProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAdminImageModelProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/image-model-providers/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete an image generation model provider.
     */
    async deleteAdminImageModelProviderRaw(requestParameters: DeleteAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteAdminImageModelProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete an image generation model provider.
     */
    async deleteAdminImageModelProvider(requestParameters: DeleteAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAdminImageModelProviderRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAdminDashboard without sending the request
     */
    async getAdminDashboardRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/dashboard`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get local administration dashboard counters.
     */
    async getAdminDashboardRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminDashboard>> {
        const requestOptions = await this.getAdminDashboardRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminDashboardFromJSON(jsonValue));
    }

    /**
     * Get local administration dashboard counters.
     */
    async getAdminDashboard(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminDashboard> {
        const response = await this.getAdminDashboardRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for grantAdminMediaAccess without sending the request
     */
    async grantAdminMediaAccessRequestOpts(requestParameters: GrantAdminMediaAccessRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['adminMediaAccessGrantRequest'] == null) {
            throw new runtime.RequiredError(
                'adminMediaAccessGrantRequest',
                'Required parameter "adminMediaAccessGrantRequest" was null or undefined when calling grantAdminMediaAccess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/media-access-grants`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdminMediaAccessGrantRequestToJSON(requestParameters['adminMediaAccessGrantRequest']),
        };
    }

    /**
     * Create an audited short-lived media access grant.
     */
    async grantAdminMediaAccessRaw(requestParameters: GrantAdminMediaAccessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMediaAccessGrant>> {
        const requestOptions = await this.grantAdminMediaAccessRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMediaAccessGrantFromJSON(jsonValue));
    }

    /**
     * Create an audited short-lived media access grant.
     */
    async grantAdminMediaAccess(requestParameters: GrantAdminMediaAccessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMediaAccessGrant> {
        const response = await this.grantAdminMediaAccessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAdminAiTextModelProviders without sending the request
     */
    async listAdminAiTextModelProvidersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/internal/admin/ai-text-model-providers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listAdminAiTextModelProvidersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AiTextModelProvider>>> {
        const requestOptions = await this.listAdminAiTextModelProvidersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AiTextModelProviderFromJSON));
    }

    /**
     */
    async listAdminAiTextModelProviders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AiTextModelProvider>> {
        const response = await this.listAdminAiTextModelProvidersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAdminAuditLogs without sending the request
     */
    async listAdminAuditLogsRequestOpts(requestParameters: ListAdminAuditLogsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['familyId'] != null) {
            queryParameters['familyId'] = requestParameters['familyId'];
        }

        if (requestParameters['action'] != null) {
            queryParameters['action'] = requestParameters['action'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/audit-logs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List audit logs for administration.
     */
    async listAdminAuditLogsRaw(requestParameters: ListAdminAuditLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdminAuditLog>>> {
        const requestOptions = await this.listAdminAuditLogsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AdminAuditLogFromJSON));
    }

    /**
     * List audit logs for administration.
     */
    async listAdminAuditLogs(requestParameters: ListAdminAuditLogsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdminAuditLog>> {
        const response = await this.listAdminAuditLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAdminFamilies without sending the request
     */
    async listAdminFamiliesRequestOpts(requestParameters: ListAdminFamiliesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/families`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List family metadata for administration.
     */
    async listAdminFamiliesRaw(requestParameters: ListAdminFamiliesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdminFamilySummary>>> {
        const requestOptions = await this.listAdminFamiliesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AdminFamilySummaryFromJSON));
    }

    /**
     * List family metadata for administration.
     */
    async listAdminFamilies(requestParameters: ListAdminFamiliesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdminFamilySummary>> {
        const response = await this.listAdminFamiliesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAdminImageGenUsages without sending the request
     */
    async listAdminImageGenUsagesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/image-gen-usages`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List business usage to image provider mappings.
     */
    async listAdminImageGenUsagesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ImageGenUsage>>> {
        const requestOptions = await this.listAdminImageGenUsagesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ImageGenUsageFromJSON));
    }

    /**
     * List business usage to image provider mappings.
     */
    async listAdminImageGenUsages(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ImageGenUsage>> {
        const response = await this.listAdminImageGenUsagesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAdminImageModelProviders without sending the request
     */
    async listAdminImageModelProvidersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/image-model-providers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List image generation model provider configurations with masked API keys.
     */
    async listAdminImageModelProvidersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ImageModelProvider>>> {
        const requestOptions = await this.listAdminImageModelProvidersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ImageModelProviderFromJSON));
    }

    /**
     * List image generation model provider configurations with masked API keys.
     */
    async listAdminImageModelProviders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ImageModelProvider>> {
        const response = await this.listAdminImageModelProvidersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAdminMediaAccessGrants without sending the request
     */
    async listAdminMediaAccessGrantsRequestOpts(requestParameters: ListAdminMediaAccessGrantsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['familyId'] != null) {
            queryParameters['familyId'] = requestParameters['familyId'];
        }

        if (requestParameters['mediaAssetId'] != null) {
            queryParameters['mediaAssetId'] = requestParameters['mediaAssetId'];
        }

        if (requestParameters['active'] != null) {
            queryParameters['active'] = requestParameters['active'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/media-access-grants`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listAdminMediaAccessGrantsRaw(requestParameters: ListAdminMediaAccessGrantsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMediaAccessGrantPage>> {
        const requestOptions = await this.listAdminMediaAccessGrantsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMediaAccessGrantPageFromJSON(jsonValue));
    }

    /**
     */
    async listAdminMediaAccessGrants(requestParameters: ListAdminMediaAccessGrantsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMediaAccessGrantPage> {
        const response = await this.listAdminMediaAccessGrantsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAdminPrivacyRequests without sending the request
     */
    async listAdminPrivacyRequestsRequestOpts(requestParameters: ListAdminPrivacyRequestsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/privacy-requests`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List privacy requests for administration.
     */
    async listAdminPrivacyRequestsRaw(requestParameters: ListAdminPrivacyRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdminPrivacyRequest>>> {
        const requestOptions = await this.listAdminPrivacyRequestsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AdminPrivacyRequestFromJSON));
    }

    /**
     * List privacy requests for administration.
     */
    async listAdminPrivacyRequests(requestParameters: ListAdminPrivacyRequestsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdminPrivacyRequest>> {
        const response = await this.listAdminPrivacyRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeAdminMediaAccessGrant without sending the request
     */
    async revokeAdminMediaAccessGrantRequestOpts(requestParameters: RevokeAdminMediaAccessGrantOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['grantId'] == null) {
            throw new runtime.RequiredError(
                'grantId',
                'Required parameter "grantId" was null or undefined when calling revokeAdminMediaAccessGrant().'
            );
        }

        if (requestParameters['revokeAdminMediaAccessGrantRequest'] == null) {
            throw new runtime.RequiredError(
                'revokeAdminMediaAccessGrantRequest',
                'Required parameter "revokeAdminMediaAccessGrantRequest" was null or undefined when calling revokeAdminMediaAccessGrant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/media-access-grants/{grantId}/revoke`;
        urlPath = urlPath.replace('{grantId}', encodeURIComponent(String(requestParameters['grantId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RevokeAdminMediaAccessGrantRequestToJSON(requestParameters['revokeAdminMediaAccessGrantRequest']),
        };
    }

    /**
     */
    async revokeAdminMediaAccessGrantRaw(requestParameters: RevokeAdminMediaAccessGrantOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminMediaAccessGrant>> {
        const requestOptions = await this.revokeAdminMediaAccessGrantRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminMediaAccessGrantFromJSON(jsonValue));
    }

    /**
     */
    async revokeAdminMediaAccessGrant(requestParameters: RevokeAdminMediaAccessGrantOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminMediaAccessGrant> {
        const response = await this.revokeAdminMediaAccessGrantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setDefaultAdminAiTextModelProvider without sending the request
     */
    async setDefaultAdminAiTextModelProviderRequestOpts(requestParameters: SetDefaultAdminAiTextModelProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setDefaultAdminAiTextModelProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/internal/admin/ai-text-model-providers/{id}/set-default`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async setDefaultAdminAiTextModelProviderRaw(requestParameters: SetDefaultAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiTextModelProvider>> {
        const requestOptions = await this.setDefaultAdminAiTextModelProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiTextModelProviderFromJSON(jsonValue));
    }

    /**
     */
    async setDefaultAdminAiTextModelProvider(requestParameters: SetDefaultAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiTextModelProvider> {
        const response = await this.setDefaultAdminAiTextModelProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setDefaultAdminImageModelProvider without sending the request
     */
    async setDefaultAdminImageModelProviderRequestOpts(requestParameters: SetDefaultAdminImageModelProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setDefaultAdminImageModelProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/image-model-providers/{id}/set-default`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Set the global default image generation model provider.
     */
    async setDefaultAdminImageModelProviderRaw(requestParameters: SetDefaultAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageModelProvider>> {
        const requestOptions = await this.setDefaultAdminImageModelProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageModelProviderFromJSON(jsonValue));
    }

    /**
     * Set the global default image generation model provider.
     */
    async setDefaultAdminImageModelProvider(requestParameters: SetDefaultAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageModelProvider> {
        const response = await this.setDefaultAdminImageModelProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for testAdminAiTextModelProvider without sending the request
     */
    async testAdminAiTextModelProviderRequestOpts(requestParameters: TestAdminAiTextModelProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling testAdminAiTextModelProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/internal/admin/ai-text-model-providers/{id}/test-connection`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async testAdminAiTextModelProviderRaw(requestParameters: TestAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiTextProviderTestResponse>> {
        const requestOptions = await this.testAdminAiTextModelProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiTextProviderTestResponseFromJSON(jsonValue));
    }

    /**
     */
    async testAdminAiTextModelProvider(requestParameters: TestAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiTextProviderTestResponse> {
        const response = await this.testAdminAiTextModelProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for toggleAdminAiTextModelProvider without sending the request
     */
    async toggleAdminAiTextModelProviderRequestOpts(requestParameters: ToggleAdminAiTextModelProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling toggleAdminAiTextModelProvider().'
            );
        }

        if (requestParameters['aiTextModelProviderToggleRequest'] == null) {
            throw new runtime.RequiredError(
                'aiTextModelProviderToggleRequest',
                'Required parameter "aiTextModelProviderToggleRequest" was null or undefined when calling toggleAdminAiTextModelProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/internal/admin/ai-text-model-providers/{id}/toggle`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AiTextModelProviderToggleRequestToJSON(requestParameters['aiTextModelProviderToggleRequest']),
        };
    }

    /**
     */
    async toggleAdminAiTextModelProviderRaw(requestParameters: ToggleAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiTextModelProvider>> {
        const requestOptions = await this.toggleAdminAiTextModelProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiTextModelProviderFromJSON(jsonValue));
    }

    /**
     */
    async toggleAdminAiTextModelProvider(requestParameters: ToggleAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiTextModelProvider> {
        const response = await this.toggleAdminAiTextModelProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for toggleAdminImageModelProvider without sending the request
     */
    async toggleAdminImageModelProviderRequestOpts(requestParameters: ToggleAdminImageModelProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling toggleAdminImageModelProvider().'
            );
        }

        if (requestParameters['imageModelProviderToggleRequest'] == null) {
            throw new runtime.RequiredError(
                'imageModelProviderToggleRequest',
                'Required parameter "imageModelProviderToggleRequest" was null or undefined when calling toggleAdminImageModelProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/image-model-providers/{id}/toggle`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImageModelProviderToggleRequestToJSON(requestParameters['imageModelProviderToggleRequest']),
        };
    }

    /**
     * Enable or disable an image generation model provider.
     */
    async toggleAdminImageModelProviderRaw(requestParameters: ToggleAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageModelProvider>> {
        const requestOptions = await this.toggleAdminImageModelProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageModelProviderFromJSON(jsonValue));
    }

    /**
     * Enable or disable an image generation model provider.
     */
    async toggleAdminImageModelProvider(requestParameters: ToggleAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageModelProvider> {
        const response = await this.toggleAdminImageModelProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateAdminAiTextModelProvider without sending the request
     */
    async updateAdminAiTextModelProviderRequestOpts(requestParameters: UpdateAdminAiTextModelProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAdminAiTextModelProvider().'
            );
        }

        if (requestParameters['aiTextModelProviderWriteRequest'] == null) {
            throw new runtime.RequiredError(
                'aiTextModelProviderWriteRequest',
                'Required parameter "aiTextModelProviderWriteRequest" was null or undefined when calling updateAdminAiTextModelProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/internal/admin/ai-text-model-providers/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AiTextModelProviderWriteRequestToJSON(requestParameters['aiTextModelProviderWriteRequest']),
        };
    }

    /**
     */
    async updateAdminAiTextModelProviderRaw(requestParameters: UpdateAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiTextModelProvider>> {
        const requestOptions = await this.updateAdminAiTextModelProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiTextModelProviderFromJSON(jsonValue));
    }

    /**
     */
    async updateAdminAiTextModelProvider(requestParameters: UpdateAdminAiTextModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiTextModelProvider> {
        const response = await this.updateAdminAiTextModelProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateAdminImageModelProvider without sending the request
     */
    async updateAdminImageModelProviderRequestOpts(requestParameters: UpdateAdminImageModelProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAdminImageModelProvider().'
            );
        }

        if (requestParameters['imageModelProviderWriteRequest'] == null) {
            throw new runtime.RequiredError(
                'imageModelProviderWriteRequest',
                'Required parameter "imageModelProviderWriteRequest" was null or undefined when calling updateAdminImageModelProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/image-model-providers/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ImageModelProviderWriteRequestToJSON(requestParameters['imageModelProviderWriteRequest']),
        };
    }

    /**
     * Update an image generation model provider.
     */
    async updateAdminImageModelProviderRaw(requestParameters: UpdateAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageModelProvider>> {
        const requestOptions = await this.updateAdminImageModelProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageModelProviderFromJSON(jsonValue));
    }

    /**
     * Update an image generation model provider.
     */
    async updateAdminImageModelProvider(requestParameters: UpdateAdminImageModelProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageModelProvider> {
        const response = await this.updateAdminImageModelProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for upsertAdminImageGenUsage without sending the request
     */
    async upsertAdminImageGenUsageRequestOpts(requestParameters: UpsertAdminImageGenUsageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['usageCode'] == null) {
            throw new runtime.RequiredError(
                'usageCode',
                'Required parameter "usageCode" was null or undefined when calling upsertAdminImageGenUsage().'
            );
        }

        if (requestParameters['imageGenUsageWriteRequest'] == null) {
            throw new runtime.RequiredError(
                'imageGenUsageWriteRequest',
                'Required parameter "imageGenUsageWriteRequest" was null or undefined when calling upsertAdminImageGenUsage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Internal-Token"] = await this.configuration.apiKey("X-Internal-Token"); // internalToken authentication
        }


        let urlPath = `/internal/admin/image-gen-usages/{usageCode}`;
        urlPath = urlPath.replace('{usageCode}', encodeURIComponent(String(requestParameters['usageCode'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ImageGenUsageWriteRequestToJSON(requestParameters['imageGenUsageWriteRequest']),
        };
    }

    /**
     * Create or update a business usage to image provider mapping.
     */
    async upsertAdminImageGenUsageRaw(requestParameters: UpsertAdminImageGenUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageGenUsage>> {
        const requestOptions = await this.upsertAdminImageGenUsageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageGenUsageFromJSON(jsonValue));
    }

    /**
     * Create or update a business usage to image provider mapping.
     */
    async upsertAdminImageGenUsage(requestParameters: UpsertAdminImageGenUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageGenUsage> {
        const response = await this.upsertAdminImageGenUsageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListAdminFamiliesStatusEnum = {
    active: 'active',
    locked: 'locked',
    deleting: 'deleting',
    deleted: 'deleted'
} as const;
export type ListAdminFamiliesStatusEnum = typeof ListAdminFamiliesStatusEnum[keyof typeof ListAdminFamiliesStatusEnum];
