/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateFamilyRequest,
    CreateFamilyRequestFromJSON,
    CreateFamilyRequestToJSON,
} from '../models/CreateFamilyRequest';
import {
    type Family,
    FamilyFromJSON,
    FamilyToJSON,
} from '../models/Family';
import {
    type FamilyDevice,
    FamilyDeviceFromJSON,
    FamilyDeviceToJSON,
} from '../models/FamilyDevice';
import {
    type FamilyInvite,
    FamilyInviteFromJSON,
    FamilyInviteToJSON,
} from '../models/FamilyInvite';
import {
    type FamilyMember,
    FamilyMemberFromJSON,
    FamilyMemberToJSON,
} from '../models/FamilyMember';
import {
    type InviteParentRequest,
    InviteParentRequestFromJSON,
    InviteParentRequestToJSON,
} from '../models/InviteParentRequest';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type RevokeDeviceRequest,
    RevokeDeviceRequestFromJSON,
    RevokeDeviceRequestToJSON,
} from '../models/RevokeDeviceRequest';

export interface CreateFamilyOperationRequest {
    createFamilyRequest: CreateFamilyRequest;
    idempotencyKey?: string;
}

export interface GetFamilyRequest {
    familyId: string;
}

export interface InviteParentOperationRequest {
    familyId: string;
    inviteParentRequest: InviteParentRequest;
    idempotencyKey?: string;
}

export interface ListFamilyDevicesRequest {
    familyId: string;
}

export interface ListFamilyMembersRequest {
    familyId: string;
}

export interface RevokeFamilyDeviceRequest {
    familyId: string;
    deviceId: string;
    revokeDeviceRequest?: RevokeDeviceRequest;
}

/**
 * FamiliesApi - interface
 * 
 * @export
 * @interface FamiliesApiInterface
 */
export interface FamiliesApiInterface {
    /**
     * Creates request options for createFamily without sending the request
     * @param {CreateFamilyRequest} createFamilyRequest 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof FamiliesApiInterface
     */
    createFamilyRequestOpts(requestParameters: CreateFamilyOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a family.
     * @param {CreateFamilyRequest} createFamilyRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FamiliesApiInterface
     */
    createFamilyRaw(requestParameters: CreateFamilyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Family>>;

    /**
     * Create a family.
     */
    createFamily(requestParameters: CreateFamilyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Family>;

    /**
     * Creates request options for getFamily without sending the request
     * @param {string} familyId 
     * @throws {RequiredError}
     * @memberof FamiliesApiInterface
     */
    getFamilyRequestOpts(requestParameters: GetFamilyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get family details.
     * @param {string} familyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FamiliesApiInterface
     */
    getFamilyRaw(requestParameters: GetFamilyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Family>>;

    /**
     * Get family details.
     */
    getFamily(requestParameters: GetFamilyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Family>;

    /**
     * Creates request options for inviteParent without sending the request
     * @param {string} familyId 
     * @param {InviteParentRequest} inviteParentRequest 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof FamiliesApiInterface
     */
    inviteParentRequestOpts(requestParameters: InviteParentOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Invite a parent to a family.
     * @param {string} familyId 
     * @param {InviteParentRequest} inviteParentRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FamiliesApiInterface
     */
    inviteParentRaw(requestParameters: InviteParentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FamilyInvite>>;

    /**
     * Invite a parent to a family.
     */
    inviteParent(requestParameters: InviteParentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FamilyInvite>;

    /**
     * Creates request options for listFamilyDevices without sending the request
     * @param {string} familyId 
     * @throws {RequiredError}
     * @memberof FamiliesApiInterface
     */
    listFamilyDevicesRequestOpts(requestParameters: ListFamilyDevicesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List paired devices in a family.
     * @param {string} familyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FamiliesApiInterface
     */
    listFamilyDevicesRaw(requestParameters: ListFamilyDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FamilyDevice>>>;

    /**
     * List paired devices in a family.
     */
    listFamilyDevices(requestParameters: ListFamilyDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FamilyDevice>>;

    /**
     * Creates request options for listFamilyMembers without sending the request
     * @param {string} familyId 
     * @throws {RequiredError}
     * @memberof FamiliesApiInterface
     */
    listFamilyMembersRequestOpts(requestParameters: ListFamilyMembersRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List family members.
     * @param {string} familyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FamiliesApiInterface
     */
    listFamilyMembersRaw(requestParameters: ListFamilyMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FamilyMember>>>;

    /**
     * List family members.
     */
    listFamilyMembers(requestParameters: ListFamilyMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FamilyMember>>;

    /**
     * Creates request options for revokeFamilyDevice without sending the request
     * @param {string} familyId 
     * @param {string} deviceId 
     * @param {RevokeDeviceRequest} [revokeDeviceRequest] 
     * @throws {RequiredError}
     * @memberof FamiliesApiInterface
     */
    revokeFamilyDeviceRequestOpts(requestParameters: RevokeFamilyDeviceRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Revoke a paired device. Repeated revocation is idempotent.
     * @param {string} familyId 
     * @param {string} deviceId 
     * @param {RevokeDeviceRequest} [revokeDeviceRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FamiliesApiInterface
     */
    revokeFamilyDeviceRaw(requestParameters: RevokeFamilyDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FamilyDevice>>;

    /**
     * Revoke a paired device. Repeated revocation is idempotent.
     */
    revokeFamilyDevice(requestParameters: RevokeFamilyDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FamilyDevice>;

}

/**
 * 
 */
export class FamiliesApi extends runtime.BaseAPI implements FamiliesApiInterface {

    /**
     * Creates request options for createFamily without sending the request
     */
    async createFamilyRequestOpts(requestParameters: CreateFamilyOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createFamilyRequest'] == null) {
            throw new runtime.RequiredError(
                'createFamilyRequest',
                'Required parameter "createFamilyRequest" was null or undefined when calling createFamily().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/families`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFamilyRequestToJSON(requestParameters['createFamilyRequest']),
        };
    }

    /**
     * Create a family.
     */
    async createFamilyRaw(requestParameters: CreateFamilyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Family>> {
        const requestOptions = await this.createFamilyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FamilyFromJSON(jsonValue));
    }

    /**
     * Create a family.
     */
    async createFamily(requestParameters: CreateFamilyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Family> {
        const response = await this.createFamilyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFamily without sending the request
     */
    async getFamilyRequestOpts(requestParameters: GetFamilyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['familyId'] == null) {
            throw new runtime.RequiredError(
                'familyId',
                'Required parameter "familyId" was null or undefined when calling getFamily().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/families/{familyId}`;
        urlPath = urlPath.replace('{familyId}', encodeURIComponent(String(requestParameters['familyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get family details.
     */
    async getFamilyRaw(requestParameters: GetFamilyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Family>> {
        const requestOptions = await this.getFamilyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FamilyFromJSON(jsonValue));
    }

    /**
     * Get family details.
     */
    async getFamily(requestParameters: GetFamilyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Family> {
        const response = await this.getFamilyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for inviteParent without sending the request
     */
    async inviteParentRequestOpts(requestParameters: InviteParentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['familyId'] == null) {
            throw new runtime.RequiredError(
                'familyId',
                'Required parameter "familyId" was null or undefined when calling inviteParent().'
            );
        }

        if (requestParameters['inviteParentRequest'] == null) {
            throw new runtime.RequiredError(
                'inviteParentRequest',
                'Required parameter "inviteParentRequest" was null or undefined when calling inviteParent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/families/{familyId}/invites`;
        urlPath = urlPath.replace('{familyId}', encodeURIComponent(String(requestParameters['familyId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InviteParentRequestToJSON(requestParameters['inviteParentRequest']),
        };
    }

    /**
     * Invite a parent to a family.
     */
    async inviteParentRaw(requestParameters: InviteParentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FamilyInvite>> {
        const requestOptions = await this.inviteParentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FamilyInviteFromJSON(jsonValue));
    }

    /**
     * Invite a parent to a family.
     */
    async inviteParent(requestParameters: InviteParentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FamilyInvite> {
        const response = await this.inviteParentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listFamilyDevices without sending the request
     */
    async listFamilyDevicesRequestOpts(requestParameters: ListFamilyDevicesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['familyId'] == null) {
            throw new runtime.RequiredError(
                'familyId',
                'Required parameter "familyId" was null or undefined when calling listFamilyDevices().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/families/{familyId}/devices`;
        urlPath = urlPath.replace('{familyId}', encodeURIComponent(String(requestParameters['familyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List paired devices in a family.
     */
    async listFamilyDevicesRaw(requestParameters: ListFamilyDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FamilyDevice>>> {
        const requestOptions = await this.listFamilyDevicesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FamilyDeviceFromJSON));
    }

    /**
     * List paired devices in a family.
     */
    async listFamilyDevices(requestParameters: ListFamilyDevicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FamilyDevice>> {
        const response = await this.listFamilyDevicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listFamilyMembers without sending the request
     */
    async listFamilyMembersRequestOpts(requestParameters: ListFamilyMembersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['familyId'] == null) {
            throw new runtime.RequiredError(
                'familyId',
                'Required parameter "familyId" was null or undefined when calling listFamilyMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/families/{familyId}/members`;
        urlPath = urlPath.replace('{familyId}', encodeURIComponent(String(requestParameters['familyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List family members.
     */
    async listFamilyMembersRaw(requestParameters: ListFamilyMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FamilyMember>>> {
        const requestOptions = await this.listFamilyMembersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FamilyMemberFromJSON));
    }

    /**
     * List family members.
     */
    async listFamilyMembers(requestParameters: ListFamilyMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FamilyMember>> {
        const response = await this.listFamilyMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeFamilyDevice without sending the request
     */
    async revokeFamilyDeviceRequestOpts(requestParameters: RevokeFamilyDeviceRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['familyId'] == null) {
            throw new runtime.RequiredError(
                'familyId',
                'Required parameter "familyId" was null or undefined when calling revokeFamilyDevice().'
            );
        }

        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling revokeFamilyDevice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/families/{familyId}/devices/{deviceId}/revoke`;
        urlPath = urlPath.replace('{familyId}', encodeURIComponent(String(requestParameters['familyId'])));
        urlPath = urlPath.replace('{deviceId}', encodeURIComponent(String(requestParameters['deviceId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RevokeDeviceRequestToJSON(requestParameters['revokeDeviceRequest']),
        };
    }

    /**
     * Revoke a paired device. Repeated revocation is idempotent.
     */
    async revokeFamilyDeviceRaw(requestParameters: RevokeFamilyDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FamilyDevice>> {
        const requestOptions = await this.revokeFamilyDeviceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FamilyDeviceFromJSON(jsonValue));
    }

    /**
     * Revoke a paired device. Repeated revocation is idempotent.
     */
    async revokeFamilyDevice(requestParameters: RevokeFamilyDeviceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FamilyDevice> {
        const response = await this.revokeFamilyDeviceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
