/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateUploadSessionRequest,
    CreateUploadSessionRequestFromJSON,
    CreateUploadSessionRequestToJSON,
} from '../models/CreateUploadSessionRequest';
import {
    type FinalizeMediaRequest,
    FinalizeMediaRequestFromJSON,
    FinalizeMediaRequestToJSON,
} from '../models/FinalizeMediaRequest';
import {
    type MediaAsset,
    MediaAssetFromJSON,
    MediaAssetToJSON,
} from '../models/MediaAsset';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type UploadSession,
    UploadSessionFromJSON,
    UploadSessionToJSON,
} from '../models/UploadSession';

export interface CreateUploadSessionOperationRequest {
    createUploadSessionRequest: CreateUploadSessionRequest;
    idempotencyKey?: string;
}

export interface FinalizeMediaOperationRequest {
    mediaId: string;
    finalizeMediaRequest: FinalizeMediaRequest;
    idempotencyKey?: string;
}

/**
 * MediaApi - interface
 * 
 * @export
 * @interface MediaApiInterface
 */
export interface MediaApiInterface {
    /**
     * Creates request options for createUploadSession without sending the request
     * @param {CreateUploadSessionRequest} createUploadSessionRequest 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof MediaApiInterface
     */
    createUploadSessionRequestOpts(requestParameters: CreateUploadSessionOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a signed upload session.
     * @param {CreateUploadSessionRequest} createUploadSessionRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApiInterface
     */
    createUploadSessionRaw(requestParameters: CreateUploadSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadSession>>;

    /**
     * Create a signed upload session.
     */
    createUploadSession(requestParameters: CreateUploadSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadSession>;

    /**
     * Creates request options for finalizeMedia without sending the request
     * @param {string} mediaId 
     * @param {FinalizeMediaRequest} finalizeMediaRequest 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof MediaApiInterface
     */
    finalizeMediaRequestOpts(requestParameters: FinalizeMediaOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Finalize a media upload.
     * @param {string} mediaId 
     * @param {FinalizeMediaRequest} finalizeMediaRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaApiInterface
     */
    finalizeMediaRaw(requestParameters: FinalizeMediaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MediaAsset>>;

    /**
     * Finalize a media upload.
     */
    finalizeMedia(requestParameters: FinalizeMediaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MediaAsset>;

}

/**
 * 
 */
export class MediaApi extends runtime.BaseAPI implements MediaApiInterface {

    /**
     * Creates request options for createUploadSession without sending the request
     */
    async createUploadSessionRequestOpts(requestParameters: CreateUploadSessionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createUploadSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'createUploadSessionRequest',
                'Required parameter "createUploadSessionRequest" was null or undefined when calling createUploadSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/media/upload-sessions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUploadSessionRequestToJSON(requestParameters['createUploadSessionRequest']),
        };
    }

    /**
     * Create a signed upload session.
     */
    async createUploadSessionRaw(requestParameters: CreateUploadSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadSession>> {
        const requestOptions = await this.createUploadSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadSessionFromJSON(jsonValue));
    }

    /**
     * Create a signed upload session.
     */
    async createUploadSession(requestParameters: CreateUploadSessionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadSession> {
        const response = await this.createUploadSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for finalizeMedia without sending the request
     */
    async finalizeMediaRequestOpts(requestParameters: FinalizeMediaOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mediaId'] == null) {
            throw new runtime.RequiredError(
                'mediaId',
                'Required parameter "mediaId" was null or undefined when calling finalizeMedia().'
            );
        }

        if (requestParameters['finalizeMediaRequest'] == null) {
            throw new runtime.RequiredError(
                'finalizeMediaRequest',
                'Required parameter "finalizeMediaRequest" was null or undefined when calling finalizeMedia().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/media/{mediaId}/finalize`;
        urlPath = urlPath.replace('{mediaId}', encodeURIComponent(String(requestParameters['mediaId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FinalizeMediaRequestToJSON(requestParameters['finalizeMediaRequest']),
        };
    }

    /**
     * Finalize a media upload.
     */
    async finalizeMediaRaw(requestParameters: FinalizeMediaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MediaAsset>> {
        const requestOptions = await this.finalizeMediaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MediaAssetFromJSON(jsonValue));
    }

    /**
     * Finalize a media upload.
     */
    async finalizeMedia(requestParameters: FinalizeMediaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MediaAsset> {
        const response = await this.finalizeMediaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
