/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ExportMemoryRequest,
    ExportMemoryRequestFromJSON,
    ExportMemoryRequestToJSON,
} from '../models/ExportMemoryRequest';
import {
    type MemoryExport,
    MemoryExportFromJSON,
    MemoryExportToJSON,
} from '../models/MemoryExport';
import {
    type MemoryTimeline,
    MemoryTimelineFromJSON,
    MemoryTimelineToJSON,
} from '../models/MemoryTimeline';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type WeeklyMemory,
    WeeklyMemoryFromJSON,
    WeeklyMemoryToJSON,
} from '../models/WeeklyMemory';

export interface ExportMemoryOperationRequest {
    memoryId: string;
    exportMemoryRequest: ExportMemoryRequest;
    idempotencyKey?: string;
}

export interface GetMemoryRequest {
    memoryId: string;
}

export interface ListMemoriesRequest {
    childId: string;
    cursor?: string;
}

/**
 * MemoriesApi - interface
 * 
 * @export
 * @interface MemoriesApiInterface
 */
export interface MemoriesApiInterface {
    /**
     * Creates request options for exportMemory without sending the request
     * @param {string} memoryId 
     * @param {ExportMemoryRequest} exportMemoryRequest 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof MemoriesApiInterface
     */
    exportMemoryRequestOpts(requestParameters: ExportMemoryOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Request memory export.
     * @param {string} memoryId 
     * @param {ExportMemoryRequest} exportMemoryRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoriesApiInterface
     */
    exportMemoryRaw(requestParameters: ExportMemoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemoryExport>>;

    /**
     * Request memory export.
     */
    exportMemory(requestParameters: ExportMemoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemoryExport>;

    /**
     * Creates request options for getMemory without sending the request
     * @param {string} memoryId 
     * @throws {RequiredError}
     * @memberof MemoriesApiInterface
     */
    getMemoryRequestOpts(requestParameters: GetMemoryRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a memory detail.
     * @param {string} memoryId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoriesApiInterface
     */
    getMemoryRaw(requestParameters: GetMemoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WeeklyMemory>>;

    /**
     * Get a memory detail.
     */
    getMemory(requestParameters: GetMemoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WeeklyMemory>;

    /**
     * Creates request options for listMemories without sending the request
     * @param {string} childId 
     * @param {string} [cursor] 
     * @throws {RequiredError}
     * @memberof MemoriesApiInterface
     */
    listMemoriesRequestOpts(requestParameters: ListMemoriesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List memories for a child.
     * @param {string} childId 
     * @param {string} [cursor] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoriesApiInterface
     */
    listMemoriesRaw(requestParameters: ListMemoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemoryTimeline>>;

    /**
     * List memories for a child.
     */
    listMemories(requestParameters: ListMemoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemoryTimeline>;

}

/**
 * 
 */
export class MemoriesApi extends runtime.BaseAPI implements MemoriesApiInterface {

    /**
     * Creates request options for exportMemory without sending the request
     */
    async exportMemoryRequestOpts(requestParameters: ExportMemoryOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memoryId'] == null) {
            throw new runtime.RequiredError(
                'memoryId',
                'Required parameter "memoryId" was null or undefined when calling exportMemory().'
            );
        }

        if (requestParameters['exportMemoryRequest'] == null) {
            throw new runtime.RequiredError(
                'exportMemoryRequest',
                'Required parameter "exportMemoryRequest" was null or undefined when calling exportMemory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/memories/{memoryId}/export`;
        urlPath = urlPath.replace('{memoryId}', encodeURIComponent(String(requestParameters['memoryId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExportMemoryRequestToJSON(requestParameters['exportMemoryRequest']),
        };
    }

    /**
     * Request memory export.
     */
    async exportMemoryRaw(requestParameters: ExportMemoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemoryExport>> {
        const requestOptions = await this.exportMemoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemoryExportFromJSON(jsonValue));
    }

    /**
     * Request memory export.
     */
    async exportMemory(requestParameters: ExportMemoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemoryExport> {
        const response = await this.exportMemoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMemory without sending the request
     */
    async getMemoryRequestOpts(requestParameters: GetMemoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memoryId'] == null) {
            throw new runtime.RequiredError(
                'memoryId',
                'Required parameter "memoryId" was null or undefined when calling getMemory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/memories/{memoryId}`;
        urlPath = urlPath.replace('{memoryId}', encodeURIComponent(String(requestParameters['memoryId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a memory detail.
     */
    async getMemoryRaw(requestParameters: GetMemoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WeeklyMemory>> {
        const requestOptions = await this.getMemoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WeeklyMemoryFromJSON(jsonValue));
    }

    /**
     * Get a memory detail.
     */
    async getMemory(requestParameters: GetMemoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WeeklyMemory> {
        const response = await this.getMemoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMemories without sending the request
     */
    async listMemoriesRequestOpts(requestParameters: ListMemoriesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['childId'] == null) {
            throw new runtime.RequiredError(
                'childId',
                'Required parameter "childId" was null or undefined when calling listMemories().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['childId'] != null) {
            queryParameters['childId'] = requestParameters['childId'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/memories`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List memories for a child.
     */
    async listMemoriesRaw(requestParameters: ListMemoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemoryTimeline>> {
        const requestOptions = await this.listMemoriesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemoryTimelineFromJSON(jsonValue));
    }

    /**
     * List memories for a child.
     */
    async listMemories(requestParameters: ListMemoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemoryTimeline> {
        const response = await this.listMemoriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
