/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type SaveWeeklyPlanRequest,
    SaveWeeklyPlanRequestFromJSON,
    SaveWeeklyPlanRequestToJSON,
} from '../models/SaveWeeklyPlanRequest';
import {
    type WeeklyPlan,
    WeeklyPlanFromJSON,
    WeeklyPlanToJSON,
} from '../models/WeeklyPlan';

export interface GetWeeklyPlanRequest {
    planId: string;
}

export interface SaveWeeklyPlanOperationRequest {
    saveWeeklyPlanRequest: SaveWeeklyPlanRequest;
    idempotencyKey?: string;
}

/**
 * PlansApi - interface
 * 
 * @export
 * @interface PlansApiInterface
 */
export interface PlansApiInterface {
    /**
     * Creates request options for getWeeklyPlan without sending the request
     * @param {string} planId 
     * @throws {RequiredError}
     * @memberof PlansApiInterface
     */
    getWeeklyPlanRequestOpts(requestParameters: GetWeeklyPlanRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a weekly plan.
     * @param {string} planId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlansApiInterface
     */
    getWeeklyPlanRaw(requestParameters: GetWeeklyPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WeeklyPlan>>;

    /**
     * Get a weekly plan.
     */
    getWeeklyPlan(requestParameters: GetWeeklyPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WeeklyPlan>;

    /**
     * Creates request options for saveWeeklyPlan without sending the request
     * @param {SaveWeeklyPlanRequest} saveWeeklyPlanRequest 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof PlansApiInterface
     */
    saveWeeklyPlanRequestOpts(requestParameters: SaveWeeklyPlanOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create or update a weekly plan.
     * @param {SaveWeeklyPlanRequest} saveWeeklyPlanRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlansApiInterface
     */
    saveWeeklyPlanRaw(requestParameters: SaveWeeklyPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WeeklyPlan>>;

    /**
     * Create or update a weekly plan.
     */
    saveWeeklyPlan(requestParameters: SaveWeeklyPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WeeklyPlan>;

}

/**
 * 
 */
export class PlansApi extends runtime.BaseAPI implements PlansApiInterface {

    /**
     * Creates request options for getWeeklyPlan without sending the request
     */
    async getWeeklyPlanRequestOpts(requestParameters: GetWeeklyPlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['planId'] == null) {
            throw new runtime.RequiredError(
                'planId',
                'Required parameter "planId" was null or undefined when calling getWeeklyPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/plans/{planId}`;
        urlPath = urlPath.replace('{planId}', encodeURIComponent(String(requestParameters['planId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a weekly plan.
     */
    async getWeeklyPlanRaw(requestParameters: GetWeeklyPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WeeklyPlan>> {
        const requestOptions = await this.getWeeklyPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WeeklyPlanFromJSON(jsonValue));
    }

    /**
     * Get a weekly plan.
     */
    async getWeeklyPlan(requestParameters: GetWeeklyPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WeeklyPlan> {
        const response = await this.getWeeklyPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for saveWeeklyPlan without sending the request
     */
    async saveWeeklyPlanRequestOpts(requestParameters: SaveWeeklyPlanOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['saveWeeklyPlanRequest'] == null) {
            throw new runtime.RequiredError(
                'saveWeeklyPlanRequest',
                'Required parameter "saveWeeklyPlanRequest" was null or undefined when calling saveWeeklyPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/plans`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveWeeklyPlanRequestToJSON(requestParameters['saveWeeklyPlanRequest']),
        };
    }

    /**
     * Create or update a weekly plan.
     */
    async saveWeeklyPlanRaw(requestParameters: SaveWeeklyPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WeeklyPlan>> {
        const requestOptions = await this.saveWeeklyPlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WeeklyPlanFromJSON(jsonValue));
    }

    /**
     * Create or update a weekly plan.
     */
    async saveWeeklyPlan(requestParameters: SaveWeeklyPlanOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WeeklyPlan> {
        const response = await this.saveWeeklyPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
