/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PrivacyRequest,
    PrivacyRequestFromJSON,
    PrivacyRequestToJSON,
} from '../models/PrivacyRequest';
import {
    type PrivacyRequestCreate,
    PrivacyRequestCreateFromJSON,
    PrivacyRequestCreateToJSON,
} from '../models/PrivacyRequestCreate';
import {
    type PrivacyRequestList,
    PrivacyRequestListFromJSON,
    PrivacyRequestListToJSON,
} from '../models/PrivacyRequestList';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';

export interface ListPrivacyRequestsRequest {
    familyId: string;
}

export interface RequestDataExportRequest {
    privacyRequestCreate: PrivacyRequestCreate;
    idempotencyKey?: string;
}

export interface RequestFamilyDeletionRequest {
    privacyRequestCreate: PrivacyRequestCreate;
    idempotencyKey?: string;
}

/**
 * PrivacyApi - interface
 * 
 * @export
 * @interface PrivacyApiInterface
 */
export interface PrivacyApiInterface {
    /**
     * Creates request options for listPrivacyRequests without sending the request
     * @param {string} familyId 
     * @throws {RequiredError}
     * @memberof PrivacyApiInterface
     */
    listPrivacyRequestsRequestOpts(requestParameters: ListPrivacyRequestsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List family privacy requests and export download links.
     * @param {string} familyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrivacyApiInterface
     */
    listPrivacyRequestsRaw(requestParameters: ListPrivacyRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PrivacyRequestList>>;

    /**
     * List family privacy requests and export download links.
     */
    listPrivacyRequests(requestParameters: ListPrivacyRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PrivacyRequestList>;

    /**
     * Creates request options for requestDataExport without sending the request
     * @param {PrivacyRequestCreate} privacyRequestCreate 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof PrivacyApiInterface
     */
    requestDataExportRequestOpts(requestParameters: RequestDataExportRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Request family data export.
     * @param {PrivacyRequestCreate} privacyRequestCreate 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrivacyApiInterface
     */
    requestDataExportRaw(requestParameters: RequestDataExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PrivacyRequest>>;

    /**
     * Request family data export.
     */
    requestDataExport(requestParameters: RequestDataExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PrivacyRequest>;

    /**
     * Creates request options for requestFamilyDeletion without sending the request
     * @param {PrivacyRequestCreate} privacyRequestCreate 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof PrivacyApiInterface
     */
    requestFamilyDeletionRequestOpts(requestParameters: RequestFamilyDeletionRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Request family deletion.
     * @param {PrivacyRequestCreate} privacyRequestCreate 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrivacyApiInterface
     */
    requestFamilyDeletionRaw(requestParameters: RequestFamilyDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PrivacyRequest>>;

    /**
     * Request family deletion.
     */
    requestFamilyDeletion(requestParameters: RequestFamilyDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PrivacyRequest>;

}

/**
 * 
 */
export class PrivacyApi extends runtime.BaseAPI implements PrivacyApiInterface {

    /**
     * Creates request options for listPrivacyRequests without sending the request
     */
    async listPrivacyRequestsRequestOpts(requestParameters: ListPrivacyRequestsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['familyId'] == null) {
            throw new runtime.RequiredError(
                'familyId',
                'Required parameter "familyId" was null or undefined when calling listPrivacyRequests().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/families/{familyId}/privacy-requests`;
        urlPath = urlPath.replace('{familyId}', encodeURIComponent(String(requestParameters['familyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List family privacy requests and export download links.
     */
    async listPrivacyRequestsRaw(requestParameters: ListPrivacyRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PrivacyRequestList>> {
        const requestOptions = await this.listPrivacyRequestsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PrivacyRequestListFromJSON(jsonValue));
    }

    /**
     * List family privacy requests and export download links.
     */
    async listPrivacyRequests(requestParameters: ListPrivacyRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PrivacyRequestList> {
        const response = await this.listPrivacyRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestDataExport without sending the request
     */
    async requestDataExportRequestOpts(requestParameters: RequestDataExportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['privacyRequestCreate'] == null) {
            throw new runtime.RequiredError(
                'privacyRequestCreate',
                'Required parameter "privacyRequestCreate" was null or undefined when calling requestDataExport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/privacy/export`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PrivacyRequestCreateToJSON(requestParameters['privacyRequestCreate']),
        };
    }

    /**
     * Request family data export.
     */
    async requestDataExportRaw(requestParameters: RequestDataExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PrivacyRequest>> {
        const requestOptions = await this.requestDataExportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PrivacyRequestFromJSON(jsonValue));
    }

    /**
     * Request family data export.
     */
    async requestDataExport(requestParameters: RequestDataExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PrivacyRequest> {
        const response = await this.requestDataExportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestFamilyDeletion without sending the request
     */
    async requestFamilyDeletionRequestOpts(requestParameters: RequestFamilyDeletionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['privacyRequestCreate'] == null) {
            throw new runtime.RequiredError(
                'privacyRequestCreate',
                'Required parameter "privacyRequestCreate" was null or undefined when calling requestFamilyDeletion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/privacy/delete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PrivacyRequestCreateToJSON(requestParameters['privacyRequestCreate']),
        };
    }

    /**
     * Request family deletion.
     */
    async requestFamilyDeletionRaw(requestParameters: RequestFamilyDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PrivacyRequest>> {
        const requestOptions = await this.requestFamilyDeletionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PrivacyRequestFromJSON(jsonValue));
    }

    /**
     * Request family deletion.
     */
    async requestFamilyDeletion(requestParameters: RequestFamilyDeletionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PrivacyRequest> {
        const response = await this.requestFamilyDeletionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
