/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PendingReviewCard,
    PendingReviewCardFromJSON,
    PendingReviewCardToJSON,
} from '../models/PendingReviewCard';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type Review,
    ReviewFromJSON,
    ReviewToJSON,
} from '../models/Review';
import {
    type ReviewBatchRequest,
    ReviewBatchRequestFromJSON,
    ReviewBatchRequestToJSON,
} from '../models/ReviewBatchRequest';
import {
    type ReviewBatchResponse,
    ReviewBatchResponseFromJSON,
    ReviewBatchResponseToJSON,
} from '../models/ReviewBatchResponse';
import {
    type ReviewSubmissionRequest,
    ReviewSubmissionRequestFromJSON,
    ReviewSubmissionRequestToJSON,
} from '../models/ReviewSubmissionRequest';
import {
    type RevokeReviewRequest,
    RevokeReviewRequestFromJSON,
    RevokeReviewRequestToJSON,
} from '../models/RevokeReviewRequest';
import {
    type SubmissionDetail,
    SubmissionDetailFromJSON,
    SubmissionDetailToJSON,
} from '../models/SubmissionDetail';

export interface GetReviewDetailRequest {
    submissionId: string;
}

export interface ListPendingReviewsRequest {
    familyId: string;
}

export interface ReviewSubmissionOperationRequest {
    reviewSubmissionRequest: ReviewSubmissionRequest;
    idempotencyKey?: string;
}

export interface ReviewSubmissionsBatchRequest {
    reviewBatchRequest: ReviewBatchRequest;
}

export interface RevokeReviewOperationRequest {
    reviewId: string;
    revokeReviewRequest: RevokeReviewRequest;
    idempotencyKey?: string;
}

/**
 * ReviewsApi - interface
 * 
 * @export
 * @interface ReviewsApiInterface
 */
export interface ReviewsApiInterface {
    /**
     * Creates request options for getReviewDetail without sending the request
     * @param {string} submissionId 
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    getReviewDetailRequestOpts(requestParameters: GetReviewDetailRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a review detail view for a submission.
     * @param {string} submissionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    getReviewDetailRaw(requestParameters: GetReviewDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmissionDetail>>;

    /**
     * Get a review detail view for a submission.
     */
    getReviewDetail(requestParameters: GetReviewDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmissionDetail>;

    /**
     * Creates request options for listPendingReviews without sending the request
     * @param {string} familyId 
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    listPendingReviewsRequestOpts(requestParameters: ListPendingReviewsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List pending reviews.
     * @param {string} familyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    listPendingReviewsRaw(requestParameters: ListPendingReviewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PendingReviewCard>>>;

    /**
     * List pending reviews.
     */
    listPendingReviews(requestParameters: ListPendingReviewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PendingReviewCard>>;

    /**
     * Creates request options for reviewSubmission without sending the request
     * @param {ReviewSubmissionRequest} reviewSubmissionRequest 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewSubmissionRequestOpts(requestParameters: ReviewSubmissionOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Approve or reject a submission.
     * @param {ReviewSubmissionRequest} reviewSubmissionRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewSubmissionRaw(requestParameters: ReviewSubmissionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Review>>;

    /**
     * Approve or reject a submission.
     */
    reviewSubmission(requestParameters: ReviewSubmissionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Review>;

    /**
     * Creates request options for reviewSubmissionsBatch without sending the request
     * @param {ReviewBatchRequest} reviewBatchRequest 
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewSubmissionsBatchRequestOpts(requestParameters: ReviewSubmissionsBatchRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Approve or reject multiple submissions independently.
     * @param {ReviewBatchRequest} reviewBatchRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    reviewSubmissionsBatchRaw(requestParameters: ReviewSubmissionsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReviewBatchResponse>>;

    /**
     * Approve or reject multiple submissions independently.
     */
    reviewSubmissionsBatch(requestParameters: ReviewSubmissionsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReviewBatchResponse>;

    /**
     * Creates request options for revokeReview without sending the request
     * @param {string} reviewId 
     * @param {RevokeReviewRequest} revokeReviewRequest 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    revokeReviewRequestOpts(requestParameters: RevokeReviewOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Revoke a review and create adjustment records when needed.
     * @param {string} reviewId 
     * @param {RevokeReviewRequest} revokeReviewRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReviewsApiInterface
     */
    revokeReviewRaw(requestParameters: RevokeReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Review>>;

    /**
     * Revoke a review and create adjustment records when needed.
     */
    revokeReview(requestParameters: RevokeReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Review>;

}

/**
 * 
 */
export class ReviewsApi extends runtime.BaseAPI implements ReviewsApiInterface {

    /**
     * Creates request options for getReviewDetail without sending the request
     */
    async getReviewDetailRequestOpts(requestParameters: GetReviewDetailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['submissionId'] == null) {
            throw new runtime.RequiredError(
                'submissionId',
                'Required parameter "submissionId" was null or undefined when calling getReviewDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reviews/{submissionId}/detail`;
        urlPath = urlPath.replace('{submissionId}', encodeURIComponent(String(requestParameters['submissionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a review detail view for a submission.
     */
    async getReviewDetailRaw(requestParameters: GetReviewDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmissionDetail>> {
        const requestOptions = await this.getReviewDetailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmissionDetailFromJSON(jsonValue));
    }

    /**
     * Get a review detail view for a submission.
     */
    async getReviewDetail(requestParameters: GetReviewDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmissionDetail> {
        const response = await this.getReviewDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listPendingReviews without sending the request
     */
    async listPendingReviewsRequestOpts(requestParameters: ListPendingReviewsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['familyId'] == null) {
            throw new runtime.RequiredError(
                'familyId',
                'Required parameter "familyId" was null or undefined when calling listPendingReviews().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['familyId'] != null) {
            queryParameters['familyId'] = requestParameters['familyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reviews/pending`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List pending reviews.
     */
    async listPendingReviewsRaw(requestParameters: ListPendingReviewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PendingReviewCard>>> {
        const requestOptions = await this.listPendingReviewsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PendingReviewCardFromJSON));
    }

    /**
     * List pending reviews.
     */
    async listPendingReviews(requestParameters: ListPendingReviewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PendingReviewCard>> {
        const response = await this.listPendingReviewsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reviewSubmission without sending the request
     */
    async reviewSubmissionRequestOpts(requestParameters: ReviewSubmissionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reviewSubmissionRequest'] == null) {
            throw new runtime.RequiredError(
                'reviewSubmissionRequest',
                'Required parameter "reviewSubmissionRequest" was null or undefined when calling reviewSubmission().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reviews`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReviewSubmissionRequestToJSON(requestParameters['reviewSubmissionRequest']),
        };
    }

    /**
     * Approve or reject a submission.
     */
    async reviewSubmissionRaw(requestParameters: ReviewSubmissionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Review>> {
        const requestOptions = await this.reviewSubmissionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReviewFromJSON(jsonValue));
    }

    /**
     * Approve or reject a submission.
     */
    async reviewSubmission(requestParameters: ReviewSubmissionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Review> {
        const response = await this.reviewSubmissionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reviewSubmissionsBatch without sending the request
     */
    async reviewSubmissionsBatchRequestOpts(requestParameters: ReviewSubmissionsBatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reviewBatchRequest'] == null) {
            throw new runtime.RequiredError(
                'reviewBatchRequest',
                'Required parameter "reviewBatchRequest" was null or undefined when calling reviewSubmissionsBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reviews/batch`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReviewBatchRequestToJSON(requestParameters['reviewBatchRequest']),
        };
    }

    /**
     * Approve or reject multiple submissions independently.
     */
    async reviewSubmissionsBatchRaw(requestParameters: ReviewSubmissionsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReviewBatchResponse>> {
        const requestOptions = await this.reviewSubmissionsBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReviewBatchResponseFromJSON(jsonValue));
    }

    /**
     * Approve or reject multiple submissions independently.
     */
    async reviewSubmissionsBatch(requestParameters: ReviewSubmissionsBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReviewBatchResponse> {
        const response = await this.reviewSubmissionsBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeReview without sending the request
     */
    async revokeReviewRequestOpts(requestParameters: RevokeReviewOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reviewId'] == null) {
            throw new runtime.RequiredError(
                'reviewId',
                'Required parameter "reviewId" was null or undefined when calling revokeReview().'
            );
        }

        if (requestParameters['revokeReviewRequest'] == null) {
            throw new runtime.RequiredError(
                'revokeReviewRequest',
                'Required parameter "revokeReviewRequest" was null or undefined when calling revokeReview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/reviews/{reviewId}/revoke`;
        urlPath = urlPath.replace('{reviewId}', encodeURIComponent(String(requestParameters['reviewId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RevokeReviewRequestToJSON(requestParameters['revokeReviewRequest']),
        };
    }

    /**
     * Revoke a review and create adjustment records when needed.
     */
    async revokeReviewRaw(requestParameters: RevokeReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Review>> {
        const requestOptions = await this.revokeReviewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReviewFromJSON(jsonValue));
    }

    /**
     * Revoke a review and create adjustment records when needed.
     */
    async revokeReview(requestParameters: RevokeReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Review> {
        const response = await this.revokeReviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
