/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateSubmissionRequest,
    CreateSubmissionRequestFromJSON,
    CreateSubmissionRequestToJSON,
} from '../models/CreateSubmissionRequest';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type Submission,
    SubmissionFromJSON,
    SubmissionToJSON,
} from '../models/Submission';
import {
    type SubmissionDetail,
    SubmissionDetailFromJSON,
    SubmissionDetailToJSON,
} from '../models/SubmissionDetail';

export interface CreateSubmissionOperationRequest {
    createSubmissionRequest: CreateSubmissionRequest;
    idempotencyKey?: string;
}

export interface GetSubmissionRequest {
    submissionId: string;
}

/**
 * SubmissionsApi - interface
 * 
 * @export
 * @interface SubmissionsApiInterface
 */
export interface SubmissionsApiInterface {
    /**
     * Creates request options for createSubmission without sending the request
     * @param {CreateSubmissionRequest} createSubmissionRequest 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof SubmissionsApiInterface
     */
    createSubmissionRequestOpts(requestParameters: CreateSubmissionOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a child submission.
     * @param {CreateSubmissionRequest} createSubmissionRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubmissionsApiInterface
     */
    createSubmissionRaw(requestParameters: CreateSubmissionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Submission>>;

    /**
     * Create a child submission.
     */
    createSubmission(requestParameters: CreateSubmissionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Submission>;

    /**
     * Creates request options for getSubmission without sending the request
     * @param {string} submissionId 
     * @throws {RequiredError}
     * @memberof SubmissionsApiInterface
     */
    getSubmissionRequestOpts(requestParameters: GetSubmissionRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get submission details.
     * @param {string} submissionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SubmissionsApiInterface
     */
    getSubmissionRaw(requestParameters: GetSubmissionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmissionDetail>>;

    /**
     * Get submission details.
     */
    getSubmission(requestParameters: GetSubmissionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmissionDetail>;

}

/**
 * 
 */
export class SubmissionsApi extends runtime.BaseAPI implements SubmissionsApiInterface {

    /**
     * Creates request options for createSubmission without sending the request
     */
    async createSubmissionRequestOpts(requestParameters: CreateSubmissionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createSubmissionRequest'] == null) {
            throw new runtime.RequiredError(
                'createSubmissionRequest',
                'Required parameter "createSubmissionRequest" was null or undefined when calling createSubmission().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/submissions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSubmissionRequestToJSON(requestParameters['createSubmissionRequest']),
        };
    }

    /**
     * Create a child submission.
     */
    async createSubmissionRaw(requestParameters: CreateSubmissionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Submission>> {
        const requestOptions = await this.createSubmissionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmissionFromJSON(jsonValue));
    }

    /**
     * Create a child submission.
     */
    async createSubmission(requestParameters: CreateSubmissionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Submission> {
        const response = await this.createSubmissionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSubmission without sending the request
     */
    async getSubmissionRequestOpts(requestParameters: GetSubmissionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['submissionId'] == null) {
            throw new runtime.RequiredError(
                'submissionId',
                'Required parameter "submissionId" was null or undefined when calling getSubmission().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/submissions/{submissionId}`;
        urlPath = urlPath.replace('{submissionId}', encodeURIComponent(String(requestParameters['submissionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get submission details.
     */
    async getSubmissionRaw(requestParameters: GetSubmissionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmissionDetail>> {
        const requestOptions = await this.getSubmissionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmissionDetailFromJSON(jsonValue));
    }

    /**
     * Get submission details.
     */
    async getSubmission(requestParameters: GetSubmissionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmissionDetail> {
        const response = await this.getSubmissionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
