/* tslint:disable */
/* eslint-disable */
/**
 * WishPool API
 * WishPool core API contract for mobile apps, parent web, admin web, and backend services. All write endpoints are command-oriented and should be called with an Idempotency-Key header. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AttachWishImageRequest,
    AttachWishImageRequestFromJSON,
    AttachWishImageRequestToJSON,
} from '../models/AttachWishImageRequest';
import {
    type BusinessImageModelProviderList,
    BusinessImageModelProviderListFromJSON,
    BusinessImageModelProviderListToJSON,
} from '../models/BusinessImageModelProviderList';
import {
    type CreateWishImageGenerationRequest,
    CreateWishImageGenerationRequestFromJSON,
    CreateWishImageGenerationRequestToJSON,
} from '../models/CreateWishImageGenerationRequest';
import {
    type CreateWishRequest,
    CreateWishRequestFromJSON,
    CreateWishRequestToJSON,
} from '../models/CreateWishRequest';
import {
    type Problem,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/Problem';
import {
    type RedeemWishRequest,
    RedeemWishRequestFromJSON,
    RedeemWishRequestToJSON,
} from '../models/RedeemWishRequest';
import {
    type Wish,
    WishFromJSON,
    WishToJSON,
} from '../models/Wish';
import {
    type WishHistoryItem,
    WishHistoryItemFromJSON,
    WishHistoryItemToJSON,
} from '../models/WishHistoryItem';
import {
    type WishImageCandidateRequest,
    WishImageCandidateRequestFromJSON,
    WishImageCandidateRequestToJSON,
} from '../models/WishImageCandidateRequest';
import {
    type WishImageCandidateResponse,
    WishImageCandidateResponseFromJSON,
    WishImageCandidateResponseToJSON,
} from '../models/WishImageCandidateResponse';
import {
    type WishImageGenerationJob,
    WishImageGenerationJobFromJSON,
    WishImageGenerationJobToJSON,
} from '../models/WishImageGenerationJob';
import {
    type WishRedemption,
    WishRedemptionFromJSON,
    WishRedemptionToJSON,
} from '../models/WishRedemption';

export interface ActivateWishRequest {
    wishId: string;
    idempotencyKey?: string;
}

export interface AttachWishImageOperationRequest {
    wishId: string;
    attachWishImageRequest: AttachWishImageRequest;
}

export interface CreateWishOperationRequest {
    createWishRequest: CreateWishRequest;
    idempotencyKey?: string;
}

export interface CreateWishImageGenerationOperationRequest {
    createWishImageGenerationRequest: CreateWishImageGenerationRequest;
}

export interface FindWishImageCandidatesRequest {
    wishImageCandidateRequest: WishImageCandidateRequest;
}

export interface GetCurrentWishRequest {
    childId: string;
}

export interface GetWishRequest {
    wishId: string;
}

export interface GetWishImageGenerationRequest {
    jobId: string;
}

export interface ListChildWishHistoryRequest {
    childId: string;
}

export interface ListChildWishesRequest {
    childId: string;
    weekId?: string;
}

export interface ListWishImageModelProvidersRequest {
    usageCode?: string;
}

export interface RedeemWishOperationRequest {
    wishId: string;
    redeemWishRequest: RedeemWishRequest;
    idempotencyKey?: string;
}

/**
 * WishesApi - interface
 * 
 * @export
 * @interface WishesApiInterface
 */
export interface WishesApiInterface {
    /**
     * Creates request options for activateWish without sending the request
     * @param {string} wishId 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    activateWishRequestOpts(requestParameters: ActivateWishRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Activate a wish.
     * @param {string} wishId 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    activateWishRaw(requestParameters: ActivateWishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wish>>;

    /**
     * Activate a wish.
     */
    activateWish(requestParameters: ActivateWishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wish>;

    /**
     * Creates request options for attachWishImage without sending the request
     * @param {string} wishId 
     * @param {AttachWishImageRequest} attachWishImageRequest 
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    attachWishImageRequestOpts(requestParameters: AttachWishImageOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Attach a finalized wish image to a wish.
     * @param {string} wishId 
     * @param {AttachWishImageRequest} attachWishImageRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    attachWishImageRaw(requestParameters: AttachWishImageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wish>>;

    /**
     * Attach a finalized wish image to a wish.
     */
    attachWishImage(requestParameters: AttachWishImageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wish>;

    /**
     * Creates request options for createWish without sending the request
     * @param {CreateWishRequest} createWishRequest 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    createWishRequestOpts(requestParameters: CreateWishOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a wish.
     * @param {CreateWishRequest} createWishRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    createWishRaw(requestParameters: CreateWishOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wish>>;

    /**
     * Create a wish.
     */
    createWish(requestParameters: CreateWishOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wish>;

    /**
     * Creates request options for createWishImageGeneration without sending the request
     * @param {CreateWishImageGenerationRequest} createWishImageGenerationRequest 
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    createWishImageGenerationRequestOpts(requestParameters: CreateWishImageGenerationOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a wish image generation job.
     * @param {CreateWishImageGenerationRequest} createWishImageGenerationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    createWishImageGenerationRaw(requestParameters: CreateWishImageGenerationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WishImageGenerationJob>>;

    /**
     * Create a wish image generation job.
     */
    createWishImageGeneration(requestParameters: CreateWishImageGenerationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WishImageGenerationJob>;

    /**
     * Creates request options for findWishImageCandidates without sending the request
     * @param {WishImageCandidateRequest} wishImageCandidateRequest 
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    findWishImageCandidatesRequestOpts(requestParameters: FindWishImageCandidatesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Find reusable wish image candidates for a new wish.
     * @param {WishImageCandidateRequest} wishImageCandidateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    findWishImageCandidatesRaw(requestParameters: FindWishImageCandidatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WishImageCandidateResponse>>;

    /**
     * Find reusable wish image candidates for a new wish.
     */
    findWishImageCandidates(requestParameters: FindWishImageCandidatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WishImageCandidateResponse>;

    /**
     * Creates request options for getCurrentWish without sending the request
     * @param {string} childId 
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    getCurrentWishRequestOpts(requestParameters: GetCurrentWishRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get the current wish for a child.
     * @param {string} childId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    getCurrentWishRaw(requestParameters: GetCurrentWishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wish>>;

    /**
     * Get the current wish for a child.
     */
    getCurrentWish(requestParameters: GetCurrentWishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wish>;

    /**
     * Creates request options for getWish without sending the request
     * @param {string} wishId 
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    getWishRequestOpts(requestParameters: GetWishRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a wish.
     * @param {string} wishId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    getWishRaw(requestParameters: GetWishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wish>>;

    /**
     * Get a wish.
     */
    getWish(requestParameters: GetWishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wish>;

    /**
     * Creates request options for getWishImageGeneration without sending the request
     * @param {string} jobId 
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    getWishImageGenerationRequestOpts(requestParameters: GetWishImageGenerationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get a wish image generation job.
     * @param {string} jobId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    getWishImageGenerationRaw(requestParameters: GetWishImageGenerationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WishImageGenerationJob>>;

    /**
     * Get a wish image generation job.
     */
    getWishImageGeneration(requestParameters: GetWishImageGenerationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WishImageGenerationJob>;

    /**
     * Creates request options for listChildWishHistory without sending the request
     * @param {string} childId 
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    listChildWishHistoryRequestOpts(requestParameters: ListChildWishHistoryRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List wish history items for a child.
     * @param {string} childId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    listChildWishHistoryRaw(requestParameters: ListChildWishHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WishHistoryItem>>>;

    /**
     * List wish history items for a child.
     */
    listChildWishHistory(requestParameters: ListChildWishHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WishHistoryItem>>;

    /**
     * Creates request options for listChildWishes without sending the request
     * @param {string} childId 
     * @param {string} [weekId] 
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    listChildWishesRequestOpts(requestParameters: ListChildWishesRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List wishes for a child.
     * @param {string} childId 
     * @param {string} [weekId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    listChildWishesRaw(requestParameters: ListChildWishesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Wish>>>;

    /**
     * List wishes for a child.
     */
    listChildWishes(requestParameters: ListChildWishesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Wish>>;

    /**
     * Creates request options for listWishImageModelProviders without sending the request
     * @param {string} [usageCode] 
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    listWishImageModelProvidersRequestOpts(requestParameters: ListWishImageModelProvidersRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List enabled image generation model providers for a business usage.
     * @param {string} [usageCode] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    listWishImageModelProvidersRaw(requestParameters: ListWishImageModelProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessImageModelProviderList>>;

    /**
     * List enabled image generation model providers for a business usage.
     */
    listWishImageModelProviders(requestParameters: ListWishImageModelProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessImageModelProviderList>;

    /**
     * Creates request options for redeemWish without sending the request
     * @param {string} wishId 
     * @param {RedeemWishRequest} redeemWishRequest 
     * @param {string} [idempotencyKey] 
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    redeemWishRequestOpts(requestParameters: RedeemWishOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Redeem an unlocked wish.
     * @param {string} wishId 
     * @param {RedeemWishRequest} redeemWishRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WishesApiInterface
     */
    redeemWishRaw(requestParameters: RedeemWishOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WishRedemption>>;

    /**
     * Redeem an unlocked wish.
     */
    redeemWish(requestParameters: RedeemWishOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WishRedemption>;

}

/**
 * 
 */
export class WishesApi extends runtime.BaseAPI implements WishesApiInterface {

    /**
     * Creates request options for activateWish without sending the request
     */
    async activateWishRequestOpts(requestParameters: ActivateWishRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['wishId'] == null) {
            throw new runtime.RequiredError(
                'wishId',
                'Required parameter "wishId" was null or undefined when calling activateWish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishes/{wishId}/activate`;
        urlPath = urlPath.replace('{wishId}', encodeURIComponent(String(requestParameters['wishId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Activate a wish.
     */
    async activateWishRaw(requestParameters: ActivateWishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wish>> {
        const requestOptions = await this.activateWishRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WishFromJSON(jsonValue));
    }

    /**
     * Activate a wish.
     */
    async activateWish(requestParameters: ActivateWishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wish> {
        const response = await this.activateWishRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for attachWishImage without sending the request
     */
    async attachWishImageRequestOpts(requestParameters: AttachWishImageOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['wishId'] == null) {
            throw new runtime.RequiredError(
                'wishId',
                'Required parameter "wishId" was null or undefined when calling attachWishImage().'
            );
        }

        if (requestParameters['attachWishImageRequest'] == null) {
            throw new runtime.RequiredError(
                'attachWishImageRequest',
                'Required parameter "attachWishImageRequest" was null or undefined when calling attachWishImage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishes/{wishId}/image`;
        urlPath = urlPath.replace('{wishId}', encodeURIComponent(String(requestParameters['wishId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AttachWishImageRequestToJSON(requestParameters['attachWishImageRequest']),
        };
    }

    /**
     * Attach a finalized wish image to a wish.
     */
    async attachWishImageRaw(requestParameters: AttachWishImageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wish>> {
        const requestOptions = await this.attachWishImageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WishFromJSON(jsonValue));
    }

    /**
     * Attach a finalized wish image to a wish.
     */
    async attachWishImage(requestParameters: AttachWishImageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wish> {
        const response = await this.attachWishImageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createWish without sending the request
     */
    async createWishRequestOpts(requestParameters: CreateWishOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWishRequest'] == null) {
            throw new runtime.RequiredError(
                'createWishRequest',
                'Required parameter "createWishRequest" was null or undefined when calling createWish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishes`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWishRequestToJSON(requestParameters['createWishRequest']),
        };
    }

    /**
     * Create a wish.
     */
    async createWishRaw(requestParameters: CreateWishOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wish>> {
        const requestOptions = await this.createWishRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WishFromJSON(jsonValue));
    }

    /**
     * Create a wish.
     */
    async createWish(requestParameters: CreateWishOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wish> {
        const response = await this.createWishRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createWishImageGeneration without sending the request
     */
    async createWishImageGenerationRequestOpts(requestParameters: CreateWishImageGenerationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWishImageGenerationRequest'] == null) {
            throw new runtime.RequiredError(
                'createWishImageGenerationRequest',
                'Required parameter "createWishImageGenerationRequest" was null or undefined when calling createWishImageGeneration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishes/image-generations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWishImageGenerationRequestToJSON(requestParameters['createWishImageGenerationRequest']),
        };
    }

    /**
     * Create a wish image generation job.
     */
    async createWishImageGenerationRaw(requestParameters: CreateWishImageGenerationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WishImageGenerationJob>> {
        const requestOptions = await this.createWishImageGenerationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WishImageGenerationJobFromJSON(jsonValue));
    }

    /**
     * Create a wish image generation job.
     */
    async createWishImageGeneration(requestParameters: CreateWishImageGenerationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WishImageGenerationJob> {
        const response = await this.createWishImageGenerationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for findWishImageCandidates without sending the request
     */
    async findWishImageCandidatesRequestOpts(requestParameters: FindWishImageCandidatesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['wishImageCandidateRequest'] == null) {
            throw new runtime.RequiredError(
                'wishImageCandidateRequest',
                'Required parameter "wishImageCandidateRequest" was null or undefined when calling findWishImageCandidates().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishes/image-candidates`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WishImageCandidateRequestToJSON(requestParameters['wishImageCandidateRequest']),
        };
    }

    /**
     * Find reusable wish image candidates for a new wish.
     */
    async findWishImageCandidatesRaw(requestParameters: FindWishImageCandidatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WishImageCandidateResponse>> {
        const requestOptions = await this.findWishImageCandidatesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WishImageCandidateResponseFromJSON(jsonValue));
    }

    /**
     * Find reusable wish image candidates for a new wish.
     */
    async findWishImageCandidates(requestParameters: FindWishImageCandidatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WishImageCandidateResponse> {
        const response = await this.findWishImageCandidatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCurrentWish without sending the request
     */
    async getCurrentWishRequestOpts(requestParameters: GetCurrentWishRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['childId'] == null) {
            throw new runtime.RequiredError(
                'childId',
                'Required parameter "childId" was null or undefined when calling getCurrentWish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/children/{childId}/wishes/current`;
        urlPath = urlPath.replace('{childId}', encodeURIComponent(String(requestParameters['childId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the current wish for a child.
     */
    async getCurrentWishRaw(requestParameters: GetCurrentWishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wish>> {
        const requestOptions = await this.getCurrentWishRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WishFromJSON(jsonValue));
    }

    /**
     * Get the current wish for a child.
     */
    async getCurrentWish(requestParameters: GetCurrentWishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wish> {
        const response = await this.getCurrentWishRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWish without sending the request
     */
    async getWishRequestOpts(requestParameters: GetWishRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['wishId'] == null) {
            throw new runtime.RequiredError(
                'wishId',
                'Required parameter "wishId" was null or undefined when calling getWish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishes/{wishId}`;
        urlPath = urlPath.replace('{wishId}', encodeURIComponent(String(requestParameters['wishId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a wish.
     */
    async getWishRaw(requestParameters: GetWishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Wish>> {
        const requestOptions = await this.getWishRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WishFromJSON(jsonValue));
    }

    /**
     * Get a wish.
     */
    async getWish(requestParameters: GetWishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Wish> {
        const response = await this.getWishRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getWishImageGeneration without sending the request
     */
    async getWishImageGenerationRequestOpts(requestParameters: GetWishImageGenerationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getWishImageGeneration().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishes/image-generations/{jobId}`;
        urlPath = urlPath.replace('{jobId}', encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a wish image generation job.
     */
    async getWishImageGenerationRaw(requestParameters: GetWishImageGenerationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WishImageGenerationJob>> {
        const requestOptions = await this.getWishImageGenerationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WishImageGenerationJobFromJSON(jsonValue));
    }

    /**
     * Get a wish image generation job.
     */
    async getWishImageGeneration(requestParameters: GetWishImageGenerationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WishImageGenerationJob> {
        const response = await this.getWishImageGenerationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listChildWishHistory without sending the request
     */
    async listChildWishHistoryRequestOpts(requestParameters: ListChildWishHistoryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['childId'] == null) {
            throw new runtime.RequiredError(
                'childId',
                'Required parameter "childId" was null or undefined when calling listChildWishHistory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/children/{childId}/wishes/history`;
        urlPath = urlPath.replace('{childId}', encodeURIComponent(String(requestParameters['childId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List wish history items for a child.
     */
    async listChildWishHistoryRaw(requestParameters: ListChildWishHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WishHistoryItem>>> {
        const requestOptions = await this.listChildWishHistoryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WishHistoryItemFromJSON));
    }

    /**
     * List wish history items for a child.
     */
    async listChildWishHistory(requestParameters: ListChildWishHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WishHistoryItem>> {
        const response = await this.listChildWishHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listChildWishes without sending the request
     */
    async listChildWishesRequestOpts(requestParameters: ListChildWishesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['childId'] == null) {
            throw new runtime.RequiredError(
                'childId',
                'Required parameter "childId" was null or undefined when calling listChildWishes().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['weekId'] != null) {
            queryParameters['weekId'] = requestParameters['weekId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/children/{childId}/wishes`;
        urlPath = urlPath.replace('{childId}', encodeURIComponent(String(requestParameters['childId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List wishes for a child.
     */
    async listChildWishesRaw(requestParameters: ListChildWishesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Wish>>> {
        const requestOptions = await this.listChildWishesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WishFromJSON));
    }

    /**
     * List wishes for a child.
     */
    async listChildWishes(requestParameters: ListChildWishesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Wish>> {
        const response = await this.listChildWishesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWishImageModelProviders without sending the request
     */
    async listWishImageModelProvidersRequestOpts(requestParameters: ListWishImageModelProvidersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['usageCode'] != null) {
            queryParameters['usageCode'] = requestParameters['usageCode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishes/image-model-providers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List enabled image generation model providers for a business usage.
     */
    async listWishImageModelProvidersRaw(requestParameters: ListWishImageModelProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessImageModelProviderList>> {
        const requestOptions = await this.listWishImageModelProvidersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessImageModelProviderListFromJSON(jsonValue));
    }

    /**
     * List enabled image generation model providers for a business usage.
     */
    async listWishImageModelProviders(requestParameters: ListWishImageModelProvidersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessImageModelProviderList> {
        const response = await this.listWishImageModelProvidersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for redeemWish without sending the request
     */
    async redeemWishRequestOpts(requestParameters: RedeemWishOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['wishId'] == null) {
            throw new runtime.RequiredError(
                'wishId',
                'Required parameter "wishId" was null or undefined when calling redeemWish().'
            );
        }

        if (requestParameters['redeemWishRequest'] == null) {
            throw new runtime.RequiredError(
                'redeemWishRequest',
                'Required parameter "redeemWishRequest" was null or undefined when calling redeemWish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishes/{wishId}/redeem`;
        urlPath = urlPath.replace('{wishId}', encodeURIComponent(String(requestParameters['wishId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RedeemWishRequestToJSON(requestParameters['redeemWishRequest']),
        };
    }

    /**
     * Redeem an unlocked wish.
     */
    async redeemWishRaw(requestParameters: RedeemWishOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WishRedemption>> {
        const requestOptions = await this.redeemWishRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WishRedemptionFromJSON(jsonValue));
    }

    /**
     * Redeem an unlocked wish.
     */
    async redeemWish(requestParameters: RedeemWishOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WishRedemption> {
        const response = await this.redeemWishRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
