"use client";

import { useMemo, useState } from "react";
import { useFormStatus } from "react-dom";
import { CalendarDays, Pencil, Plus, Trash2 } from "lucide-react";
import { saveWeeklyPlanAction } from "@/app/actions";
import type { TaskTemplateResponse } from "@/lib/dashboard-data";

export type WeeklyPlanRuleInput = {
  taskTemplateId?: string; title: string; category: string; submissionType: string; description?: string; targetText?: string;
  weekdays: number[]; isCore: boolean; requireReview: boolean; sortOrder?: number;
};
type PlanEditorProps = { rules: WeeklyPlanRuleInput[]; templates: TaskTemplateResponse[]; childId: string; weekId: string; startDate: string; endDate: string; rewardMode: string; disabled?: boolean };
const weekdays = ["周一", "周二", "周三", "周四", "周五", "周六", "周日"].map((label, index) => ({ value: index + 1, label }));
const categoryOptions = [{ value: "study", label: "学习" }, { value: "reading", label: "阅读" }, { value: "exercise", label: "运动" }, { value: "habit", label: "习惯" }, { value: "custom", label: "自定义" }];
const submissionOptions = [{ value: "photo", label: "照片" }, { value: "audio", label: "音频" }, { value: "video", label: "视频" }, { value: "manual", label: "手动" }];

export function PlanEditor({ rules, templates, childId, weekId, startDate, endDate, rewardMode, disabled = false }: Readonly<PlanEditorProps>) {
  const [currentRules, setCurrentRules] = useState<WeeklyPlanRuleInput[]>(() => normalizeRules(rules));
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [highlight, setHighlight] = useState<string | null>(null);
  const [customWeekdays, setCustomWeekdays] = useState<number[]>([1, 2, 3, 4, 5]);
  const rulesJson = useMemo(() => JSON.stringify(normalizeRules(currentRules)), [currentRules]);
  function nextSortOrder() { return currentRules.reduce((max, rule) => Math.max(max, rule.sortOrder ?? 0), 0) + 1; }
  function addTemplate(template: TaskTemplateResponse) { setCurrentRules((items) => [...items, { taskTemplateId: template.id, title: template.title, category: template.category, submissionType: template.submissionType, description: template.description ?? undefined, targetText: template.targetText ?? undefined, weekdays: [1, 2, 3, 4, 5], isCore: false, requireReview: false, sortOrder: nextSortOrder() }]); setHighlight(template.title); }
  function addCustomRule(formData: FormData) { const title = stringValue(formData.get("customTitle")); const category = stringValue(formData.get("customCategory")); const submissionType = stringValue(formData.get("customSubmissionType")); if (!title || !category || !submissionType || customWeekdays.length === 0) return; setCurrentRules((items) => [...items, { title, category, submissionType, weekdays: customWeekdays, isCore: formData.get("customIsCore") === "on", requireReview: formData.get("customRequireReview") === "on", sortOrder: nextSortOrder() }]); setHighlight(title); }
  function updateRule(index: number, formData: FormData) { const title = stringValue(formData.get("title")); const category = stringValue(formData.get("category")); const submissionType = stringValue(formData.get("submissionType")); const selectedDays = formData.getAll("weekdays").map(Number).filter((day) => day >= 1 && day <= 7).sort((a, b) => a - b); if (!title || !category || !submissionType || selectedDays.length === 0) return; setCurrentRules((items) => items.map((rule, itemIndex) => itemIndex === index ? { ...rule, title, category, submissionType, weekdays: selectedDays, isCore: formData.get("isCore") === "on", requireReview: formData.get("requireReview") === "on" } : rule)); setEditingIndex(null); setHighlight(title); }
  function toggleCustomDay(day: number) { setCustomWeekdays((items) => items.includes(day) ? items.filter((item) => item !== day) : [...items, day].sort((a, b) => a - b)); }
  return <div className="plan-editor">
    <section className="plan-editor-section" aria-label="计划规则编辑器"><div className="plan-editor-header"><h2>计划规则编辑</h2>{highlight ? <span className="status-pill status-ready">已更新：{highlight}</span> : null}</div>
      <div className="task-list">{currentRules.length === 0 ? <div className="empty-state"><CalendarDays size={20} aria-hidden="true" /><div><strong>本周还没有安排</strong><p className="muted">新增规则后保存，即可安排本周任务。</p></div></div> : currentRules.map((rule, index) => <div className="plan-rule-card" key={`${rule.title}-${rule.sortOrder ?? index}`}>{editingIndex === index ? <RuleForm rule={rule} onSubmit={(formData) => updateRule(index, formData)} onCancel={() => setEditingIndex(null)} disabled={disabled} /> : <><div><strong>{rule.title}</strong><p className="muted" style={{ margin: "6px 0 0" }}>{categoryLabel(rule.category)} · {submissionLabel(rule.submissionType)} · {rule.weekdays.map((day) => weekdays[day - 1]?.label).join("、")}</p></div><div className="task-actions"><span className="status-pill status-blue">{rule.weekdays.length} 天</span>{rule.isCore ? <span className="status-pill status-ready">核心</span> : null}{rule.requireReview ? <span className="status-pill status-waiting">需审核</span> : null}<button className="icon-button" disabled={disabled} type="button" aria-label={`编辑 ${rule.title}`} onClick={() => setEditingIndex(index)}><Pencil size={16} aria-hidden="true" /></button><button className="icon-button" disabled={disabled} type="button" aria-label={`删除 ${rule.title}`} onClick={() => setCurrentRules((items) => items.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={16} aria-hidden="true" /></button></div></>}</div>)}</div>
      <form action={saveWeeklyPlanAction} className="plan-actions"><input name="returnTo" type="hidden" value="/plan" /><input name="childId" type="hidden" value={childId} /><input name="weekId" type="hidden" value={weekId} /><input name="startDate" type="hidden" value={startDate} /><input name="endDate" type="hidden" value={endDate} /><input name="rewardMode" type="hidden" value={rewardMode} /><input name="rulesJson" type="hidden" value={rulesJson} /><SaveButton disabled={disabled || currentRules.length === 0} /></form>
    </section>
    <section className="plan-editor-section" aria-label="从模板加入计划"><h2>从任务模板加入</h2><div className="template-list">{templates.length === 0 ? <div className="empty-state"><Plus size={20} aria-hidden="true" /><div><strong>还没有任务模板</strong><p className="muted">创建模板后，可以一键加入本周计划。</p></div></div> : templates.map((template) => <div className="template-row" key={template.id}><div><strong>{template.title}</strong><p className="muted" style={{ margin: "6px 0 0" }}>{categoryLabel(template.category)} · {submissionLabel(template.submissionType)}</p></div><button className="secondary-button" disabled={disabled} type="button" onClick={() => addTemplate(template)}><Plus size={16} aria-hidden="true" />加入计划</button></div>)}</div></section>
    <section className="plan-editor-section" aria-label="添加自定义规则"><h2>新增规则</h2><form action={addCustomRule} className="plan-editor-form"><label>标题<input name="customTitle" placeholder="亲子阅读 20 分钟" required /></label><label>分类<select name="customCategory" defaultValue="reading">{categoryOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label>提交方式<select name="customSubmissionType" defaultValue="photo">{submissionOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><WeekdayFieldset selected={customWeekdays} onToggle={toggleCustomDay} name="customWeekdays" /><div className="plan-editor-row"><label className="inline-check"><input name="customIsCore" type="checkbox" />核心任务</label><label className="inline-check"><input name="customRequireReview" type="checkbox" />需要审核</label></div><button className="secondary-button" disabled={disabled || customWeekdays.length === 0} type="submit"><Plus size={16} aria-hidden="true" />新增规则</button></form></section>
  </div>;
}

function RuleForm({ rule, onSubmit, onCancel, disabled }: { rule: WeeklyPlanRuleInput; onSubmit: (formData: FormData) => void; onCancel: () => void; disabled: boolean }) {
  const [selectedDays, setSelectedDays] = useState(rule.weekdays);
  return <form action={onSubmit} className="plan-editor-form rule-edit-form"><label>标题<input name="title" defaultValue={rule.title} required /></label><label>分类<select name="category" defaultValue={rule.category}>{categoryOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label>提交方式<select name="submissionType" defaultValue={rule.submissionType}>{submissionOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><WeekdayFieldset selected={selectedDays} onToggle={(day) => setSelectedDays((items) => items.includes(day) ? items.filter((item) => item !== day) : [...items, day].sort((a, b) => a - b))} name="weekdays" /><div className="plan-editor-row"><label className="inline-check"><input name="isCore" type="checkbox" defaultChecked={rule.isCore} />核心任务</label><label className="inline-check"><input name="requireReview" type="checkbox" defaultChecked={rule.requireReview} />需要审核</label></div><div className="task-actions"><button className="primary-button" disabled={disabled} type="submit">保存修改</button><button className="secondary-button" disabled={disabled} onClick={onCancel} type="button">取消</button></div></form>;
}
function WeekdayFieldset({ selected, onToggle, name }: { selected: number[]; onToggle?: (day: number) => void; name: string }) { return <fieldset className="weekday-fieldset"><legend>安排日期</legend>{weekdays.map((day) => <label className="inline-check" key={day.value}><input checked={selected.includes(day.value)} name={name} type="checkbox" value={day.value} onChange={() => onToggle?.(day.value)} />{day.label}</label>)}</fieldset>; }
function SaveButton({ disabled }: { disabled: boolean }) { const { pending } = useFormStatus(); return <button className="primary-button" disabled={disabled || pending} type="submit">{pending ? "保存中…" : "保存计划"}</button>; }
function normalizeRules(rules: WeeklyPlanRuleInput[]) { return rules.map((rule, index) => ({ ...rule, sortOrder: rule.sortOrder ?? index })); }
function stringValue(value: FormDataEntryValue | null) { return typeof value === "string" && value.trim() ? value.trim() : null; }
function categoryLabel(value: string) { return categoryOptions.find((option) => option.value === value)?.label ?? value; }
function submissionLabel(value: string) { return submissionOptions.find((option) => option.value === value)?.label ?? value; }
